from __clrclasses__.System.Collections import ICollection as _n_0_t_0
from __clrclasses__.System.Configuration import ConfigurationElement as _n_1_t_0
from __clrclasses__.System.Configuration import ConfigurationElementCollection as _n_1_t_1
from __clrclasses__.System.Security.Authentication.ExtendedProtection import PolicyEnforcement as _n_2_t_0
from __clrclasses__.System.Security.Authentication.ExtendedProtection import ProtectionScenario as _n_2_t_1
from __clrclasses__.System.Security.Authentication.ExtendedProtection import ExtendedProtectionPolicy as _n_2_t_2
import typing
class ExtendedProtectionPolicyElement(_n_1_t_0):
    @property
    def CustomServiceNames(self) -> ServiceNameElementCollection:"""CustomServiceNames { get; } -> ServiceNameElementCollection"""
    @property
    def PolicyEnforcement(self) -> _n_2_t_0:"""PolicyEnforcement { get; set; } -> PolicyEnforcement"""
    @property
    def ProtectionScenario(self) -> _n_2_t_1:"""ProtectionScenario { get; set; } -> ProtectionScenario"""
    def __init__(self) -> ExtendedProtectionPolicyElement:...
    def BuildPolicy(self) -> _n_2_t_2:...
class ServiceNameElement(_n_1_t_0):
    @property
    def Name(self) -> str:"""Name { get; set; } -> str"""
    def __init__(self) -> ServiceNameElement:...
class ServiceNameElementCollection(_n_1_t_1, _n_0_t_0, typing.Iterable[ServiceNameElement]):
    @property
    def Item(self) -> ServiceNameElement:"""Item { get; set; } -> ServiceNameElement"""
    def __init__(self) -> ServiceNameElementCollection:...
    def Add(self, element: ServiceNameElement):...
    def Clear(self):...
    def IndexOf(self, element: ServiceNameElement) -> int:...
    def Remove(self, name: str):...
    def Remove(self, element: ServiceNameElement):...
    def RemoveAt(self, index: int):...
