from __clrclasses__.System import Delegate as _n_0_t_0
from __clrclasses__.System.Reflection import IReflect as _n_1_t_0
from __clrclasses__.System.Reflection import FieldInfo as _n_1_t_1
from __clrclasses__.System.Reflection import MethodInfo as _n_1_t_2
from __clrclasses__.System.Reflection import PropertyInfo as _n_1_t_3
from __clrclasses__.System.Reflection import MemberInfo as _n_1_t_4
import typing
class IExpando(_n_1_t_0):
    def AddField(self, name: str) -> _n_1_t_1:...
    def AddMethod(self, name: str, method: _n_0_t_0) -> _n_1_t_2:...
    def AddProperty(self, name: str) -> _n_1_t_3:...
    def RemoveMember(self, m: _n_1_t_4):...
