import __clrclasses__.System.IO.IsolatedStorage as IsolatedStorage
import __clrclasses__.System.IO.MemoryMappedFiles as MemoryMappedFiles
import __clrclasses__.System.IO.Pipes as Pipes
import __clrclasses__.System.IO.Ports as Ports
import __clrclasses__.System.IO.Compression as Compression
from __clrclasses__.System.IO import BinaryReader
from __clrclasses__.System.IO import BinaryWriter
from __clrclasses__.System.IO import BufferedStream
from __clrclasses__.System.IO import Directory
from __clrclasses__.System.IO import DirectoryInfo
from __clrclasses__.System.IO import DirectoryNotFoundException
from __clrclasses__.System.IO import DriveInfo
from __clrclasses__.System.IO import DriveNotFoundException
from __clrclasses__.System.IO import DriveType
from __clrclasses__.System.IO import EndOfStreamException
from __clrclasses__.System.IO import ErrorEventArgs
from __clrclasses__.System.IO import ErrorEventHandler
from __clrclasses__.System.IO import File
from __clrclasses__.System.IO import FileAccess
from __clrclasses__.System.IO import FileAttributes
from __clrclasses__.System.IO import FileInfo
from __clrclasses__.System.IO import FileLoadException
from __clrclasses__.System.IO import FileMode
from __clrclasses__.System.IO import FileNotFoundException
from __clrclasses__.System.IO import FileOptions
from __clrclasses__.System.IO import FileShare
from __clrclasses__.System.IO import FileStream
from __clrclasses__.System.IO import FileSystemEventArgs
from __clrclasses__.System.IO import FileSystemEventHandler
from __clrclasses__.System.IO import FileSystemInfo
from __clrclasses__.System.IO import FileSystemWatcher
from __clrclasses__.System.IO import HandleInheritability
from __clrclasses__.System.IO import InternalBufferOverflowException
from __clrclasses__.System.IO import InvalidDataException
from __clrclasses__.System.IO import IODescriptionAttribute
from __clrclasses__.System.IO import IOException
from __clrclasses__.System.IO import MemoryStream
from __clrclasses__.System.IO import NotifyFilters
from __clrclasses__.System.IO import Path
from __clrclasses__.System.IO import PathTooLongException
from __clrclasses__.System.IO import RenamedEventArgs
from __clrclasses__.System.IO import RenamedEventHandler
from __clrclasses__.System.IO import SearchOption
from __clrclasses__.System.IO import SeekOrigin
from __clrclasses__.System.IO import Stream
from __clrclasses__.System.IO import StreamReader
from __clrclasses__.System.IO import StreamWriter
from __clrclasses__.System.IO import StringReader
from __clrclasses__.System.IO import StringWriter
from __clrclasses__.System.IO import TextReader
from __clrclasses__.System.IO import TextWriter
from __clrclasses__.System.IO import UnmanagedMemoryAccessor
from __clrclasses__.System.IO import UnmanagedMemoryStream
from __clrclasses__.System.IO import WaitForChangedResult
from __clrclasses__.System.IO import WatcherChangeTypes
