from __clrclasses__.Autodesk.AutoCAD.ComponentModel import IPropertyProvider
from __clrclasses__.Autodesk.AutoCAD.ComponentModel import ITypeDescriptor
from __clrclasses__.Autodesk.AutoCAD.ComponentModel import PropertyDescriptorBase
from __clrclasses__.Autodesk.AutoCAD.ComponentModel import PropertyProviderAttribute
from __clrclasses__.Autodesk.AutoCAD.ComponentModel import TypeDescriptionProvider
from __clrclasses__.Autodesk.AutoCAD.ComponentModel import TypeDescriptor
from __clrclasses__.Autodesk.AutoCAD.ComponentModel import TypeManager
