import __clrclasses__.System.Configuration as Configuration
import __clrclasses__.System.IO as IO
import __clrclasses__.System.Security as Security
import __clrclasses__.System.Resources as Resources
import __clrclasses__.System.Globalization as Globalization
import __clrclasses__.System.Diagnostics as Diagnostics
import __clrclasses__.System.Reflection as Reflection
import __clrclasses__.System.Deployment as Deployment
import __clrclasses__.System.Runtime as Runtime
import __clrclasses__.System.Threading as Threading
import __clrclasses__.System.Dynamic as Dynamic
import __clrclasses__.System.Linq as Linq
import __clrclasses__.System.Management as Management
import __clrclasses__.System.Web as Web
import __clrclasses__.System.Timers as Timers
import __clrclasses__.System.Net as Net
import __clrclasses__.System.Windows as Windows
import __clrclasses__.System.Media as Media
import __clrclasses__.System.Collections as Collections
import __clrclasses__.System.ComponentModel as ComponentModel
import __clrclasses__.System.CodeDom as CodeDom
import __clrclasses__.System.Text as Text
from __clrclasses__.System import _AppDomain
from __clrclasses__.System import AccessViolationException
from __clrclasses__.System import Action
from __clrclasses__.System import ActivationContext
from __clrclasses__.System import Activator
from __clrclasses__.System import AggregateException
from __clrclasses__.System import AppContext
from __clrclasses__.System import AppDomain
from __clrclasses__.System import AppDomainInitializer
from __clrclasses__.System import AppDomainManager
from __clrclasses__.System import AppDomainManagerInitializationOptions
from __clrclasses__.System import AppDomainSetup
from __clrclasses__.System import AppDomainUnloadedException
from __clrclasses__.System import ApplicationException
from __clrclasses__.System import ApplicationId
from __clrclasses__.System import ApplicationIdentity
from __clrclasses__.System import ArgIterator
from __clrclasses__.System import ArgumentException
from __clrclasses__.System import ArgumentNullException
from __clrclasses__.System import ArgumentOutOfRangeException
from __clrclasses__.System import ArithmeticException
from __clrclasses__.System import Array
from __clrclasses__.System import ArraySegment
from __clrclasses__.System import ArrayTypeMismatchException
from __clrclasses__.System import AssemblyLoadEventArgs
from __clrclasses__.System import AssemblyLoadEventHandler
from __clrclasses__.System import AsyncCallback
from __clrclasses__.System import Attribute
from __clrclasses__.System import AttributeTargets
from __clrclasses__.System import AttributeUsageAttribute
from __clrclasses__.System import BadImageFormatException
from __clrclasses__.System import Base64FormattingOptions
from __clrclasses__.System import BitConverter
from __clrclasses__.System import Buffer
from __clrclasses__.System import Byte
from __clrclasses__.System import CannotUnloadAppDomainException
from __clrclasses__.System import Char
from __clrclasses__.System import CharEnumerator
from __clrclasses__.System import CLSCompliantAttribute
from __clrclasses__.System import Comparison
from __clrclasses__.System import Console
from __clrclasses__.System import ConsoleCancelEventArgs
from __clrclasses__.System import ConsoleCancelEventHandler
from __clrclasses__.System import ConsoleColor
from __clrclasses__.System import ConsoleKey
from __clrclasses__.System import ConsoleKeyInfo
from __clrclasses__.System import ConsoleModifiers
from __clrclasses__.System import ConsoleSpecialKey
from __clrclasses__.System import ContextBoundObject
from __clrclasses__.System import ContextMarshalException
from __clrclasses__.System import ContextStaticAttribute
from __clrclasses__.System import Convert
from __clrclasses__.System import Converter
from __clrclasses__.System import CrossAppDomainDelegate
from __clrclasses__.System import DataMisalignedException
from __clrclasses__.System import DateTime
from __clrclasses__.System import DateTimeKind
from __clrclasses__.System import DateTimeOffset
from __clrclasses__.System import DayOfWeek
from __clrclasses__.System import DBNull
from __clrclasses__.System import Decimal
from __clrclasses__.System import Delegate
from __clrclasses__.System import DivideByZeroException
from __clrclasses__.System import DllNotFoundException
from __clrclasses__.System import DuplicateWaitObjectException
from __clrclasses__.System import EntryPointNotFoundException
from __clrclasses__.System import Enum
from __clrclasses__.System import Environment
from __clrclasses__.System import EnvironmentVariableTarget
from __clrclasses__.System import EventArgs
from __clrclasses__.System import EventHandler
from __clrclasses__.System import Exception
from __clrclasses__.System import ExecutionEngineException
from __clrclasses__.System import FieldAccessException
from __clrclasses__.System import FileStyleUriParser
from __clrclasses__.System import FlagsAttribute
from __clrclasses__.System import FormatException
from __clrclasses__.System import FormattableString
from __clrclasses__.System import FtpStyleUriParser
from __clrclasses__.System import Func
from __clrclasses__.System import GC
from __clrclasses__.System import GCCollectionMode
from __clrclasses__.System import GCNotificationStatus
from __clrclasses__.System import GenericUriParser
from __clrclasses__.System import GenericUriParserOptions
from __clrclasses__.System import GopherStyleUriParser
from __clrclasses__.System import Guid
from __clrclasses__.System import HttpStyleUriParser
from __clrclasses__.System import IAppDomainSetup
from __clrclasses__.System import IAsyncResult
from __clrclasses__.System import ICloneable
from __clrclasses__.System import IComparable
from __clrclasses__.System import IConvertible
from __clrclasses__.System import ICustomFormatter
from __clrclasses__.System import IDisposable
from __clrclasses__.System import IEquatable
from __clrclasses__.System import IFormatProvider
from __clrclasses__.System import IFormattable
from __clrclasses__.System import IndexOutOfRangeException
from __clrclasses__.System import InsufficientExecutionStackException
from __clrclasses__.System import InsufficientMemoryException
from __clrclasses__.System import IntPtr
from __clrclasses__.System import InvalidCastException
from __clrclasses__.System import InvalidOperationException
from __clrclasses__.System import InvalidProgramException
from __clrclasses__.System import InvalidTimeZoneException
from __clrclasses__.System import IObservable
from __clrclasses__.System import IObserver
from __clrclasses__.System import IProgress
from __clrclasses__.System import IServiceProvider
from __clrclasses__.System import Lazy
from __clrclasses__.System import LdapStyleUriParser
from __clrclasses__.System import LoaderOptimization
from __clrclasses__.System import LoaderOptimizationAttribute
from __clrclasses__.System import LocalDataStoreSlot
from __clrclasses__.System import MarshalByRefObject
from __clrclasses__.System import Math
from __clrclasses__.System import MemberAccessException
from __clrclasses__.System import MethodAccessException
from __clrclasses__.System import MidpointRounding
from __clrclasses__.System import MissingFieldException
from __clrclasses__.System import MissingMemberException
from __clrclasses__.System import MissingMethodException
from __clrclasses__.System import ModuleHandle
from __clrclasses__.System import MTAThreadAttribute
from __clrclasses__.System import MulticastDelegate
from __clrclasses__.System import MulticastNotSupportedException
from __clrclasses__.System import NetPipeStyleUriParser
from __clrclasses__.System import NetTcpStyleUriParser
from __clrclasses__.System import NewsStyleUriParser
from __clrclasses__.System import NonSerializedAttribute
from __clrclasses__.System import NotFiniteNumberException
from __clrclasses__.System import NotImplementedException
from __clrclasses__.System import NotSupportedException
from __clrclasses__.System import Nullable
from __clrclasses__.System import NullReferenceException
from __clrclasses__.System import ObjectDisposedException
from __clrclasses__.System import ObsoleteAttribute
from __clrclasses__.System import OperatingSystem
from __clrclasses__.System import OperationCanceledException
from __clrclasses__.System import OutOfMemoryException
from __clrclasses__.System import OverflowException
from __clrclasses__.System import ParamArrayAttribute
from __clrclasses__.System import PlatformID
from __clrclasses__.System import PlatformNotSupportedException
from __clrclasses__.System import Predicate
from __clrclasses__.System import Progress
from __clrclasses__.System import Random
from __clrclasses__.System import RankException
from __clrclasses__.System import ResolveEventArgs
from __clrclasses__.System import ResolveEventHandler
from __clrclasses__.System import RuntimeArgumentHandle
from __clrclasses__.System import RuntimeFieldHandle
from __clrclasses__.System import RuntimeMethodHandle
from __clrclasses__.System import RuntimeTypeHandle
from __clrclasses__.System import SByte
from __clrclasses__.System import SerializableAttribute
from __clrclasses__.System import StackOverflowException
from __clrclasses__.System import STAThreadAttribute
from __clrclasses__.System import StringComparer
from __clrclasses__.System import StringComparison
from __clrclasses__.System import StringNormalizationExtensions
from __clrclasses__.System import StringSplitOptions
from __clrclasses__.System import SystemException
from __clrclasses__.System import ThreadStaticAttribute
from __clrclasses__.System import TimeoutException
from __clrclasses__.System import TimeSpan
from __clrclasses__.System import TimeZone
from __clrclasses__.System import TimeZoneInfo
from __clrclasses__.System import TimeZoneNotFoundException
from __clrclasses__.System import Tuple
from __clrclasses__.System import TupleExtensions
from __clrclasses__.System import Type
from __clrclasses__.System import TypeAccessException
from __clrclasses__.System import TypeCode
from __clrclasses__.System import TypedReference
from __clrclasses__.System import TypeInitializationException
from __clrclasses__.System import TypeLoadException
from __clrclasses__.System import TypeUnloadedException
from __clrclasses__.System import UInt16
from __clrclasses__.System import UInt32
from __clrclasses__.System import UInt64
from __clrclasses__.System import UIntPtr
from __clrclasses__.System import UnauthorizedAccessException
from __clrclasses__.System import UnhandledExceptionEventArgs
from __clrclasses__.System import UnhandledExceptionEventHandler
from __clrclasses__.System import Uri
from __clrclasses__.System import UriBuilder
from __clrclasses__.System import UriComponents
from __clrclasses__.System import UriFormat
from __clrclasses__.System import UriFormatException
from __clrclasses__.System import UriHostNameType
from __clrclasses__.System import UriIdnScope
from __clrclasses__.System import UriKind
from __clrclasses__.System import UriParser
from __clrclasses__.System import UriPartial
from __clrclasses__.System import UriTypeConverter
from __clrclasses__.System import ValueTuple
from __clrclasses__.System import ValueType
from __clrclasses__.System import Version
from __clrclasses__.System import WeakReference
