from __clrclasses__.Atil import Image as _n_0_t_0
from __clrclasses__.Autodesk.AutoCAD.ApplicationServices import Document as _n_1_t_0
from __clrclasses__.Autodesk.AutoCAD.Runtime import ErrorStatus as _n_2_t_0
from __clrclasses__.System import IDisposable as _n_3_t_0
from __clrclasses__.System import Byte as _n_3_t_1
from __clrclasses__.System import Array as _n_3_t_2
from __clrclasses__.System.Collections.Specialized import StringCollection as _n_4_t_0
from __clrclasses__.System.Drawing import Bitmap as _n_5_t_0
import typing
class PairedImage(_n_3_t_0):
    @property
    def ManagedBitMap(self) -> _n_5_t_0:"""ManagedBitMap { get; set; } -> Bitmap"""
    @property
    def UnmanagedBitmap(self) -> _n_0_t_0:"""UnmanagedBitmap { get; set; } -> Image"""
    def __init__(self) -> PairedImage:...
class RenderUtil(object):
    def __init__(self) -> RenderUtil:...
    @staticmethod
    def CreateCustomPreset(presetName: str, presetDescription: str, basePresetName: str) -> _n_2_t_0:...
    @staticmethod
    def DeleteCustomPreset(presetName: str) -> _n_2_t_0:...
    @staticmethod
    def DoModalRenderSaveFileDlg(pStrPath: str, filterExtName: _n_4_t_0, filterExt: _n_4_t_0, caption: str, invalidFileName: str) -> bool:...
    @staticmethod
    def GetSceneResString(id: int) -> str:...
    @staticmethod
    def GetSceneResXMLBlob(id: int) -> _n_3_t_2[_n_3_t_1]:...
    @staticmethod
    def GetViewportImage() -> PairedImage:...
    @staticmethod
    def RenameCustomPreset(presetName: str, newPresetName: str) -> _n_2_t_0:...
    @staticmethod
    def SaveImage(fileName: str, strFormat: str, imagePair: PairedImage) -> bool:...
    @staticmethod
    def SaveRenderJobImage(fileName: str, strFormat: str, jobIndex: int, pDoc: _n_1_t_0) -> bool:...
