from __clrclasses__.System.Net.WebSockets import ClientWebSocket
from __clrclasses__.System.Net.WebSockets import ClientWebSocketOptions
from __clrclasses__.System.Net.WebSockets import HttpListenerWebSocketContext
from __clrclasses__.System.Net.WebSockets import WebSocket
from __clrclasses__.System.Net.WebSockets import WebSocketCloseStatus
from __clrclasses__.System.Net.WebSockets import WebSocketContext
from __clrclasses__.System.Net.WebSockets import WebSocketError
from __clrclasses__.System.Net.WebSockets import WebSocketException
from __clrclasses__.System.Net.WebSockets import WebSocketMessageType
from __clrclasses__.System.Net.WebSockets import WebSocketReceiveResult
from __clrclasses__.System.Net.WebSockets import WebSocketState
