from __clrclasses__.System.Net.Mail import AlternateView
from __clrclasses__.System.Net.Mail import AlternateViewCollection
from __clrclasses__.System.Net.Mail import Attachment
from __clrclasses__.System.Net.Mail import AttachmentBase
from __clrclasses__.System.Net.Mail import AttachmentCollection
from __clrclasses__.System.Net.Mail import DeliveryNotificationOptions
from __clrclasses__.System.Net.Mail import LinkedResource
from __clrclasses__.System.Net.Mail import LinkedResourceCollection
from __clrclasses__.System.Net.Mail import MailAddress
from __clrclasses__.System.Net.Mail import MailAddressCollection
from __clrclasses__.System.Net.Mail import MailMessage
from __clrclasses__.System.Net.Mail import MailPriority
from __clrclasses__.System.Net.Mail import SendCompletedEventHandler
from __clrclasses__.System.Net.Mail import SmtpAccess
from __clrclasses__.System.Net.Mail import SmtpClient
from __clrclasses__.System.Net.Mail import SmtpDeliveryFormat
from __clrclasses__.System.Net.Mail import SmtpDeliveryMethod
from __clrclasses__.System.Net.Mail import SmtpException
from __clrclasses__.System.Net.Mail import SmtpFailedRecipientException
from __clrclasses__.System.Net.Mail import SmtpFailedRecipientsException
from __clrclasses__.System.Net.Mail import SmtpPermission
from __clrclasses__.System.Net.Mail import SmtpPermissionAttribute
from __clrclasses__.System.Net.Mail import SmtpStatusCode
