
commands = {
    "pytest.cmds.entity.helloworld": "",
    "pytest.cmds.entity.mtexttest": "",
    "pytest.cmds.entity.mtexttest2": "",
    "pytest.cmds.entity.randtest": "",
    "pytest.cmds.entity.mycir": "",
    "pytest.cmds.entity.mycir2": "",
    "pytest.cmds.entity.mycir3": "",
    "pytest.cmds.entity.myline": "",
    "pytest.cmds.entity.myline2": "",
    "pytest.cmds.entity.mypl3d": "",
    "pytest.cmds.form.mymsg": "",
    "pytest.cmds.form.showwpf": "",
    "pytest.cmds.form.showfrm": "",
    "pytest.cmds.gecurve.ccitest": "",
    "pytest.cmds.gecurve.ccitest2": "",
    "pytest.cmds.gecurve.mindict": "",
    "pytest.cmds.gecurve.comptest": "",
    "pytest.cmds.gecurve.linetest": "",
    "pytest.cmds.jig.testblockjig": "",
    "pytest.cmds.jig.testcirjig": "",
    "pytest.cmds.linq.linqtest": "flags=acrx.CommandFlags.UsePickSet",
    "pytest.cmds.linq.linqtest2": "",
    "pytest.cmds.runtime.cstest": "",
    "pytest.cmds.runtime.switchtotest": "lock=False",
    "pytest.cmds.runtime.cmdtest": "",
    "pytest.cmds.runtime.dbxtest": "",
    "pytest.cmds.selection.myss1": "",
    "pytest.cmds.selection.myss2": "",
    "pytest.cmds.selection.comtest": "flags=acrx.CommandFlags.UsePickSet",
    "pytest.cmds.sort.pysort": "",
    "pytest.cmds.sort.linqsort": "",
    "pytest.cmds.symboltable.dicttest": "",
    "pytest.cmds.symboltable.dicttest2": "",
    "pytest.cmds.symboltable.dicttest3": "",
    "pytest.cmds.symboltable.layertest": "",
    "pytest.cmds.xdata.myxdata": "",
    "pytest.cmds.xdata.myxdata2": "",
    "pytest.cmds.xdata.deserializetest": "",
}
panels = {
    "pytest.panels.showpanel": "'testpanel'",
}
lisps = {
    "pytest.lisps.mylisp": "",
    "pytest.lisps.mylisp0": "",
    "pytest.lisps.mylisp1": "",
    "pytest.lisps.mylisp2": "",
    "pytest.lisps.mylisp3": "",
    "pytest.lisps.mylisp4": "",
    "pytest.lisps.clipboard": "",
}
