from __clrclasses__.Autodesk.AutoCAD.DatabaseServices import RenderGlobal as _n_0_t_0
from __clrclasses__.Autodesk.AutoCAD.DatabaseServices import MentalRayRenderSettings as _n_0_t_1
from __clrclasses__.System import IntPtr as _n_1_t_0
from __clrclasses__.System.Collections.Generic import List as _n_2_t_0
from __clrclasses__.System.Collections.ObjectModel import ObservableCollection as _n_3_t_0
from __clrclasses__.System.Collections.Specialized import StringCollection as _n_4_t_0
import typing
class RenderUtil(object):
    def __init__(self) -> RenderUtil:...
    @staticmethod
    def DoModalRenderSaveFileDlg(pStrPath: str, filterExtName: _n_4_t_0, caption: str, invalidFileName: str) -> bool:...
    @staticmethod
    def GetActiveRenderSettings(activeSettings: object):...
    @staticmethod
    def GetCurrentRenderOutputSize() -> str:...
    @staticmethod
    def GetCurrentRenderStyleName() -> str:...
    @staticmethod
    def GetCurrentRenderStyleName(itemName: str) -> str:...
    @staticmethod
    def GetCurrentRenderStyleName(dbObject: _n_1_t_0) -> str:...
    @staticmethod
    def GetCustomOutputSize(customList: _n_3_t_0[str]):...
    @staticmethod
    def GetCustomSettings(styleName: str, settings: object) -> bool:...
    @staticmethod
    def GetPredefinedSettings(styleName: str, settings: object) -> bool:...
    @staticmethod
    def GetRenderGlobal() -> _n_0_t_0:...
    @staticmethod
    def GetRenderStylesNames(renderStyleList: _n_2_t_0[str]):...
    @staticmethod
    def IsActiveRenderStyle(itemName: str) -> bool:...
    @staticmethod
    def IsCustomRenderStyle(styleName: str) -> bool:...
    @staticmethod
    def PopupPresetDlg() -> int:...
    @staticmethod
    def SetActiveSettings(activeSettings: _n_0_t_1) -> bool:...
    @staticmethod
    def SetCustomOutputSize(customSize: str):...
    @staticmethod
    def SetImageSize(cx: int, cy: int):...
    @staticmethod
    def SetRenderGlobal(_global: _n_0_t_0):...
    @staticmethod
    def SpecialImageSize(cx: int, cy: int) -> bool:...
    @staticmethod
    def UpdatePresetStyle():...
