import __clrclasses__.System.Text.RegularExpressions as RegularExpressions
from __clrclasses__.System import ICloneable as _n_0_t_0
from __clrclasses__.System import Byte as _n_0_t_1
from __clrclasses__.System import Array as _n_0_t_2
from __clrclasses__.System import Char as _n_0_t_3
from __clrclasses__.System import ArgumentException as _n_0_t_4
from __clrclasses__.System import Exception as _n_0_t_5
from __clrclasses__.System import Enum as _n_0_t_6
from __clrclasses__.System import IComparable as _n_0_t_7
from __clrclasses__.System import IFormattable as _n_0_t_8
from __clrclasses__.System import IConvertible as _n_0_t_9
from __clrclasses__.System import SByte as _n_0_t_10
from __clrclasses__.System import Decimal as _n_0_t_11
from __clrclasses__.System import UInt16 as _n_0_t_12
from __clrclasses__.System import UInt32 as _n_0_t_13
from __clrclasses__.System import UInt64 as _n_0_t_14
from __clrclasses__.System import IFormatProvider as _n_0_t_15
from __clrclasses__.System.Runtime.InteropServices import _Exception as _n_1_t_0
from __clrclasses__.System.Runtime.Serialization import ISerializable as _n_2_t_0
import typing
class ASCIIEncoding(Encoding, _n_0_t_0):
    def __init__(self) -> ASCIIEncoding:...
class Decoder(object):
    @property
    def Fallback(self) -> DecoderFallback:"""Fallback { get; set; } -> DecoderFallback"""
    @property
    def FallbackBuffer(self) -> DecoderFallbackBuffer:"""FallbackBuffer { get; } -> DecoderFallbackBuffer"""
    def Convert(self, bytes: _n_0_t_2[_n_0_t_1], byteIndex: int, byteCount: int, chars: _n_0_t_2[_n_0_t_3], charIndex: int, charCount: int, flush: bool, bytesUsed: int, charsUsed: int, completed: bool):...
    def Convert(self, bytes: _n_0_t_1, byteCount: int, chars: _n_0_t_3, charCount: int, flush: bool, bytesUsed: int, charsUsed: int, completed: bool):...
    def GetCharCount(self, bytes: _n_0_t_2[_n_0_t_1], index: int, count: int) -> int:...
    def GetCharCount(self, bytes: _n_0_t_2[_n_0_t_1], index: int, count: int, flush: bool) -> int:...
    def GetCharCount(self, bytes: _n_0_t_1, count: int, flush: bool) -> int:...
    def GetChars(self, bytes: _n_0_t_2[_n_0_t_1], byteIndex: int, byteCount: int, chars: _n_0_t_2[_n_0_t_3], charIndex: int) -> int:...
    def GetChars(self, bytes: _n_0_t_2[_n_0_t_1], byteIndex: int, byteCount: int, chars: _n_0_t_2[_n_0_t_3], charIndex: int, flush: bool) -> int:...
    def GetChars(self, bytes: _n_0_t_1, byteCount: int, chars: _n_0_t_3, charCount: int, flush: bool) -> int:...
    def Reset(self):...
class DecoderExceptionFallback(DecoderFallback):
    def __init__(self) -> DecoderExceptionFallback:...
class DecoderExceptionFallbackBuffer(DecoderFallbackBuffer):
    def __init__(self) -> DecoderExceptionFallbackBuffer:...
class DecoderFallback(object):
    @property
    def ExceptionFallback(self) -> DecoderFallback:"""ExceptionFallback { get; } -> DecoderFallback"""
    @property
    def MaxCharCount(self) -> int:"""MaxCharCount { get; } -> int"""
    @property
    def ReplacementFallback(self) -> DecoderFallback:"""ReplacementFallback { get; } -> DecoderFallback"""
    def CreateFallbackBuffer(self) -> DecoderFallbackBuffer:...
class DecoderFallbackBuffer(object):
    @property
    def Remaining(self) -> int:"""Remaining { get; } -> int"""
    def Fallback(self, bytesUnknown: _n_0_t_2[_n_0_t_1], index: int) -> bool:...
    def GetNextChar(self) -> _n_0_t_3:...
    def MovePrevious(self) -> bool:...
    def Reset(self):...
class DecoderFallbackException(_n_0_t_4, _n_2_t_0, _n_1_t_0):
    @property
    def BytesUnknown(self) -> _n_0_t_2[_n_0_t_1]:"""BytesUnknown { get; } -> Array"""
    @property
    def Index(self) -> int:"""Index { get; } -> int"""
    def __init__(self) -> DecoderFallbackException:...
    def __init__(self, message: str) -> DecoderFallbackException:...
    def __init__(self, message: str, innerException: _n_0_t_5) -> DecoderFallbackException:...
    def __init__(self, message: str, bytesUnknown: _n_0_t_2[_n_0_t_1], index: int) -> DecoderFallbackException:...
class DecoderReplacementFallback(DecoderFallback):
    @property
    def DefaultString(self) -> str:"""DefaultString { get; } -> str"""
    def __init__(self) -> DecoderReplacementFallback:...
    def __init__(self, replacement: str) -> DecoderReplacementFallback:...
class DecoderReplacementFallbackBuffer(DecoderFallbackBuffer):
    def __init__(self, fallback: DecoderReplacementFallback) -> DecoderReplacementFallbackBuffer:...
class Encoder(object):
    @property
    def Fallback(self) -> EncoderFallback:"""Fallback { get; set; } -> EncoderFallback"""
    @property
    def FallbackBuffer(self) -> EncoderFallbackBuffer:"""FallbackBuffer { get; } -> EncoderFallbackBuffer"""
    def Convert(self, chars: _n_0_t_2[_n_0_t_3], charIndex: int, charCount: int, bytes: _n_0_t_2[_n_0_t_1], byteIndex: int, byteCount: int, flush: bool, charsUsed: int, bytesUsed: int, completed: bool):...
    def Convert(self, chars: _n_0_t_3, charCount: int, bytes: _n_0_t_1, byteCount: int, flush: bool, charsUsed: int, bytesUsed: int, completed: bool):...
    def GetByteCount(self, chars: _n_0_t_2[_n_0_t_3], index: int, count: int, flush: bool) -> int:...
    def GetByteCount(self, chars: _n_0_t_3, count: int, flush: bool) -> int:...
    def GetBytes(self, chars: _n_0_t_2[_n_0_t_3], charIndex: int, charCount: int, bytes: _n_0_t_2[_n_0_t_1], byteIndex: int, flush: bool) -> int:...
    def GetBytes(self, chars: _n_0_t_3, charCount: int, bytes: _n_0_t_1, byteCount: int, flush: bool) -> int:...
    def Reset(self):...
class EncoderExceptionFallback(EncoderFallback):
    def __init__(self) -> EncoderExceptionFallback:...
class EncoderExceptionFallbackBuffer(EncoderFallbackBuffer):
    def __init__(self) -> EncoderExceptionFallbackBuffer:...
class EncoderFallback(object):
    @property
    def ExceptionFallback(self) -> EncoderFallback:"""ExceptionFallback { get; } -> EncoderFallback"""
    @property
    def MaxCharCount(self) -> int:"""MaxCharCount { get; } -> int"""
    @property
    def ReplacementFallback(self) -> EncoderFallback:"""ReplacementFallback { get; } -> EncoderFallback"""
    def CreateFallbackBuffer(self) -> EncoderFallbackBuffer:...
class EncoderFallbackBuffer(object):
    @property
    def Remaining(self) -> int:"""Remaining { get; } -> int"""
    def Fallback(self, charUnknown: _n_0_t_3, index: int) -> bool:...
    def Fallback(self, charUnknownHigh: _n_0_t_3, charUnknownLow: _n_0_t_3, index: int) -> bool:...
    def GetNextChar(self) -> _n_0_t_3:...
    def MovePrevious(self) -> bool:...
    def Reset(self):...
class EncoderFallbackException(_n_0_t_4, _n_2_t_0, _n_1_t_0):
    @property
    def CharUnknown(self) -> _n_0_t_3:"""CharUnknown { get; } -> Char"""
    @property
    def CharUnknownHigh(self) -> _n_0_t_3:"""CharUnknownHigh { get; } -> Char"""
    @property
    def CharUnknownLow(self) -> _n_0_t_3:"""CharUnknownLow { get; } -> Char"""
    @property
    def Index(self) -> int:"""Index { get; } -> int"""
    def __init__(self) -> EncoderFallbackException:...
    def __init__(self, message: str) -> EncoderFallbackException:...
    def __init__(self, message: str, innerException: _n_0_t_5) -> EncoderFallbackException:...
    def IsUnknownSurrogate(self) -> bool:...
class EncoderReplacementFallback(EncoderFallback):
    @property
    def DefaultString(self) -> str:"""DefaultString { get; } -> str"""
    def __init__(self) -> EncoderReplacementFallback:...
    def __init__(self, replacement: str) -> EncoderReplacementFallback:...
class EncoderReplacementFallbackBuffer(EncoderFallbackBuffer):
    def __init__(self, fallback: EncoderReplacementFallback) -> EncoderReplacementFallbackBuffer:...
class Encoding(_n_0_t_0):
    @property
    def ASCII(self) -> Encoding:"""ASCII { get; } -> Encoding"""
    @property
    def BigEndianUnicode(self) -> Encoding:"""BigEndianUnicode { get; } -> Encoding"""
    @property
    def BodyName(self) -> str:"""BodyName { get; } -> str"""
    @property
    def CodePage(self) -> int:"""CodePage { get; } -> int"""
    @property
    def DecoderFallback(self) -> DecoderFallback:"""DecoderFallback { get; set; } -> DecoderFallback"""
    @property
    def Default(self) -> Encoding:"""Default { get; } -> Encoding"""
    @property
    def EncoderFallback(self) -> EncoderFallback:"""EncoderFallback { get; set; } -> EncoderFallback"""
    @property
    def EncodingName(self) -> str:"""EncodingName { get; } -> str"""
    @property
    def HeaderName(self) -> str:"""HeaderName { get; } -> str"""
    @property
    def IsBrowserDisplay(self) -> bool:"""IsBrowserDisplay { get; } -> bool"""
    @property
    def IsBrowserSave(self) -> bool:"""IsBrowserSave { get; } -> bool"""
    @property
    def IsMailNewsDisplay(self) -> bool:"""IsMailNewsDisplay { get; } -> bool"""
    @property
    def IsMailNewsSave(self) -> bool:"""IsMailNewsSave { get; } -> bool"""
    @property
    def IsReadOnly(self) -> bool:"""IsReadOnly { get; } -> bool"""
    @property
    def IsSingleByte(self) -> bool:"""IsSingleByte { get; } -> bool"""
    @property
    def Unicode(self) -> Encoding:"""Unicode { get; } -> Encoding"""
    @property
    def UTF32(self) -> Encoding:"""UTF32 { get; } -> Encoding"""
    @property
    def UTF7(self) -> Encoding:"""UTF7 { get; } -> Encoding"""
    @property
    def UTF8(self) -> Encoding:"""UTF8 { get; } -> Encoding"""
    @property
    def WebName(self) -> str:"""WebName { get; } -> str"""
    @property
    def WindowsCodePage(self) -> int:"""WindowsCodePage { get; } -> int"""
    @staticmethod
    def Convert(srcEncoding: Encoding, dstEncoding: Encoding, bytes: _n_0_t_2[_n_0_t_1]) -> _n_0_t_2[_n_0_t_1]:...
    @staticmethod
    def Convert(srcEncoding: Encoding, dstEncoding: Encoding, bytes: _n_0_t_2[_n_0_t_1], index: int, count: int) -> _n_0_t_2[_n_0_t_1]:...
    def GetByteCount(self, chars: _n_0_t_2[_n_0_t_3]) -> int:...
    def GetByteCount(self, s: str) -> int:...
    def GetByteCount(self, chars: _n_0_t_2[_n_0_t_3], index: int, count: int) -> int:...
    def GetByteCount(self, chars: _n_0_t_3, count: int) -> int:...
    def GetBytes(self, chars: _n_0_t_2[_n_0_t_3]) -> _n_0_t_2[_n_0_t_1]:...
    def GetBytes(self, chars: _n_0_t_2[_n_0_t_3], index: int, count: int) -> _n_0_t_2[_n_0_t_1]:...
    def GetBytes(self, chars: _n_0_t_2[_n_0_t_3], charIndex: int, charCount: int, bytes: _n_0_t_2[_n_0_t_1], byteIndex: int) -> int:...
    def GetBytes(self, s: str) -> _n_0_t_2[_n_0_t_1]:...
    def GetBytes(self, s: str, charIndex: int, charCount: int, bytes: _n_0_t_2[_n_0_t_1], byteIndex: int) -> int:...
    def GetBytes(self, chars: _n_0_t_3, charCount: int, bytes: _n_0_t_1, byteCount: int) -> int:...
    def GetCharCount(self, bytes: _n_0_t_2[_n_0_t_1]) -> int:...
    def GetCharCount(self, bytes: _n_0_t_2[_n_0_t_1], index: int, count: int) -> int:...
    def GetCharCount(self, bytes: _n_0_t_1, count: int) -> int:...
    def GetChars(self, bytes: _n_0_t_2[_n_0_t_1]) -> _n_0_t_2[_n_0_t_3]:...
    def GetChars(self, bytes: _n_0_t_2[_n_0_t_1], index: int, count: int) -> _n_0_t_2[_n_0_t_3]:...
    def GetChars(self, bytes: _n_0_t_2[_n_0_t_1], byteIndex: int, byteCount: int, chars: _n_0_t_2[_n_0_t_3], charIndex: int) -> int:...
    def GetChars(self, bytes: _n_0_t_1, byteCount: int, chars: _n_0_t_3, charCount: int) -> int:...
    def GetDecoder(self) -> Decoder:...
    def GetEncoder(self) -> Encoder:...
    @staticmethod
    def GetEncoding(codepage: int) -> Encoding:...
    @staticmethod
    def GetEncoding(codepage: int, encoderFallback: EncoderFallback, decoderFallback: DecoderFallback) -> Encoding:...
    @staticmethod
    def GetEncoding(name: str) -> Encoding:...
    @staticmethod
    def GetEncoding(name: str, encoderFallback: EncoderFallback, decoderFallback: DecoderFallback) -> Encoding:...
    @staticmethod
    def GetEncodings() -> _n_0_t_2[EncodingInfo]:...
    def GetMaxByteCount(self, charCount: int) -> int:...
    def GetMaxCharCount(self, byteCount: int) -> int:...
    def GetPreamble(self) -> _n_0_t_2[_n_0_t_1]:...
    def GetString(self, bytes: _n_0_t_1, byteCount: int) -> str:...
    def GetString(self, bytes: _n_0_t_2[_n_0_t_1]) -> str:...
    def GetString(self, bytes: _n_0_t_2[_n_0_t_1], index: int, count: int) -> str:...
    def IsAlwaysNormalized(self) -> bool:...
    def IsAlwaysNormalized(self, form: NormalizationForm) -> bool:...
    @staticmethod
    def RegisterProvider(provider: EncodingProvider):...
class EncodingInfo(object):
    @property
    def CodePage(self) -> int:"""CodePage { get; } -> int"""
    @property
    def DisplayName(self) -> str:"""DisplayName { get; } -> str"""
    @property
    def Name(self) -> str:"""Name { get; } -> str"""
    def GetEncoding(self) -> Encoding:...
class EncodingProvider(object):
    def __init__(self) -> EncodingProvider:...
    def GetEncoding(self, name: str) -> Encoding:...
    def GetEncoding(self, codepage: int) -> Encoding:...
    def GetEncoding(self, name: str, encoderFallback: EncoderFallback, decoderFallback: DecoderFallback) -> Encoding:...
    def GetEncoding(self, codepage: int, encoderFallback: EncoderFallback, decoderFallback: DecoderFallback) -> Encoding:...
class NormalizationForm(_n_0_t_6, _n_0_t_7, _n_0_t_8, _n_0_t_9):
    FormC: int
    FormD: int
    FormKC: int
    FormKD: int
    value__: int
class StringBuilder(_n_2_t_0):
    @property
    def Capacity(self) -> int:"""Capacity { get; set; } -> int"""
    @property
    def Chars(self) -> _n_0_t_3:"""Chars { get; set; } -> Char"""
    @property
    def Length(self) -> int:"""Length { get; set; } -> int"""
    @property
    def MaxCapacity(self) -> int:"""MaxCapacity { get; } -> int"""
    def __init__(self) -> StringBuilder:...
    def __init__(self, capacity: int) -> StringBuilder:...
    def __init__(self, value: str) -> StringBuilder:...
    def __init__(self, value: str, capacity: int) -> StringBuilder:...
    def __init__(self, value: str, startIndex: int, length: int, capacity: int) -> StringBuilder:...
    def __init__(self, capacity: int, maxCapacity: int) -> StringBuilder:...
    def Append(self, value: _n_0_t_3, repeatCount: int) -> StringBuilder:...
    def Append(self, value: _n_0_t_2[_n_0_t_3], startIndex: int, charCount: int) -> StringBuilder:...
    def Append(self, value: str) -> StringBuilder:...
    def Append(self, value: str, startIndex: int, count: int) -> StringBuilder:...
    def Append(self, value: bool) -> StringBuilder:...
    def Append(self, value: _n_0_t_10) -> StringBuilder:...
    def Append(self, value: _n_0_t_1) -> StringBuilder:...
    def Append(self, value: _n_0_t_3) -> StringBuilder:...
    def Append(self, value: int) -> StringBuilder:...
    def Append(self, value: float) -> StringBuilder:...
    def Append(self, value: _n_0_t_11) -> StringBuilder:...
    def Append(self, value: _n_0_t_12) -> StringBuilder:...
    def Append(self, value: _n_0_t_13) -> StringBuilder:...
    def Append(self, value: _n_0_t_14) -> StringBuilder:...
    def Append(self, value: object) -> StringBuilder:...
    def Append(self, value: _n_0_t_2[_n_0_t_3]) -> StringBuilder:...
    def AppendFormat(self, format: str, arg0: object) -> StringBuilder:...
    def AppendFormat(self, format: str, arg0: object, arg1: object) -> StringBuilder:...
    def AppendFormat(self, format: str, arg0: object, arg1: object, arg2: object) -> StringBuilder:...
    def AppendFormat(self, format: str, args: _n_0_t_2[object]) -> StringBuilder:...
    def AppendFormat(self, provider: _n_0_t_15, format: str, arg0: object) -> StringBuilder:...
    def AppendFormat(self, provider: _n_0_t_15, format: str, arg0: object, arg1: object) -> StringBuilder:...
    def AppendFormat(self, provider: _n_0_t_15, format: str, arg0: object, arg1: object, arg2: object) -> StringBuilder:...
    def AppendFormat(self, provider: _n_0_t_15, format: str, args: _n_0_t_2[object]) -> StringBuilder:...
    def AppendLine(self) -> StringBuilder:...
    def AppendLine(self, value: str) -> StringBuilder:...
    def Clear(self) -> StringBuilder:...
    def CopyTo(self, sourceIndex: int, destination: _n_0_t_2[_n_0_t_3], destinationIndex: int, count: int):...
    def EnsureCapacity(self, capacity: int) -> int:...
    def Insert(self, index: int, value: str, count: int) -> StringBuilder:...
    def Insert(self, index: int, value: str) -> StringBuilder:...
    def Insert(self, index: int, value: bool) -> StringBuilder:...
    def Insert(self, index: int, value: _n_0_t_10) -> StringBuilder:...
    def Insert(self, index: int, value: _n_0_t_1) -> StringBuilder:...
    def Insert(self, index: int, value: int) -> StringBuilder:...
    def Insert(self, index: int, value: _n_0_t_3) -> StringBuilder:...
    def Insert(self, index: int, value: _n_0_t_2[_n_0_t_3]) -> StringBuilder:...
    def Insert(self, index: int, value: _n_0_t_2[_n_0_t_3], startIndex: int, charCount: int) -> StringBuilder:...
    def Insert(self, index: int, value: float) -> StringBuilder:...
    def Insert(self, index: int, value: _n_0_t_11) -> StringBuilder:...
    def Insert(self, index: int, value: _n_0_t_12) -> StringBuilder:...
    def Insert(self, index: int, value: _n_0_t_13) -> StringBuilder:...
    def Insert(self, index: int, value: _n_0_t_14) -> StringBuilder:...
    def Insert(self, index: int, value: object) -> StringBuilder:...
    def Remove(self, startIndex: int, length: int) -> StringBuilder:...
    def Replace(self, oldValue: str, newValue: str) -> StringBuilder:...
    def Replace(self, oldValue: str, newValue: str, startIndex: int, count: int) -> StringBuilder:...
    def Replace(self, oldChar: _n_0_t_3, newChar: _n_0_t_3) -> StringBuilder:...
    def Replace(self, oldChar: _n_0_t_3, newChar: _n_0_t_3, startIndex: int, count: int) -> StringBuilder:...
class UnicodeEncoding(Encoding, _n_0_t_0):
    CharSize: int
    def __init__(self) -> UnicodeEncoding:...
    def __init__(self, bigEndian: bool, byteOrderMark: bool) -> UnicodeEncoding:...
    def __init__(self, bigEndian: bool, byteOrderMark: bool, throwOnInvalidBytes: bool) -> UnicodeEncoding:...
class UTF32Encoding(Encoding, _n_0_t_0):
    def __init__(self) -> UTF32Encoding:...
    def __init__(self, bigEndian: bool, byteOrderMark: bool) -> UTF32Encoding:...
    def __init__(self, bigEndian: bool, byteOrderMark: bool, throwOnInvalidCharacters: bool) -> UTF32Encoding:...
class UTF7Encoding(Encoding, _n_0_t_0):
    def __init__(self) -> UTF7Encoding:...
    def __init__(self, allowOptionals: bool) -> UTF7Encoding:...
class UTF8Encoding(Encoding, _n_0_t_0):
    def __init__(self) -> UTF8Encoding:...
    def __init__(self, encoderShouldEmitUTF8Identifier: bool) -> UTF8Encoding:...
    def __init__(self, encoderShouldEmitUTF8Identifier: bool, throwOnInvalidBytes: bool) -> UTF8Encoding:...
