from __clrclasses__.System import IAsyncResult as _n_0_t_0
from __clrclasses__.System import Array as _n_0_t_1
from __clrclasses__.System import MulticastDelegate as _n_0_t_2
from __clrclasses__.System import ICloneable as _n_0_t_3
from __clrclasses__.System import IntPtr as _n_0_t_4
from __clrclasses__.System import AsyncCallback as _n_0_t_5
from __clrclasses__.System import Exception as _n_0_t_6
from __clrclasses__.System import Attribute as _n_0_t_7
from __clrclasses__.System.Collections import IDictionary as _n_1_t_0
from __clrclasses__.System.Reflection import MethodBase as _n_2_t_0
from __clrclasses__.System.Runtime.InteropServices import _Attribute as _n_3_t_0
from __clrclasses__.System.Runtime.Remoting.Activation import IConstructionCallMessage as _n_4_t_0
from __clrclasses__.System.Runtime.Remoting.Activation import IConstructionReturnMessage as _n_4_t_1
from __clrclasses__.System.Runtime.Serialization import ISerializable as _n_5_t_0
from __clrclasses__.System.Runtime.Serialization import IFormatter as _n_5_t_1
from __clrclasses__.System.Runtime.Serialization import ISurrogateSelector as _n_5_t_2
import typing
class AsyncResult(_n_0_t_0, IMessageSink):
    @property
    def AsyncDelegate(self) -> object:"""AsyncDelegate { get; } -> object"""
    @property
    def EndInvokeCalled(self) -> bool:"""EndInvokeCalled { get; set; } -> bool"""
    def GetReplyMessage(self) -> IMessage:...
    def SetMessageCtrl(self, mc: IMessageCtrl):...
class CallContext(object):
    @property
    def HostContext(self) -> object:"""HostContext { get; set; } -> object"""
    @staticmethod
    def FreeNamedDataSlot(name: str):...
    @staticmethod
    def GetData(name: str) -> object:...
    @staticmethod
    def GetHeaders() -> _n_0_t_1[Header]:...
    @staticmethod
    def LogicalGetData(name: str) -> object:...
    @staticmethod
    def LogicalSetData(name: str, data: object):...
    @staticmethod
    def SetData(name: str, data: object):...
    @staticmethod
    def SetHeaders(headers: _n_0_t_1[Header]):...
class ConstructionCall(MethodCall, IMethodCallMessage, _n_5_t_0, IInternalMessage, ISerializationRootObject, _n_4_t_0):
    def __init__(self, m: IMessage) -> ConstructionCall:...
    def __init__(self, headers: _n_0_t_1[Header]) -> ConstructionCall:...
class ConstructionResponse(MethodResponse, IMethodReturnMessage, _n_5_t_0, ISerializationRootObject, IInternalMessage, _n_4_t_1):
    def __init__(self, h: _n_0_t_1[Header], mcm: IMethodCallMessage) -> ConstructionResponse:...
class Header(object):
    HeaderNamespace: int
    MustUnderstand: int
    Name: int
    Value: int
    def __init__(self, _Name: str, _Value: object, _MustUnderstand: bool, _HeaderNamespace: str) -> Header:...
    def __init__(self, _Name: str, _Value: object, _MustUnderstand: bool) -> Header:...
    def __init__(self, _Name: str, _Value: object) -> Header:...
class HeaderHandler(_n_0_t_2, _n_0_t_3, _n_5_t_0):
    def __init__(self, object: object, method: _n_0_t_4) -> HeaderHandler:...
    def BeginInvoke(self, headers: _n_0_t_1[Header], callback: _n_0_t_5, object: object) -> _n_0_t_0:...
    def EndInvoke(self, result: _n_0_t_0) -> object:...
    def Invoke(self, headers: _n_0_t_1[Header]) -> object:...
class ILogicalThreadAffinative():
    pass
class IMessage():
    @property
    def Properties(self) -> _n_1_t_0:"""Properties { get; } -> IDictionary"""
class IMessageCtrl():
    def Cancel(self, msToCancel: int):...
class IMessageSink():
    @property
    def NextSink(self) -> IMessageSink:"""NextSink { get; } -> IMessageSink"""
    def AsyncProcessMessage(self, msg: IMessage, replySink: IMessageSink) -> IMessageCtrl:...
    def SyncProcessMessage(self, msg: IMessage) -> IMessage:...
class IMethodCallMessage(IMethodMessage):
    @property
    def InArgCount(self) -> int:"""InArgCount { get; } -> int"""
    @property
    def InArgs(self) -> _n_0_t_1[object]:"""InArgs { get; } -> Array"""
    def GetInArg(self, argNum: int) -> object:...
    def GetInArgName(self, index: int) -> str:...
class IMethodMessage(IMessage):
    @property
    def ArgCount(self) -> int:"""ArgCount { get; } -> int"""
    @property
    def Args(self) -> _n_0_t_1[object]:"""Args { get; } -> Array"""
    @property
    def HasVarArgs(self) -> bool:"""HasVarArgs { get; } -> bool"""
    @property
    def LogicalCallContext(self) -> LogicalCallContext:"""LogicalCallContext { get; } -> LogicalCallContext"""
    @property
    def MethodBase(self) -> _n_2_t_0:"""MethodBase { get; } -> MethodBase"""
    @property
    def MethodName(self) -> str:"""MethodName { get; } -> str"""
    @property
    def MethodSignature(self) -> object:"""MethodSignature { get; } -> object"""
    @property
    def TypeName(self) -> str:"""TypeName { get; } -> str"""
    @property
    def Uri(self) -> str:"""Uri { get; } -> str"""
    def GetArg(self, argNum: int) -> object:...
    def GetArgName(self, index: int) -> str:...
class IMethodReturnMessage(IMethodMessage):
    @property
    def Exception(self) -> _n_0_t_6:"""Exception { get; } -> Exception"""
    @property
    def OutArgCount(self) -> int:"""OutArgCount { get; } -> int"""
    @property
    def OutArgs(self) -> _n_0_t_1[object]:"""OutArgs { get; } -> Array"""
    @property
    def ReturnValue(self) -> object:"""ReturnValue { get; } -> object"""
    def GetOutArg(self, argNum: int) -> object:...
    def GetOutArgName(self, index: int) -> str:...
class InternalMessageWrapper(object):
    def __init__(self, msg: IMessage) -> InternalMessageWrapper:...
class IRemotingFormatter(_n_5_t_1):
    pass
class LogicalCallContext(_n_5_t_0, _n_0_t_3):
    @property
    def HasInfo(self) -> bool:"""HasInfo { get; } -> bool"""
    def FreeNamedDataSlot(self, name: str):...
    def GetData(self, name: str) -> object:...
    def SetData(self, name: str, data: object):...
class MessageSurrogateFilter(_n_0_t_2, _n_0_t_3, _n_5_t_0):
    def __init__(self, object: object, method: _n_0_t_4) -> MessageSurrogateFilter:...
    def BeginInvoke(self, key: str, value: object, callback: _n_0_t_5, object: object) -> _n_0_t_0:...
    def EndInvoke(self, result: _n_0_t_0) -> bool:...
    def Invoke(self, key: str, value: object) -> bool:...
class MethodCall(IMethodCallMessage, _n_5_t_0, IInternalMessage, ISerializationRootObject):
    def __init__(self, msg: IMessage) -> MethodCall:...
    def __init__(self, h1: _n_0_t_1[Header]) -> MethodCall:...
    def HeaderHandler(self, h: _n_0_t_1[Header]) -> object:...
    def Init(self):...
    def ResolveMethod(self):...
class MethodCallMessageWrapper(InternalMessageWrapper, IMethodCallMessage):
    def __init__(self, msg: IMethodCallMessage) -> MethodCallMessageWrapper:...
class MethodResponse(IMethodReturnMessage, _n_5_t_0, ISerializationRootObject, IInternalMessage):
    def __init__(self, h1: _n_0_t_1[Header], mcm: IMethodCallMessage) -> MethodResponse:...
    def HeaderHandler(self, h: _n_0_t_1[Header]) -> object:...
class MethodReturnMessageWrapper(InternalMessageWrapper, IMethodReturnMessage):
    def __init__(self, msg: IMethodReturnMessage) -> MethodReturnMessageWrapper:...
class OneWayAttribute(_n_0_t_7, _n_3_t_0):
    def __init__(self) -> OneWayAttribute:...
class RemotingSurrogateSelector(_n_5_t_2):
    @property
    def Filter(self) -> MessageSurrogateFilter:"""Filter { get; set; } -> MessageSurrogateFilter"""
    def __init__(self) -> RemotingSurrogateSelector:...
    def GetRootObject(self) -> object:...
    def SetRootObject(self, obj: object):...
    def UseSoapFormat(self):...
class ReturnMessage(IMethodReturnMessage):
    def __init__(self, e: _n_0_t_6, mcm: IMethodCallMessage) -> ReturnMessage:...
    def __init__(self, ret: object, outArgs: _n_0_t_1[object], outArgsCount: int, callCtx: LogicalCallContext, mcm: IMethodCallMessage) -> ReturnMessage:...
