import __clrclasses__.System.Runtime.Remoting.Metadata as Metadata
import __clrclasses__.System.Runtime.Remoting.Proxies as Proxies
import __clrclasses__.System.Runtime.Remoting.Services as Services
import __clrclasses__.System.Runtime.Remoting.Contexts as Contexts
import __clrclasses__.System.Runtime.Remoting.Lifetime as Lifetime
import __clrclasses__.System.Runtime.Remoting.Channels as Channels
import __clrclasses__.System.Runtime.Remoting.Messaging as Messaging
import __clrclasses__.System.Runtime.Remoting.Activation as Activation
from __clrclasses__.System import Array as _n_0_t_0
from __clrclasses__.System import Type as _n_0_t_1
from __clrclasses__.System import Enum as _n_0_t_2
from __clrclasses__.System import IComparable as _n_0_t_3
from __clrclasses__.System import IFormattable as _n_0_t_4
from __clrclasses__.System import IConvertible as _n_0_t_5
from __clrclasses__.System import MarshalByRefObject as _n_0_t_6
from __clrclasses__.System import SystemException as _n_0_t_7
from __clrclasses__.System import Exception as _n_0_t_8
from __clrclasses__.System.Reflection import MethodBase as _n_1_t_0
from __clrclasses__.System.Reflection import Assembly as _n_1_t_1
from __clrclasses__.System.Runtime.InteropServices import _Exception as _n_2_t_0
from __clrclasses__.System.Runtime.Remoting.Contexts import IContextAttribute as _n_3_t_0
from __clrclasses__.System.Runtime.Remoting.Messaging import IMessageSink as _n_4_t_0
from __clrclasses__.System.Runtime.Remoting.Messaging import MethodCall as _n_4_t_1
from __clrclasses__.System.Runtime.Remoting.Messaging import IMethodReturnMessage as _n_4_t_2
from __clrclasses__.System.Runtime.Remoting.Messaging import IMethodCallMessage as _n_4_t_3
from __clrclasses__.System.Runtime.Remoting.Messaging import IMethodMessage as _n_4_t_4
from __clrclasses__.System.Runtime.Remoting.Metadata import SoapAttribute as _n_5_t_0
from __clrclasses__.System.Runtime.Remoting.Proxies import RealProxy as _n_6_t_0
from __clrclasses__.System.Runtime.Serialization import IObjectReference as _n_7_t_0
from __clrclasses__.System.Runtime.Serialization import ISerializable as _n_7_t_1
from __clrclasses__.System.Runtime.Serialization import SerializationInfo as _n_7_t_2
from __clrclasses__.System.Runtime.Serialization import StreamingContext as _n_7_t_3
import typing
class ActivatedClientTypeEntry(TypeEntry):
    @property
    def ApplicationUrl(self) -> str:"""ApplicationUrl { get; } -> str"""
    @property
    def ContextAttributes(self) -> _n_0_t_0[_n_3_t_0]:"""ContextAttributes { get; set; } -> Array"""
    @property
    def ObjectType(self) -> _n_0_t_1:"""ObjectType { get; } -> Type"""
    def __init__(self, type: _n_0_t_1, appUrl: str) -> ActivatedClientTypeEntry:...
    def __init__(self, typeName: str, assemblyName: str, appUrl: str) -> ActivatedClientTypeEntry:...
class ActivatedServiceTypeEntry(TypeEntry):
    @property
    def ContextAttributes(self) -> _n_0_t_0[_n_3_t_0]:"""ContextAttributes { get; set; } -> Array"""
    @property
    def ObjectType(self) -> _n_0_t_1:"""ObjectType { get; } -> Type"""
    def __init__(self, type: _n_0_t_1) -> ActivatedServiceTypeEntry:...
    def __init__(self, typeName: str, assemblyName: str) -> ActivatedServiceTypeEntry:...
class CustomErrorsModes(_n_0_t_2, _n_0_t_3, _n_0_t_4, _n_0_t_5):
    Off: int
    On: int
    RemoteOnly: int
    value__: int
class IChannelInfo():
    @property
    def ChannelData(self) -> _n_0_t_0[object]:"""ChannelData { get; set; } -> Array"""
class IEnvoyInfo():
    @property
    def EnvoySinks(self) -> _n_4_t_0:"""EnvoySinks { get; set; } -> IMessageSink"""
class InternalRemotingServices(object):
    def __init__(self) -> InternalRemotingServices:...
    @staticmethod
    def DebugOutChnl(s: str):...
    @staticmethod
    def GetCachedSoapAttribute(reflectionObject: object) -> _n_5_t_0:...
    @staticmethod
    def RemotingAssert(condition: bool, message: str):...
    @staticmethod
    def RemotingTrace(messages: _n_0_t_0[object]):...
    @staticmethod
    def SetServerIdentity(m: _n_4_t_1, srvID: object):...
class IObjectHandle():
    def Unwrap(self) -> object:...
class IRemotingTypeInfo():
    @property
    def TypeName(self) -> str:"""TypeName { get; set; } -> str"""
    def CanCastTo(self, fromType: _n_0_t_1, o: object) -> bool:...
class ObjectHandle(_n_0_t_6, IObjectHandle):
    def __init__(self, o: object) -> ObjectHandle:...
class ObjRef(_n_7_t_0, _n_7_t_1):
    @property
    def ChannelInfo(self) -> IChannelInfo:"""ChannelInfo { get; set; } -> IChannelInfo"""
    @property
    def EnvoyInfo(self) -> IEnvoyInfo:"""EnvoyInfo { get; set; } -> IEnvoyInfo"""
    @property
    def TypeInfo(self) -> IRemotingTypeInfo:"""TypeInfo { get; set; } -> IRemotingTypeInfo"""
    @property
    def URI(self) -> str:"""URI { get; set; } -> str"""
    def __init__(self) -> ObjRef:...
    def __init__(self, o: _n_0_t_6, requestedType: _n_0_t_1) -> ObjRef:...
    def IsFromThisAppDomain(self) -> bool:...
    def IsFromThisProcess(self) -> bool:...
class RemotingConfiguration(object):
    @property
    def ApplicationId(self) -> str:"""ApplicationId { get; } -> str"""
    @property
    def ApplicationName(self) -> str:"""ApplicationName { get; set; } -> str"""
    @property
    def CustomErrorsMode(self) -> CustomErrorsModes:"""CustomErrorsMode { get; set; } -> CustomErrorsModes"""
    @property
    def ProcessId(self) -> str:"""ProcessId { get; } -> str"""
    @staticmethod
    def Configure(filename: str, ensureSecurity: bool):...
    @staticmethod
    def Configure(filename: str):...
    @staticmethod
    def CustomErrorsEnabled(isLocalRequest: bool) -> bool:...
    @staticmethod
    def GetRegisteredActivatedClientTypes() -> _n_0_t_0[ActivatedClientTypeEntry]:...
    @staticmethod
    def GetRegisteredActivatedServiceTypes() -> _n_0_t_0[ActivatedServiceTypeEntry]:...
    @staticmethod
    def GetRegisteredWellKnownClientTypes() -> _n_0_t_0[WellKnownClientTypeEntry]:...
    @staticmethod
    def GetRegisteredWellKnownServiceTypes() -> _n_0_t_0[WellKnownServiceTypeEntry]:...
    @staticmethod
    def IsActivationAllowed(svrType: _n_0_t_1) -> bool:...
    @staticmethod
    def IsRemotelyActivatedClientType(typeName: str, assemblyName: str) -> ActivatedClientTypeEntry:...
    @staticmethod
    def IsRemotelyActivatedClientType(svrType: _n_0_t_1) -> ActivatedClientTypeEntry:...
    @staticmethod
    def IsWellKnownClientType(typeName: str, assemblyName: str) -> WellKnownClientTypeEntry:...
    @staticmethod
    def IsWellKnownClientType(svrType: _n_0_t_1) -> WellKnownClientTypeEntry:...
    @staticmethod
    def RegisterActivatedClientType(entry: ActivatedClientTypeEntry):...
    @staticmethod
    def RegisterActivatedClientType(type: _n_0_t_1, appUrl: str):...
    @staticmethod
    def RegisterActivatedServiceType(entry: ActivatedServiceTypeEntry):...
    @staticmethod
    def RegisterActivatedServiceType(type: _n_0_t_1):...
    @staticmethod
    def RegisterWellKnownClientType(entry: WellKnownClientTypeEntry):...
    @staticmethod
    def RegisterWellKnownClientType(type: _n_0_t_1, objectUrl: str):...
    @staticmethod
    def RegisterWellKnownServiceType(entry: WellKnownServiceTypeEntry):...
    @staticmethod
    def RegisterWellKnownServiceType(type: _n_0_t_1, objectUri: str, mode: WellKnownObjectMode):...
class RemotingException(_n_0_t_7, _n_7_t_1, _n_2_t_0):
    def __init__(self, message: str, InnerException: _n_0_t_8) -> RemotingException:...
    def __init__(self, message: str) -> RemotingException:...
    def __init__(self) -> RemotingException:...
class RemotingServices(object):
    @staticmethod
    def Connect(classToProxy: _n_0_t_1, url: str, data: object) -> object:...
    @staticmethod
    def Connect(classToProxy: _n_0_t_1, url: str) -> object:...
    @staticmethod
    def Disconnect(obj: _n_0_t_6) -> bool:...
    @staticmethod
    def ExecuteMessage(target: _n_0_t_6, reqMsg: _n_4_t_3) -> _n_4_t_2:...
    @staticmethod
    def GetEnvoyChainForProxy(obj: _n_0_t_6) -> _n_4_t_0:...
    @staticmethod
    def GetLifetimeService(obj: _n_0_t_6) -> object:...
    @staticmethod
    def GetMethodBaseFromMethodMessage(msg: _n_4_t_4) -> _n_1_t_0:...
    @staticmethod
    def GetObjectData(obj: object, info: _n_7_t_2, context: _n_7_t_3):...
    @staticmethod
    def GetObjectUri(obj: _n_0_t_6) -> str:...
    @staticmethod
    def GetObjRefForProxy(obj: _n_0_t_6) -> ObjRef:...
    @staticmethod
    def GetRealProxy(proxy: object) -> _n_6_t_0:...
    @staticmethod
    def GetServerTypeForUri(URI: str) -> _n_0_t_1:...
    @staticmethod
    def GetSessionIdForMethodMessage(msg: _n_4_t_4) -> str:...
    @staticmethod
    def IsMethodOverloaded(msg: _n_4_t_4) -> bool:...
    @staticmethod
    def IsObjectOutOfAppDomain(tp: object) -> bool:...
    @staticmethod
    def IsObjectOutOfContext(tp: object) -> bool:...
    @staticmethod
    def IsOneWay(method: _n_1_t_0) -> bool:...
    @staticmethod
    def IsTransparentProxy(proxy: object) -> bool:...
    @staticmethod
    def LogRemotingStage(stage: int):...
    @staticmethod
    def Marshal(Obj: _n_0_t_6, ObjURI: str, RequestedType: _n_0_t_1) -> ObjRef:...
    @staticmethod
    def Marshal(Obj: _n_0_t_6, URI: str) -> ObjRef:...
    @staticmethod
    def Marshal(Obj: _n_0_t_6) -> ObjRef:...
    @staticmethod
    def SetObjectUriForMarshal(obj: _n_0_t_6, uri: str):...
    @staticmethod
    def Unmarshal(objectRef: ObjRef, fRefine: bool) -> object:...
    @staticmethod
    def Unmarshal(objectRef: ObjRef) -> object:...
class RemotingTimeoutException(RemotingException, _n_7_t_1, _n_2_t_0):
    def __init__(self, message: str, InnerException: _n_0_t_8) -> RemotingTimeoutException:...
    def __init__(self, message: str) -> RemotingTimeoutException:...
    def __init__(self) -> RemotingTimeoutException:...
class ServerException(_n_0_t_7, _n_7_t_1, _n_2_t_0):
    def __init__(self, message: str, InnerException: _n_0_t_8) -> ServerException:...
    def __init__(self, message: str) -> ServerException:...
    def __init__(self) -> ServerException:...
class SoapServices(object):
    @property
    def XmlNsForClrType(self) -> str:"""XmlNsForClrType { get; } -> str"""
    @property
    def XmlNsForClrTypeWithAssembly(self) -> str:"""XmlNsForClrTypeWithAssembly { get; } -> str"""
    @property
    def XmlNsForClrTypeWithNs(self) -> str:"""XmlNsForClrTypeWithNs { get; } -> str"""
    @property
    def XmlNsForClrTypeWithNsAndAssembly(self) -> str:"""XmlNsForClrTypeWithNsAndAssembly { get; } -> str"""
    @staticmethod
    def CodeXmlNamespaceForClrTypeNamespace(typeNamespace: str, assemblyName: str) -> str:...
    @staticmethod
    def DecodeXmlNamespaceForClrTypeNamespace(inNamespace: str, typeNamespace: str, assemblyName: str) -> bool:...
    @staticmethod
    def GetInteropFieldTypeAndNameFromXmlAttribute(containingType: _n_0_t_1, xmlAttribute: str, xmlNamespace: str, type: _n_0_t_1, name: str):...
    @staticmethod
    def GetInteropFieldTypeAndNameFromXmlElement(containingType: _n_0_t_1, xmlElement: str, xmlNamespace: str, type: _n_0_t_1, name: str):...
    @staticmethod
    def GetInteropTypeFromXmlElement(xmlElement: str, xmlNamespace: str) -> _n_0_t_1:...
    @staticmethod
    def GetInteropTypeFromXmlType(xmlType: str, xmlTypeNamespace: str) -> _n_0_t_1:...
    @staticmethod
    def GetSoapActionFromMethodBase(mb: _n_1_t_0) -> str:...
    @staticmethod
    def GetTypeAndMethodNameFromSoapAction(soapAction: str, typeName: str, methodName: str) -> bool:...
    @staticmethod
    def GetXmlElementForInteropType(type: _n_0_t_1, xmlElement: str, xmlNamespace: str) -> bool:...
    @staticmethod
    def GetXmlNamespaceForMethodCall(mb: _n_1_t_0) -> str:...
    @staticmethod
    def GetXmlNamespaceForMethodResponse(mb: _n_1_t_0) -> str:...
    @staticmethod
    def GetXmlTypeForInteropType(type: _n_0_t_1, xmlType: str, xmlTypeNamespace: str) -> bool:...
    @staticmethod
    def IsClrTypeNamespace(namespaceString: str) -> bool:...
    @staticmethod
    def IsSoapActionValidForMethodBase(soapAction: str, mb: _n_1_t_0) -> bool:...
    @staticmethod
    def PreLoad(assembly: _n_1_t_1):...
    @staticmethod
    def PreLoad(type: _n_0_t_1):...
    @staticmethod
    def RegisterInteropXmlElement(xmlElement: str, xmlNamespace: str, type: _n_0_t_1):...
    @staticmethod
    def RegisterInteropXmlType(xmlType: str, xmlTypeNamespace: str, type: _n_0_t_1):...
    @staticmethod
    def RegisterSoapActionForMethodBase(mb: _n_1_t_0, soapAction: str):...
    @staticmethod
    def RegisterSoapActionForMethodBase(mb: _n_1_t_0):...
class TypeEntry(object):
    @property
    def AssemblyName(self) -> str:"""AssemblyName { get; set; } -> str"""
    @property
    def TypeName(self) -> str:"""TypeName { get; set; } -> str"""
class WellKnownClientTypeEntry(TypeEntry):
    @property
    def ApplicationUrl(self) -> str:"""ApplicationUrl { get; set; } -> str"""
    @property
    def ObjectType(self) -> _n_0_t_1:"""ObjectType { get; } -> Type"""
    @property
    def ObjectUrl(self) -> str:"""ObjectUrl { get; } -> str"""
    def __init__(self, type: _n_0_t_1, objectUrl: str) -> WellKnownClientTypeEntry:...
    def __init__(self, typeName: str, assemblyName: str, objectUrl: str) -> WellKnownClientTypeEntry:...
class WellKnownObjectMode(_n_0_t_2, _n_0_t_3, _n_0_t_4, _n_0_t_5):
    SingleCall: int
    Singleton: int
    value__: int
class WellKnownServiceTypeEntry(TypeEntry):
    @property
    def ContextAttributes(self) -> _n_0_t_0[_n_3_t_0]:"""ContextAttributes { get; set; } -> Array"""
    @property
    def Mode(self) -> WellKnownObjectMode:"""Mode { get; } -> WellKnownObjectMode"""
    @property
    def ObjectType(self) -> _n_0_t_1:"""ObjectType { get; } -> Type"""
    @property
    def ObjectUri(self) -> str:"""ObjectUri { get; } -> str"""
    def __init__(self, type: _n_0_t_1, objectUri: str, mode: WellKnownObjectMode) -> WellKnownServiceTypeEntry:...
    def __init__(self, typeName: str, assemblyName: str, objectUri: str, mode: WellKnownObjectMode) -> WellKnownServiceTypeEntry:...
