import __clrclasses__.System.Text.RegularExpressions as RegularExpressions
from __clrclasses__.System.Text import ASCIIEncoding
from __clrclasses__.System.Text import Decoder
from __clrclasses__.System.Text import DecoderExceptionFallback
from __clrclasses__.System.Text import DecoderExceptionFallbackBuffer
from __clrclasses__.System.Text import DecoderFallback
from __clrclasses__.System.Text import DecoderFallbackBuffer
from __clrclasses__.System.Text import DecoderFallbackException
from __clrclasses__.System.Text import DecoderReplacementFallback
from __clrclasses__.System.Text import DecoderReplacementFallbackBuffer
from __clrclasses__.System.Text import Encoder
from __clrclasses__.System.Text import EncoderExceptionFallback
from __clrclasses__.System.Text import EncoderExceptionFallbackBuffer
from __clrclasses__.System.Text import EncoderFallback
from __clrclasses__.System.Text import EncoderFallbackBuffer
from __clrclasses__.System.Text import EncoderFallbackException
from __clrclasses__.System.Text import EncoderReplacementFallback
from __clrclasses__.System.Text import EncoderReplacementFallbackBuffer
from __clrclasses__.System.Text import Encoding
from __clrclasses__.System.Text import EncodingInfo
from __clrclasses__.System.Text import EncodingProvider
from __clrclasses__.System.Text import NormalizationForm
from __clrclasses__.System.Text import StringBuilder
from __clrclasses__.System.Text import UnicodeEncoding
from __clrclasses__.System.Text import UTF32Encoding
from __clrclasses__.System.Text import UTF7Encoding
from __clrclasses__.System.Text import UTF8Encoding
