from __clrclasses__.System import ActivationContext as _n_0_t_0
from __clrclasses__.System import Array as _n_0_t_1
from __clrclasses__.System import ApplicationIdentity as _n_0_t_2
from __clrclasses__.System.Runtime.Remoting import ObjectHandle as _n_1_t_0
from __clrclasses__.System.Security.Policy import EvidenceBase as _n_2_t_0
import typing
class ActivationArguments(_n_2_t_0):
    @property
    def ActivationContext(self) -> _n_0_t_0:"""ActivationContext { get; } -> ActivationContext"""
    @property
    def ActivationData(self) -> _n_0_t_1[str]:"""ActivationData { get; } -> Array"""
    @property
    def ApplicationIdentity(self) -> _n_0_t_2:"""ApplicationIdentity { get; } -> ApplicationIdentity"""
    def __init__(self, activationContext: _n_0_t_0, activationData: _n_0_t_1[str]) -> ActivationArguments:...
    def __init__(self, activationData: _n_0_t_0) -> ActivationArguments:...
    def __init__(self, applicationIdentity: _n_0_t_2, activationData: _n_0_t_1[str]) -> ActivationArguments:...
    def __init__(self, applicationIdentity: _n_0_t_2) -> ActivationArguments:...
class ApplicationActivator(object):
    def __init__(self) -> ApplicationActivator:...
    def CreateInstance(self, activationContext: _n_0_t_0, activationCustomData: _n_0_t_1[str]) -> _n_1_t_0:...
    def CreateInstance(self, activationContext: _n_0_t_0) -> _n_1_t_0:...
