from __clrclasses__.System import Byte as _n_0_t_0
from __clrclasses__.System import Array as _n_0_t_1
from __clrclasses__.System import DateTime as _n_0_t_2
from __clrclasses__.System import TimeSpan as _n_0_t_3
from __clrclasses__.System import Decimal as _n_0_t_4
import typing
class ISoapXsd():
    def GetXsdType(self) -> str:...
class SoapAnyUri(ISoapXsd):
    @property
    def Value(self) -> str:"""Value { get; set; } -> str"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: str) -> SoapAnyUri:...
    def __init__(self) -> SoapAnyUri:...
    @staticmethod
    def Parse(value: str) -> SoapAnyUri:...
class SoapBase64Binary(ISoapXsd):
    @property
    def Value(self) -> _n_0_t_1[_n_0_t_0]:"""Value { get; set; } -> Array"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: _n_0_t_1[_n_0_t_0]) -> SoapBase64Binary:...
    def __init__(self) -> SoapBase64Binary:...
    @staticmethod
    def Parse(value: str) -> SoapBase64Binary:...
class SoapDate(ISoapXsd):
    @property
    def Sign(self) -> int:"""Sign { get; set; } -> int"""
    @property
    def Value(self) -> _n_0_t_2:"""Value { get; set; } -> DateTime"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: _n_0_t_2, sign: int) -> SoapDate:...
    def __init__(self, value: _n_0_t_2) -> SoapDate:...
    def __init__(self) -> SoapDate:...
    @staticmethod
    def Parse(value: str) -> SoapDate:...
class SoapDateTime(object):
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self) -> SoapDateTime:...
    @staticmethod
    def Parse(value: str) -> _n_0_t_2:...
class SoapDay(ISoapXsd):
    @property
    def Value(self) -> _n_0_t_2:"""Value { get; set; } -> DateTime"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: _n_0_t_2) -> SoapDay:...
    def __init__(self) -> SoapDay:...
    @staticmethod
    def Parse(value: str) -> SoapDay:...
class SoapDuration(object):
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self) -> SoapDuration:...
    @staticmethod
    def Parse(value: str) -> _n_0_t_3:...
class SoapEntities(ISoapXsd):
    @property
    def Value(self) -> str:"""Value { get; set; } -> str"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: str) -> SoapEntities:...
    def __init__(self) -> SoapEntities:...
    @staticmethod
    def Parse(value: str) -> SoapEntities:...
class SoapEntity(ISoapXsd):
    @property
    def Value(self) -> str:"""Value { get; set; } -> str"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: str) -> SoapEntity:...
    def __init__(self) -> SoapEntity:...
    @staticmethod
    def Parse(value: str) -> SoapEntity:...
class SoapHexBinary(ISoapXsd):
    @property
    def Value(self) -> _n_0_t_1[_n_0_t_0]:"""Value { get; set; } -> Array"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: _n_0_t_1[_n_0_t_0]) -> SoapHexBinary:...
    def __init__(self) -> SoapHexBinary:...
    @staticmethod
    def Parse(value: str) -> SoapHexBinary:...
class SoapId(ISoapXsd):
    @property
    def Value(self) -> str:"""Value { get; set; } -> str"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: str) -> SoapId:...
    def __init__(self) -> SoapId:...
    @staticmethod
    def Parse(value: str) -> SoapId:...
class SoapIdref(ISoapXsd):
    @property
    def Value(self) -> str:"""Value { get; set; } -> str"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: str) -> SoapIdref:...
    def __init__(self) -> SoapIdref:...
    @staticmethod
    def Parse(value: str) -> SoapIdref:...
class SoapIdrefs(ISoapXsd):
    @property
    def Value(self) -> str:"""Value { get; set; } -> str"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: str) -> SoapIdrefs:...
    def __init__(self) -> SoapIdrefs:...
    @staticmethod
    def Parse(value: str) -> SoapIdrefs:...
class SoapInteger(ISoapXsd):
    @property
    def Value(self) -> _n_0_t_4:"""Value { get; set; } -> Decimal"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: _n_0_t_4) -> SoapInteger:...
    def __init__(self) -> SoapInteger:...
    @staticmethod
    def Parse(value: str) -> SoapInteger:...
class SoapLanguage(ISoapXsd):
    @property
    def Value(self) -> str:"""Value { get; set; } -> str"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: str) -> SoapLanguage:...
    def __init__(self) -> SoapLanguage:...
    @staticmethod
    def Parse(value: str) -> SoapLanguage:...
class SoapMonth(ISoapXsd):
    @property
    def Value(self) -> _n_0_t_2:"""Value { get; set; } -> DateTime"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: _n_0_t_2) -> SoapMonth:...
    def __init__(self) -> SoapMonth:...
    @staticmethod
    def Parse(value: str) -> SoapMonth:...
class SoapMonthDay(ISoapXsd):
    @property
    def Value(self) -> _n_0_t_2:"""Value { get; set; } -> DateTime"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: _n_0_t_2) -> SoapMonthDay:...
    def __init__(self) -> SoapMonthDay:...
    @staticmethod
    def Parse(value: str) -> SoapMonthDay:...
class SoapName(ISoapXsd):
    @property
    def Value(self) -> str:"""Value { get; set; } -> str"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: str) -> SoapName:...
    def __init__(self) -> SoapName:...
    @staticmethod
    def Parse(value: str) -> SoapName:...
class SoapNcName(ISoapXsd):
    @property
    def Value(self) -> str:"""Value { get; set; } -> str"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: str) -> SoapNcName:...
    def __init__(self) -> SoapNcName:...
    @staticmethod
    def Parse(value: str) -> SoapNcName:...
class SoapNegativeInteger(ISoapXsd):
    @property
    def Value(self) -> _n_0_t_4:"""Value { get; set; } -> Decimal"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: _n_0_t_4) -> SoapNegativeInteger:...
    def __init__(self) -> SoapNegativeInteger:...
    @staticmethod
    def Parse(value: str) -> SoapNegativeInteger:...
class SoapNmtoken(ISoapXsd):
    @property
    def Value(self) -> str:"""Value { get; set; } -> str"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: str) -> SoapNmtoken:...
    def __init__(self) -> SoapNmtoken:...
    @staticmethod
    def Parse(value: str) -> SoapNmtoken:...
class SoapNmtokens(ISoapXsd):
    @property
    def Value(self) -> str:"""Value { get; set; } -> str"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: str) -> SoapNmtokens:...
    def __init__(self) -> SoapNmtokens:...
    @staticmethod
    def Parse(value: str) -> SoapNmtokens:...
class SoapNonNegativeInteger(ISoapXsd):
    @property
    def Value(self) -> _n_0_t_4:"""Value { get; set; } -> Decimal"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: _n_0_t_4) -> SoapNonNegativeInteger:...
    def __init__(self) -> SoapNonNegativeInteger:...
    @staticmethod
    def Parse(value: str) -> SoapNonNegativeInteger:...
class SoapNonPositiveInteger(ISoapXsd):
    @property
    def Value(self) -> _n_0_t_4:"""Value { get; set; } -> Decimal"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: _n_0_t_4) -> SoapNonPositiveInteger:...
    def __init__(self) -> SoapNonPositiveInteger:...
    @staticmethod
    def Parse(value: str) -> SoapNonPositiveInteger:...
class SoapNormalizedString(ISoapXsd):
    @property
    def Value(self) -> str:"""Value { get; set; } -> str"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: str) -> SoapNormalizedString:...
    def __init__(self) -> SoapNormalizedString:...
    @staticmethod
    def Parse(value: str) -> SoapNormalizedString:...
class SoapNotation(ISoapXsd):
    @property
    def Value(self) -> str:"""Value { get; set; } -> str"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: str) -> SoapNotation:...
    def __init__(self) -> SoapNotation:...
    @staticmethod
    def Parse(value: str) -> SoapNotation:...
class SoapPositiveInteger(ISoapXsd):
    @property
    def Value(self) -> _n_0_t_4:"""Value { get; set; } -> Decimal"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: _n_0_t_4) -> SoapPositiveInteger:...
    def __init__(self) -> SoapPositiveInteger:...
    @staticmethod
    def Parse(value: str) -> SoapPositiveInteger:...
class SoapQName(ISoapXsd):
    @property
    def Key(self) -> str:"""Key { get; set; } -> str"""
    @property
    def Name(self) -> str:"""Name { get; set; } -> str"""
    @property
    def Namespace(self) -> str:"""Namespace { get; set; } -> str"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, key: str, name: str, namespaceValue: str) -> SoapQName:...
    def __init__(self, key: str, name: str) -> SoapQName:...
    def __init__(self, value: str) -> SoapQName:...
    def __init__(self) -> SoapQName:...
    @staticmethod
    def Parse(value: str) -> SoapQName:...
class SoapTime(ISoapXsd):
    @property
    def Value(self) -> _n_0_t_2:"""Value { get; set; } -> DateTime"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: _n_0_t_2) -> SoapTime:...
    def __init__(self) -> SoapTime:...
    @staticmethod
    def Parse(value: str) -> SoapTime:...
class SoapToken(ISoapXsd):
    @property
    def Value(self) -> str:"""Value { get; set; } -> str"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: str) -> SoapToken:...
    def __init__(self) -> SoapToken:...
    @staticmethod
    def Parse(value: str) -> SoapToken:...
class SoapYear(ISoapXsd):
    @property
    def Sign(self) -> int:"""Sign { get; set; } -> int"""
    @property
    def Value(self) -> _n_0_t_2:"""Value { get; set; } -> DateTime"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: _n_0_t_2, sign: int) -> SoapYear:...
    def __init__(self, value: _n_0_t_2) -> SoapYear:...
    def __init__(self) -> SoapYear:...
    @staticmethod
    def Parse(value: str) -> SoapYear:...
class SoapYearMonth(ISoapXsd):
    @property
    def Sign(self) -> int:"""Sign { get; set; } -> int"""
    @property
    def Value(self) -> _n_0_t_2:"""Value { get; set; } -> DateTime"""
    @property
    def XsdType(self) -> str:"""XsdType { get; } -> str"""
    def __init__(self, value: _n_0_t_2, sign: int) -> SoapYearMonth:...
    def __init__(self, value: _n_0_t_2) -> SoapYearMonth:...
    def __init__(self) -> SoapYearMonth:...
    @staticmethod
    def Parse(value: str) -> SoapYearMonth:...
