import __clrclasses__.System.Security.Authentication.ExtendedProtection as ExtendedProtection
from __clrclasses__.System.Security.Authentication import AuthenticationException
from __clrclasses__.System.Security.Authentication import CipherAlgorithmType
from __clrclasses__.System.Security.Authentication import ExchangeAlgorithmType
from __clrclasses__.System.Security.Authentication import HashAlgorithmType
from __clrclasses__.System.Security.Authentication import InvalidCredentialException
from __clrclasses__.System.Security.Authentication import SslProtocols
