from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import ISoapXsd
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapAnyUri
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapBase64Binary
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapDate
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapDateTime
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapDay
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapDuration
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapEntities
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapEntity
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapHexBinary
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapId
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapIdref
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapIdrefs
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapInteger
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapLanguage
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapMonth
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapMonthDay
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapName
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapNcName
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapNegativeInteger
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapNmtoken
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapNmtokens
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapNonNegativeInteger
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapNonPositiveInteger
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapNormalizedString
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapNotation
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapPositiveInteger
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapQName
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapTime
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapToken
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapYear
from __clrclasses__.System.Runtime.Remoting.Metadata.W3cXsd2001 import SoapYearMonth
