import __clrclasses__.System.Net.WebSockets as WebSockets
import __clrclasses__.System.Net.Mime as Mime
import __clrclasses__.System.Net.Mail as Mail
import __clrclasses__.System.Net.NetworkInformation as NetworkInformation
import __clrclasses__.System.Net.Cache as Cache
import __clrclasses__.System.Net.Configuration as Configuration
import __clrclasses__.System.Net.Security as Security
import __clrclasses__.System.Net.Sockets as Sockets
from __clrclasses__.System.Net import AuthenticationManager
from __clrclasses__.System.Net import AuthenticationSchemes
from __clrclasses__.System.Net import AuthenticationSchemeSelector
from __clrclasses__.System.Net import Authorization
from __clrclasses__.System.Net import BindIPEndPoint
from __clrclasses__.System.Net import Cookie
from __clrclasses__.System.Net import CookieCollection
from __clrclasses__.System.Net import CookieContainer
from __clrclasses__.System.Net import CookieException
from __clrclasses__.System.Net import CredentialCache
from __clrclasses__.System.Net import DecompressionMethods
from __clrclasses__.System.Net import Dns
from __clrclasses__.System.Net import DnsEndPoint
from __clrclasses__.System.Net import DnsPermission
from __clrclasses__.System.Net import DnsPermissionAttribute
from __clrclasses__.System.Net import DownloadDataCompletedEventArgs
from __clrclasses__.System.Net import DownloadDataCompletedEventHandler
from __clrclasses__.System.Net import DownloadProgressChangedEventArgs
from __clrclasses__.System.Net import DownloadProgressChangedEventHandler
from __clrclasses__.System.Net import DownloadStringCompletedEventArgs
from __clrclasses__.System.Net import DownloadStringCompletedEventHandler
from __clrclasses__.System.Net import EndPoint
from __clrclasses__.System.Net import EndpointPermission
from __clrclasses__.System.Net import FileWebRequest
from __clrclasses__.System.Net import FileWebResponse
from __clrclasses__.System.Net import FtpStatusCode
from __clrclasses__.System.Net import FtpWebRequest
from __clrclasses__.System.Net import FtpWebResponse
from __clrclasses__.System.Net import GlobalProxySelection
from __clrclasses__.System.Net import HttpContinueDelegate
from __clrclasses__.System.Net import HttpListener
from __clrclasses__.System.Net import HttpListenerBasicIdentity
from __clrclasses__.System.Net import HttpListenerContext
from __clrclasses__.System.Net import HttpListenerException
from __clrclasses__.System.Net import HttpListenerPrefixCollection
from __clrclasses__.System.Net import HttpListenerRequest
from __clrclasses__.System.Net import HttpListenerResponse
from __clrclasses__.System.Net import HttpListenerTimeoutManager
from __clrclasses__.System.Net import HttpRequestHeader
from __clrclasses__.System.Net import HttpResponseHeader
from __clrclasses__.System.Net import HttpStatusCode
from __clrclasses__.System.Net import HttpVersion
from __clrclasses__.System.Net import HttpWebRequest
from __clrclasses__.System.Net import HttpWebResponse
from __clrclasses__.System.Net import IAuthenticationModule
from __clrclasses__.System.Net import ICertificatePolicy
from __clrclasses__.System.Net import ICredentialPolicy
from __clrclasses__.System.Net import ICredentials
from __clrclasses__.System.Net import ICredentialsByHost
from __clrclasses__.System.Net import IPAddress
from __clrclasses__.System.Net import IPEndPoint
from __clrclasses__.System.Net import IPHostEntry
from __clrclasses__.System.Net import IWebProxy
from __clrclasses__.System.Net import IWebProxyScript
from __clrclasses__.System.Net import IWebRequestCreate
from __clrclasses__.System.Net import NetworkAccess
from __clrclasses__.System.Net import NetworkCredential
from __clrclasses__.System.Net import OpenReadCompletedEventArgs
from __clrclasses__.System.Net import OpenReadCompletedEventHandler
from __clrclasses__.System.Net import OpenWriteCompletedEventArgs
from __clrclasses__.System.Net import OpenWriteCompletedEventHandler
from __clrclasses__.System.Net import ProtocolViolationException
from __clrclasses__.System.Net import SecurityProtocolType
from __clrclasses__.System.Net import ServicePoint
from __clrclasses__.System.Net import ServicePointManager
from __clrclasses__.System.Net import SocketAddress
from __clrclasses__.System.Net import SocketPermission
from __clrclasses__.System.Net import SocketPermissionAttribute
from __clrclasses__.System.Net import TransportContext
from __clrclasses__.System.Net import TransportType
from __clrclasses__.System.Net import UploadDataCompletedEventArgs
from __clrclasses__.System.Net import UploadDataCompletedEventHandler
from __clrclasses__.System.Net import UploadFileCompletedEventArgs
from __clrclasses__.System.Net import UploadFileCompletedEventHandler
from __clrclasses__.System.Net import UploadProgressChangedEventArgs
from __clrclasses__.System.Net import UploadProgressChangedEventHandler
from __clrclasses__.System.Net import UploadStringCompletedEventArgs
from __clrclasses__.System.Net import UploadStringCompletedEventHandler
from __clrclasses__.System.Net import UploadValuesCompletedEventArgs
from __clrclasses__.System.Net import UploadValuesCompletedEventHandler
from __clrclasses__.System.Net import WebClient
from __clrclasses__.System.Net import WebException
from __clrclasses__.System.Net import WebExceptionStatus
from __clrclasses__.System.Net import WebHeaderCollection
from __clrclasses__.System.Net import WebPermission
from __clrclasses__.System.Net import WebPermissionAttribute
from __clrclasses__.System.Net import WebProxy
from __clrclasses__.System.Net import WebRequest
from __clrclasses__.System.Net import WebRequestMethods
from __clrclasses__.System.Net import WebResponse
from __clrclasses__.System.Net import WebUtility
from __clrclasses__.System.Net import WriteStreamClosedEventArgs
from __clrclasses__.System.Net import WriteStreamClosedEventHandler
