from __clrclasses__.System import MarshalByRefObject as _n_0_t_0
from __clrclasses__.System import UInt64 as _n_0_t_1
from __clrclasses__.System import Exception as _n_0_t_2
from __clrclasses__.System import IDisposable as _n_0_t_3
from __clrclasses__.System import DateTimeOffset as _n_0_t_4
from __clrclasses__.System import Array as _n_0_t_5
from __clrclasses__.System import Type as _n_0_t_6
from __clrclasses__.System import Enum as _n_0_t_7
from __clrclasses__.System import IComparable as _n_0_t_8
from __clrclasses__.System import IFormattable as _n_0_t_9
from __clrclasses__.System import IConvertible as _n_0_t_10
from __clrclasses__.System.Collections import IEnumerator as _n_1_t_0
from __clrclasses__.System.IO import FileMode as _n_2_t_0
from __clrclasses__.System.IO import FileAccess as _n_2_t_1
from __clrclasses__.System.IO import FileShare as _n_2_t_2
from __clrclasses__.System.IO import FileStream as _n_2_t_3
from __clrclasses__.System.Runtime.InteropServices import _Exception as _n_3_t_0
from __clrclasses__.System.Runtime.Serialization import ISerializable as _n_4_t_0
from __clrclasses__.System.Security import SecurityState as _n_5_t_0
from __clrclasses__.System.Security.Policy import Evidence as _n_6_t_0
import typing
class INormalizeForIsolatedStorage():
    def Normalize(self) -> object:...
class IsolatedStorage(_n_0_t_0):
    @property
    def ApplicationIdentity(self) -> object:"""ApplicationIdentity { get; } -> object"""
    @property
    def AssemblyIdentity(self) -> object:"""AssemblyIdentity { get; } -> object"""
    @property
    def AvailableFreeSpace(self) -> int:"""AvailableFreeSpace { get; } -> int"""
    @property
    def CurrentSize(self) -> _n_0_t_1:"""CurrentSize { get; } -> UInt64"""
    @property
    def DomainIdentity(self) -> object:"""DomainIdentity { get; } -> object"""
    @property
    def MaximumSize(self) -> _n_0_t_1:"""MaximumSize { get; } -> UInt64"""
    @property
    def Quota(self) -> int:"""Quota { get; set; } -> int"""
    @property
    def Scope(self) -> IsolatedStorageScope:"""Scope { get; } -> IsolatedStorageScope"""
    @property
    def UsedSize(self) -> int:"""UsedSize { get; } -> int"""
    def IncreaseQuotaTo(self, newQuotaSize: int) -> bool:...
    def Remove(self):...
class IsolatedStorageException(_n_0_t_2, _n_4_t_0, _n_3_t_0):
    def __init__(self, message: str, inner: _n_0_t_2) -> IsolatedStorageException:...
    def __init__(self, message: str) -> IsolatedStorageException:...
    def __init__(self) -> IsolatedStorageException:...
class IsolatedStorageFile(IsolatedStorage, _n_0_t_3):
    @property
    def IsEnabled(self) -> bool:"""IsEnabled { get; } -> bool"""
    def Close(self):...
    def CopyFile(self, sourceFileName: str, destinationFileName: str, overwrite: bool):...
    def CopyFile(self, sourceFileName: str, destinationFileName: str):...
    def CreateDirectory(self, dir: str):...
    def CreateFile(self, path: str) -> IsolatedStorageFileStream:...
    def DeleteDirectory(self, dir: str):...
    def DeleteFile(self, file: str):...
    def DirectoryExists(self, path: str) -> bool:...
    def FileExists(self, path: str) -> bool:...
    def GetCreationTime(self, path: str) -> _n_0_t_4:...
    def GetDirectoryNames(self, searchPattern: str) -> _n_0_t_5[str]:...
    def GetDirectoryNames(self) -> _n_0_t_5[str]:...
    @staticmethod
    def GetEnumerator(scope: IsolatedStorageScope) -> _n_1_t_0:...
    def GetFileNames(self, searchPattern: str) -> _n_0_t_5[str]:...
    def GetFileNames(self) -> _n_0_t_5[str]:...
    def GetLastAccessTime(self, path: str) -> _n_0_t_4:...
    def GetLastWriteTime(self, path: str) -> _n_0_t_4:...
    @staticmethod
    def GetMachineStoreForApplication() -> IsolatedStorageFile:...
    @staticmethod
    def GetMachineStoreForAssembly() -> IsolatedStorageFile:...
    @staticmethod
    def GetMachineStoreForDomain() -> IsolatedStorageFile:...
    @staticmethod
    def GetStore(scope: IsolatedStorageScope, applicationIdentity: object) -> IsolatedStorageFile:...
    @staticmethod
    def GetStore(scope: IsolatedStorageScope, applicationEvidenceType: _n_0_t_6) -> IsolatedStorageFile:...
    @staticmethod
    def GetStore(scope: IsolatedStorageScope, domainEvidence: _n_6_t_0, domainEvidenceType: _n_0_t_6, assemblyEvidence: _n_6_t_0, assemblyEvidenceType: _n_0_t_6) -> IsolatedStorageFile:...
    @staticmethod
    def GetStore(scope: IsolatedStorageScope, domainIdentity: object, assemblyIdentity: object) -> IsolatedStorageFile:...
    @staticmethod
    def GetStore(scope: IsolatedStorageScope, domainEvidenceType: _n_0_t_6, assemblyEvidenceType: _n_0_t_6) -> IsolatedStorageFile:...
    @staticmethod
    def GetUserStoreForApplication() -> IsolatedStorageFile:...
    @staticmethod
    def GetUserStoreForAssembly() -> IsolatedStorageFile:...
    @staticmethod
    def GetUserStoreForDomain() -> IsolatedStorageFile:...
    @staticmethod
    def GetUserStoreForSite() -> IsolatedStorageFile:...
    def MoveDirectory(self, sourceDirectoryName: str, destinationDirectoryName: str):...
    def MoveFile(self, sourceFileName: str, destinationFileName: str):...
    def OpenFile(self, path: str, mode: _n_2_t_0, access: _n_2_t_1, share: _n_2_t_2) -> IsolatedStorageFileStream:...
    def OpenFile(self, path: str, mode: _n_2_t_0, access: _n_2_t_1) -> IsolatedStorageFileStream:...
    def OpenFile(self, path: str, mode: _n_2_t_0) -> IsolatedStorageFileStream:...
class IsolatedStorageFileStream(_n_2_t_3, _n_0_t_3):
    def __init__(self, path: str, mode: _n_2_t_0, access: _n_2_t_1, share: _n_2_t_2, bufferSize: int, isf: IsolatedStorageFile) -> IsolatedStorageFileStream:...
    def __init__(self, path: str, mode: _n_2_t_0, access: _n_2_t_1, share: _n_2_t_2, bufferSize: int) -> IsolatedStorageFileStream:...
    def __init__(self, path: str, mode: _n_2_t_0, access: _n_2_t_1, share: _n_2_t_2, isf: IsolatedStorageFile) -> IsolatedStorageFileStream:...
    def __init__(self, path: str, mode: _n_2_t_0, access: _n_2_t_1, share: _n_2_t_2) -> IsolatedStorageFileStream:...
    def __init__(self, path: str, mode: _n_2_t_0, access: _n_2_t_1, isf: IsolatedStorageFile) -> IsolatedStorageFileStream:...
    def __init__(self, path: str, mode: _n_2_t_0, access: _n_2_t_1) -> IsolatedStorageFileStream:...
    def __init__(self, path: str, mode: _n_2_t_0, isf: IsolatedStorageFile) -> IsolatedStorageFileStream:...
    def __init__(self, path: str, mode: _n_2_t_0) -> IsolatedStorageFileStream:...
class IsolatedStorageScope(_n_0_t_7, _n_0_t_8, _n_0_t_9, _n_0_t_10):
    Application: int
    Assembly: int
    Domain: int
    Machine: int
    _None: int
    Roaming: int
    User: int
    value__: int
class IsolatedStorageSecurityOptions(_n_0_t_7, _n_0_t_8, _n_0_t_9, _n_0_t_10):
    IncreaseQuotaForApplication: int
    value__: int
class IsolatedStorageSecurityState(_n_5_t_0):
    @property
    def Options(self) -> IsolatedStorageSecurityOptions:"""Options { get; } -> IsolatedStorageSecurityOptions"""
    @property
    def Quota(self) -> int:"""Quota { get; set; } -> int"""
    @property
    def UsedSize(self) -> int:"""UsedSize { get; } -> int"""
