
location: str
mainpath: str
libpath: str
supportpath: str
extensionspath: str

def runsyscmd(name: str):...

def runcmd(name: str):...

def invokelisp(name: str, args):...

def settempvalue(value: object):...

def gettempvalue() -> object:...

def execute(code: str) -> object:...

def executefile(path: str):...

def findfile(modulename: str, filename) -> str:...

def install(extfile: str):...

def version():...

def release(module: module):...

def build(module: module):...

def reference(filename: str):...