from __clrclasses__.System import IDisposable as _n_0_t_0
from __clrclasses__.System import Byte as _n_0_t_1
from __clrclasses__.System import Array as _n_0_t_2
from __clrclasses__.System import SystemException as _n_0_t_3
from __clrclasses__.System import Exception as _n_0_t_4
from __clrclasses__.System import Attribute as _n_0_t_5
from __clrclasses__.System import Type as _n_0_t_6
from __clrclasses__.System import Func as _n_0_t_7
from __clrclasses__.System import Enum as _n_0_t_8
from __clrclasses__.System import IComparable as _n_0_t_9
from __clrclasses__.System import IFormattable as _n_0_t_10
from __clrclasses__.System import IConvertible as _n_0_t_11
from __clrclasses__.System.Collections import IEnumerable as _n_1_t_0
from __clrclasses__.System.Globalization import CultureInfo as _n_2_t_0
from __clrclasses__.System.IO import UnmanagedMemoryStream as _n_3_t_0
from __clrclasses__.System.IO import Stream as _n_3_t_1
from __clrclasses__.System.Reflection import Assembly as _n_4_t_0
from __clrclasses__.System.Runtime.InteropServices import _Exception as _n_5_t_0
from __clrclasses__.System.Runtime.InteropServices import _Attribute as _n_5_t_1
from __clrclasses__.System.Runtime.Serialization import ISerializable as _n_6_t_0
import typing
class IResourceReader(_n_1_t_0, _n_0_t_0):
    def Close(self):...
class IResourceWriter(_n_0_t_0):
    def AddResource(self, name: str, value: _n_0_t_2[_n_0_t_1]):...
    def AddResource(self, name: str, value: object):...
    def AddResource(self, name: str, value: str):...
    def Close(self):...
    def Generate(self):...
class MissingManifestResourceException(_n_0_t_3, _n_6_t_0, _n_5_t_0):
    def __init__(self, message: str, inner: _n_0_t_4) -> MissingManifestResourceException:...
    def __init__(self, message: str) -> MissingManifestResourceException:...
    def __init__(self) -> MissingManifestResourceException:...
class MissingSatelliteAssemblyException(_n_0_t_3, _n_6_t_0, _n_5_t_0):
    @property
    def CultureName(self) -> str:"""CultureName { get; } -> str"""
    def __init__(self, message: str, inner: _n_0_t_4) -> MissingSatelliteAssemblyException:...
    def __init__(self, message: str, cultureName: str) -> MissingSatelliteAssemblyException:...
    def __init__(self, message: str) -> MissingSatelliteAssemblyException:...
    def __init__(self) -> MissingSatelliteAssemblyException:...
class NeutralResourcesLanguageAttribute(_n_0_t_5, _n_5_t_1):
    @property
    def CultureName(self) -> str:"""CultureName { get; } -> str"""
    @property
    def Location(self) -> UltimateResourceFallbackLocation:"""Location { get; } -> UltimateResourceFallbackLocation"""
    def __init__(self, cultureName: str, location: UltimateResourceFallbackLocation) -> NeutralResourcesLanguageAttribute:...
    def __init__(self, cultureName: str) -> NeutralResourcesLanguageAttribute:...
class ResourceManager(object):
    HeaderVersionNumber: int
    MagicNumber: int
    @property
    def BaseName(self) -> str:"""BaseName { get; } -> str"""
    @property
    def IgnoreCase(self) -> bool:"""IgnoreCase { get; set; } -> bool"""
    @property
    def ResourceSetType(self) -> _n_0_t_6:"""ResourceSetType { get; } -> Type"""
    def __init__(self, resourceSource: _n_0_t_6) -> ResourceManager:...
    def __init__(self, baseName: str, assembly: _n_4_t_0, usingResourceSet: _n_0_t_6) -> ResourceManager:...
    def __init__(self, baseName: str, assembly: _n_4_t_0) -> ResourceManager:...
    @staticmethod
    def CreateFileBasedResourceManager(baseName: str, resourceDir: str, usingResourceSet: _n_0_t_6) -> ResourceManager:...
    def GetObject(self, name: str, culture: _n_2_t_0) -> object:...
    def GetObject(self, name: str) -> object:...
    def GetResourceSet(self, culture: _n_2_t_0, createIfNotExists: bool, tryParents: bool) -> ResourceSet:...
    def GetStream(self, name: str, culture: _n_2_t_0) -> _n_3_t_0:...
    def GetStream(self, name: str) -> _n_3_t_0:...
    def GetString(self, name: str, culture: _n_2_t_0) -> str:...
    def GetString(self, name: str) -> str:...
    def ReleaseAllResources(self):...
class ResourceReader(IResourceReader):
    def __init__(self, stream: _n_3_t_1) -> ResourceReader:...
    def __init__(self, fileName: str) -> ResourceReader:...
    def GetResourceData(self, resourceName: str, resourceType: str, resourceData: _n_0_t_2[_n_0_t_1]):...
class ResourceSet(_n_0_t_0, _n_1_t_0):
    def __init__(self, reader: IResourceReader) -> ResourceSet:...
    def __init__(self, stream: _n_3_t_1) -> ResourceSet:...
    def __init__(self, fileName: str) -> ResourceSet:...
    def Close(self):...
    def GetDefaultReader(self) -> _n_0_t_6:...
    def GetDefaultWriter(self) -> _n_0_t_6:...
    def GetObject(self, name: str, ignoreCase: bool) -> object:...
    def GetObject(self, name: str) -> object:...
    def GetString(self, name: str, ignoreCase: bool) -> str:...
    def GetString(self, name: str) -> str:...
class ResourceWriter(IResourceWriter):
    @property
    def TypeNameConverter(self) -> _n_0_t_7[_n_0_t_6, str]:"""TypeNameConverter { get; set; } -> Func"""
    def __init__(self, stream: _n_3_t_1) -> ResourceWriter:...
    def __init__(self, fileName: str) -> ResourceWriter:...
    def AddResourceData(self, name: str, typeName: str, serializedData: _n_0_t_2[_n_0_t_1]):...
class SatelliteContractVersionAttribute(_n_0_t_5, _n_5_t_1):
    @property
    def Version(self) -> str:"""Version { get; } -> str"""
    def __init__(self, version: str) -> SatelliteContractVersionAttribute:...
class UltimateResourceFallbackLocation(_n_0_t_8, _n_0_t_9, _n_0_t_10, _n_0_t_11):
    MainAssembly: int
    Satellite: int
    value__: int
