from __clrclasses__.System.Collections.Generic import Comparer
from __clrclasses__.System.Collections.Generic import Dictionary
from __clrclasses__.System.Collections.Generic import EqualityComparer
from __clrclasses__.System.Collections.Generic import HashSet
from __clrclasses__.System.Collections.Generic import ICollection
from __clrclasses__.System.Collections.Generic import IComparer
from __clrclasses__.System.Collections.Generic import IDictionary
from __clrclasses__.System.Collections.Generic import IEnumerable
from __clrclasses__.System.Collections.Generic import IEnumerator
from __clrclasses__.System.Collections.Generic import IEqualityComparer
from __clrclasses__.System.Collections.Generic import IList
from __clrclasses__.System.Collections.Generic import IReadOnlyCollection
from __clrclasses__.System.Collections.Generic import IReadOnlyDictionary
from __clrclasses__.System.Collections.Generic import IReadOnlyList
from __clrclasses__.System.Collections.Generic import ISet
from __clrclasses__.System.Collections.Generic import KeyNotFoundException
from __clrclasses__.System.Collections.Generic import KeyValuePair
from __clrclasses__.System.Collections.Generic import LinkedList
from __clrclasses__.System.Collections.Generic import LinkedListNode
from __clrclasses__.System.Collections.Generic import List
from __clrclasses__.System.Collections.Generic import Queue
from __clrclasses__.System.Collections.Generic import SortedDictionary
from __clrclasses__.System.Collections.Generic import SortedList
from __clrclasses__.System.Collections.Generic import SortedSet
from __clrclasses__.System.Collections.Generic import Stack
