import __clrclasses__.System.ComponentModel.Design as Design
from __clrclasses__.System import EventArgs as _n_0_t_0
from __clrclasses__.System import MulticastDelegate as _n_0_t_1
from __clrclasses__.System import ICloneable as _n_0_t_2
from __clrclasses__.System import IntPtr as _n_0_t_3
from __clrclasses__.System import IAsyncResult as _n_0_t_4
from __clrclasses__.System import AsyncCallback as _n_0_t_5
from __clrclasses__.System import Attribute as _n_0_t_6
from __clrclasses__.System import Byte as _n_0_t_7
from __clrclasses__.System import Char as _n_0_t_8
from __clrclasses__.System import Type as _n_0_t_9
from __clrclasses__.System import Exception as _n_0_t_10
from __clrclasses__.System import Array as _n_0_t_11
from __clrclasses__.System import Enum as _n_0_t_12
from __clrclasses__.System import IComparable as _n_0_t_13
from __clrclasses__.System import IFormattable as _n_0_t_14
from __clrclasses__.System import IConvertible as _n_0_t_15
from __clrclasses__.System import MarshalByRefObject as _n_0_t_16
from __clrclasses__.System import Delegate as _n_0_t_17
from __clrclasses__.System import IDisposable as _n_0_t_18
from __clrclasses__.System import EventHandler as _n_0_t_19
from __clrclasses__.System import ArgumentException as _n_0_t_20
from __clrclasses__.System import IServiceProvider as _n_0_t_21
from __clrclasses__.System import SystemException as _n_0_t_22
from __clrclasses__.System.Collections import ICollection as _n_1_t_0
from __clrclasses__.System.Collections import IList as _n_1_t_1
from __clrclasses__.System.Collections import ReadOnlyCollectionBase as _n_1_t_2
from __clrclasses__.System.Collections import IComparer as _n_1_t_3
from __clrclasses__.System.Collections import IEnumerable as _n_1_t_4
from __clrclasses__.System.Collections import IEnumerator as _n_1_t_5
from __clrclasses__.System.Collections import IDictionary as _n_1_t_6
from __clrclasses__.System.Collections import Hashtable as _n_1_t_7
from __clrclasses__.System.Collections.Generic import IList as _n_2_t_0
from __clrclasses__.System.Collections.Generic import IReadOnlyList as _n_2_t_1
from __clrclasses__.System.Collections.ObjectModel import Collection as _n_3_t_0
from __clrclasses__.System.ComponentModel.Design import IDesigner as _n_4_t_0
from __clrclasses__.System.Globalization import CultureInfo as _n_5_t_0
from __clrclasses__.System.Reflection import Assembly as _n_6_t_0
from __clrclasses__.System.Reflection import Module as _n_6_t_1
from __clrclasses__.System.Resources import ResourceManager as _n_7_t_0
from __clrclasses__.System.Runtime.InteropServices import _Attribute as _n_8_t_0
from __clrclasses__.System.Runtime.InteropServices import _Exception as _n_8_t_1
from __clrclasses__.System.Runtime.InteropServices import ExternalException as _n_8_t_2
from __clrclasses__.System.Runtime.Serialization import ISerializable as _n_9_t_0
from __clrclasses__.System.Threading import SynchronizationContext as _n_10_t_0
from __clrclasses__.System.Threading import SendOrPostCallback as _n_10_t_1
import typing
T = typing.TypeVar('T')
class AddingNewEventArgs(_n_0_t_0):
    @property
    def NewObject(self) -> object:"""NewObject { get; set; } -> object"""
    def __init__(self, newObject: object) -> AddingNewEventArgs:...
    def __init__(self) -> AddingNewEventArgs:...
class AddingNewEventHandler(_n_0_t_1, _n_0_t_2, _n_9_t_0):
    def __init__(self, object: object, method: _n_0_t_3) -> AddingNewEventHandler:...
    def BeginInvoke(self, sender: object, e: AddingNewEventArgs, callback: _n_0_t_5, object: object) -> _n_0_t_4:...
    def EndInvoke(self, result: _n_0_t_4):...
    def Invoke(self, sender: object, e: AddingNewEventArgs):...
class AmbientValueAttribute(_n_0_t_6, _n_8_t_0):
    @property
    def Value(self) -> object:"""Value { get; } -> object"""
    def __init__(self, value: object) -> AmbientValueAttribute:...
    def __init__(self, value: str) -> AmbientValueAttribute:...
    def __init__(self, value: bool) -> AmbientValueAttribute:...
    def __init__(self, value: float) -> AmbientValueAttribute:...
    def __init__(self, value: int) -> AmbientValueAttribute:...
    def __init__(self, value: _n_0_t_7) -> AmbientValueAttribute:...
    def __init__(self, value: _n_0_t_8) -> AmbientValueAttribute:...
    def __init__(self, type: _n_0_t_9, value: str) -> AmbientValueAttribute:...
class ArrayConverter(CollectionConverter):
    def __init__(self) -> ArrayConverter:...
class AsyncCompletedEventArgs(_n_0_t_0):
    @property
    def Cancelled(self) -> bool:"""Cancelled { get; } -> bool"""
    @property
    def Error(self) -> _n_0_t_10:"""Error { get; } -> Exception"""
    @property
    def UserState(self) -> object:"""UserState { get; } -> object"""
    def __init__(self, error: _n_0_t_10, cancelled: bool, userState: object) -> AsyncCompletedEventArgs:...
    def __init__(self) -> AsyncCompletedEventArgs:...
class AsyncCompletedEventHandler(_n_0_t_1, _n_0_t_2, _n_9_t_0):
    def __init__(self, object: object, method: _n_0_t_3) -> AsyncCompletedEventHandler:...
    def BeginInvoke(self, sender: object, e: AsyncCompletedEventArgs, callback: _n_0_t_5, object: object) -> _n_0_t_4:...
    def EndInvoke(self, result: _n_0_t_4):...
    def Invoke(self, sender: object, e: AsyncCompletedEventArgs):...
class AsyncOperation(object):
    @property
    def SynchronizationContext(self) -> _n_10_t_0:"""SynchronizationContext { get; } -> SynchronizationContext"""
    @property
    def UserSuppliedState(self) -> object:"""UserSuppliedState { get; } -> object"""
    def OperationCompleted(self):...
    def Post(self, d: _n_10_t_1, arg: object):...
    def PostOperationCompleted(self, d: _n_10_t_1, arg: object):...
class AsyncOperationManager(object):
    @property
    def SynchronizationContext(self) -> _n_10_t_0:"""SynchronizationContext { get; set; } -> SynchronizationContext"""
    @staticmethod
    def CreateOperation(userSuppliedState: object) -> AsyncOperation:...
class AttributeCollection(_n_1_t_0, typing.Iterable[_n_0_t_6]):
    Empty: int
    @property
    def Item(self) -> _n_0_t_6:"""Item { get; } -> Attribute"""
    def __init__(self, attributes: _n_0_t_11[_n_0_t_6]) -> AttributeCollection:...
    def Contains(self, attributes: _n_0_t_11[_n_0_t_6]) -> bool:...
    def Contains(self, attribute: _n_0_t_6) -> bool:...
    @staticmethod
    def FromExisting(existing: AttributeCollection, newAttributes: _n_0_t_11[_n_0_t_6]) -> AttributeCollection:...
    def Matches(self, attributes: _n_0_t_11[_n_0_t_6]) -> bool:...
    def Matches(self, attribute: _n_0_t_6) -> bool:...
class AttributeProviderAttribute(_n_0_t_6, _n_8_t_0):
    @property
    def PropertyName(self) -> str:"""PropertyName { get; } -> str"""
    @property
    def TypeName(self) -> str:"""TypeName { get; } -> str"""
    def __init__(self, type: _n_0_t_9) -> AttributeProviderAttribute:...
    def __init__(self, typeName: str, propertyName: str) -> AttributeProviderAttribute:...
    def __init__(self, typeName: str) -> AttributeProviderAttribute:...
class BackgroundWorker(Component, IComponent):
    @property
    def CancellationPending(self) -> bool:"""CancellationPending { get; } -> bool"""
    @property
    def IsBusy(self) -> bool:"""IsBusy { get; } -> bool"""
    @property
    def WorkerReportsProgress(self) -> bool:"""WorkerReportsProgress { get; set; } -> bool"""
    @property
    def WorkerSupportsCancellation(self) -> bool:"""WorkerSupportsCancellation { get; set; } -> bool"""
    @property
    def DoWork(self) -> DoWorkEventHandler:
        """DoWork Event: DoWorkEventHandler"""
    @property
    def ProgressChanged(self) -> ProgressChangedEventHandler:
        """ProgressChanged Event: ProgressChangedEventHandler"""
    @property
    def RunWorkerCompleted(self) -> RunWorkerCompletedEventHandler:
        """RunWorkerCompleted Event: RunWorkerCompletedEventHandler"""
    def __init__(self) -> BackgroundWorker:...
    def CancelAsync(self):...
    def ReportProgress(self, percentProgress: int, userState: object):...
    def ReportProgress(self, percentProgress: int):...
    def RunWorkerAsync(self, argument: object):...
    def RunWorkerAsync(self):...
class BaseNumberConverter(TypeConverter):
    pass
class BindableAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    No: int
    Yes: int
    @property
    def Bindable(self) -> bool:"""Bindable { get; } -> bool"""
    @property
    def Direction(self) -> BindingDirection:"""Direction { get; } -> BindingDirection"""
    def __init__(self, flags: BindableSupport, direction: BindingDirection) -> BindableAttribute:...
    def __init__(self, flags: BindableSupport) -> BindableAttribute:...
    def __init__(self, bindable: bool, direction: BindingDirection) -> BindableAttribute:...
    def __init__(self, bindable: bool) -> BindableAttribute:...
class BindableSupport(_n_0_t_12, _n_0_t_13, _n_0_t_14, _n_0_t_15):
    Default: int
    No: int
    value__: int
    Yes: int
class BindingDirection(_n_0_t_12, _n_0_t_13, _n_0_t_14, _n_0_t_15):
    OneWay: int
    TwoWay: int
    value__: int
class BindingList(_n_3_t_0[T], _n_2_t_0[T], _n_1_t_1, _n_2_t_1[T], IBindingList, ICancelAddNew, IRaiseItemChangedEvents, typing.Generic[T], typing.Iterable[T]):
    @property
    def RaiseListChangedEvents(self) -> bool:"""RaiseListChangedEvents { get; set; } -> bool"""
    @property
    def AddingNew(self) -> AddingNewEventHandler:
        """AddingNew Event: AddingNewEventHandler"""
    def __init__(self, list: _n_2_t_0[T]) -> BindingList:...
    def __init__(self) -> BindingList:...
    def ResetBindings(self):...
    def ResetItem(self, position: int):...
class BooleanConverter(TypeConverter):
    def __init__(self) -> BooleanConverter:...
class BrowsableAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    No: int
    Yes: int
    @property
    def Browsable(self) -> bool:"""Browsable { get; } -> bool"""
    def __init__(self, browsable: bool) -> BrowsableAttribute:...
class ByteConverter(BaseNumberConverter):
    def __init__(self) -> ByteConverter:...
class CancelEventArgs(_n_0_t_0):
    @property
    def Cancel(self) -> bool:"""Cancel { get; set; } -> bool"""
    def __init__(self, cancel: bool) -> CancelEventArgs:...
    def __init__(self) -> CancelEventArgs:...
class CancelEventHandler(_n_0_t_1, _n_0_t_2, _n_9_t_0):
    def __init__(self, object: object, method: _n_0_t_3) -> CancelEventHandler:...
    def BeginInvoke(self, sender: object, e: CancelEventArgs, callback: _n_0_t_5, object: object) -> _n_0_t_4:...
    def EndInvoke(self, result: _n_0_t_4):...
    def Invoke(self, sender: object, e: CancelEventArgs):...
class CategoryAttribute(_n_0_t_6, _n_8_t_0):
    @property
    def Action(self) -> CategoryAttribute:"""Action { get; } -> CategoryAttribute"""
    @property
    def Appearance(self) -> CategoryAttribute:"""Appearance { get; } -> CategoryAttribute"""
    @property
    def Asynchronous(self) -> CategoryAttribute:"""Asynchronous { get; } -> CategoryAttribute"""
    @property
    def Behavior(self) -> CategoryAttribute:"""Behavior { get; } -> CategoryAttribute"""
    @property
    def Category(self) -> str:"""Category { get; } -> str"""
    @property
    def Data(self) -> CategoryAttribute:"""Data { get; } -> CategoryAttribute"""
    @property
    def Default(self) -> CategoryAttribute:"""Default { get; } -> CategoryAttribute"""
    @property
    def Design(self) -> CategoryAttribute:"""Design { get; } -> CategoryAttribute"""
    @property
    def DragDrop(self) -> CategoryAttribute:"""DragDrop { get; } -> CategoryAttribute"""
    @property
    def Focus(self) -> CategoryAttribute:"""Focus { get; } -> CategoryAttribute"""
    @property
    def Format(self) -> CategoryAttribute:"""Format { get; } -> CategoryAttribute"""
    @property
    def Key(self) -> CategoryAttribute:"""Key { get; } -> CategoryAttribute"""
    @property
    def Layout(self) -> CategoryAttribute:"""Layout { get; } -> CategoryAttribute"""
    @property
    def Mouse(self) -> CategoryAttribute:"""Mouse { get; } -> CategoryAttribute"""
    @property
    def WindowStyle(self) -> CategoryAttribute:"""WindowStyle { get; } -> CategoryAttribute"""
    def __init__(self, category: str) -> CategoryAttribute:...
    def __init__(self) -> CategoryAttribute:...
class CharConverter(TypeConverter):
    def __init__(self) -> CharConverter:...
class CollectionChangeAction(_n_0_t_12, _n_0_t_13, _n_0_t_14, _n_0_t_15):
    Add: int
    Refresh: int
    Remove: int
    value__: int
class CollectionChangeEventArgs(_n_0_t_0):
    @property
    def Action(self) -> CollectionChangeAction:"""Action { get; } -> CollectionChangeAction"""
    @property
    def Element(self) -> object:"""Element { get; } -> object"""
    def __init__(self, action: CollectionChangeAction, element: object) -> CollectionChangeEventArgs:...
class CollectionChangeEventHandler(_n_0_t_1, _n_0_t_2, _n_9_t_0):
    def __init__(self, object: object, method: _n_0_t_3) -> CollectionChangeEventHandler:...
    def BeginInvoke(self, sender: object, e: CollectionChangeEventArgs, callback: _n_0_t_5, object: object) -> _n_0_t_4:...
    def EndInvoke(self, result: _n_0_t_4):...
    def Invoke(self, sender: object, e: CollectionChangeEventArgs):...
class CollectionConverter(TypeConverter):
    def __init__(self) -> CollectionConverter:...
class ComplexBindingPropertiesAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    @property
    def DataMember(self) -> str:"""DataMember { get; } -> str"""
    @property
    def DataSource(self) -> str:"""DataSource { get; } -> str"""
    def __init__(self, dataSource: str, dataMember: str) -> ComplexBindingPropertiesAttribute:...
    def __init__(self, dataSource: str) -> ComplexBindingPropertiesAttribute:...
    def __init__(self) -> ComplexBindingPropertiesAttribute:...
class Component(_n_0_t_16, IComponent):
    @property
    def Container(self) -> IContainer:"""Container { get; } -> IContainer"""
    def __init__(self) -> Component:...
class ComponentCollection(_n_1_t_2, _n_1_t_0, typing.Iterable[IComponent]):
    @property
    def Item(self) -> IComponent:"""Item { get; } -> IComponent"""
    def __init__(self, components: _n_0_t_11[IComponent]) -> ComponentCollection:...
class ComponentConverter(ReferenceConverter):
    def __init__(self, type: _n_0_t_9) -> ComponentConverter:...
class ComponentEditor(object):
    def EditComponent(self, context: ITypeDescriptorContext, component: object) -> bool:...
    def EditComponent(self, component: object) -> bool:...
class ComponentResourceManager(_n_7_t_0):
    def __init__(self, t: _n_0_t_9) -> ComponentResourceManager:...
    def __init__(self) -> ComponentResourceManager:...
    def ApplyResources(self, value: object, objectName: str, culture: _n_5_t_0):...
    def ApplyResources(self, value: object, objectName: str):...
class Container(IContainer):
    def __init__(self) -> Container:...
class ContainerFilterService(object):
    def FilterComponents(self, components: ComponentCollection) -> ComponentCollection:...
class CultureInfoConverter(TypeConverter):
    def __init__(self) -> CultureInfoConverter:...
class CustomTypeDescriptor(ICustomTypeDescriptor):
    pass
class DataErrorsChangedEventArgs(_n_0_t_0):
    @property
    def PropertyName(self) -> str:"""PropertyName { get; } -> str"""
    def __init__(self, propertyName: str) -> DataErrorsChangedEventArgs:...
class DataObjectAttribute(_n_0_t_6, _n_8_t_0):
    DataObject: int
    Default: int
    NonDataObject: int
    @property
    def IsDataObject(self) -> bool:"""IsDataObject { get; } -> bool"""
    def __init__(self, isDataObject: bool) -> DataObjectAttribute:...
    def __init__(self) -> DataObjectAttribute:...
class DataObjectFieldAttribute(_n_0_t_6, _n_8_t_0):
    @property
    def IsIdentity(self) -> bool:"""IsIdentity { get; } -> bool"""
    @property
    def IsNullable(self) -> bool:"""IsNullable { get; } -> bool"""
    @property
    def Length(self) -> int:"""Length { get; } -> int"""
    @property
    def PrimaryKey(self) -> bool:"""PrimaryKey { get; } -> bool"""
    def __init__(self, primaryKey: bool, isIdentity: bool, isNullable: bool, length: int) -> DataObjectFieldAttribute:...
    def __init__(self, primaryKey: bool, isIdentity: bool, isNullable: bool) -> DataObjectFieldAttribute:...
    def __init__(self, primaryKey: bool, isIdentity: bool) -> DataObjectFieldAttribute:...
    def __init__(self, primaryKey: bool) -> DataObjectFieldAttribute:...
class DataObjectMethodAttribute(_n_0_t_6, _n_8_t_0):
    @property
    def IsDefault(self) -> bool:"""IsDefault { get; } -> bool"""
    @property
    def MethodType(self) -> DataObjectMethodType:"""MethodType { get; } -> DataObjectMethodType"""
    def __init__(self, methodType: DataObjectMethodType, isDefault: bool) -> DataObjectMethodAttribute:...
    def __init__(self, methodType: DataObjectMethodType) -> DataObjectMethodAttribute:...
class DataObjectMethodType(_n_0_t_12, _n_0_t_13, _n_0_t_14, _n_0_t_15):
    Delete: int
    Fill: int
    Insert: int
    Select: int
    Update: int
    value__: int
class DateTimeConverter(TypeConverter):
    def __init__(self) -> DateTimeConverter:...
class DateTimeOffsetConverter(TypeConverter):
    def __init__(self) -> DateTimeOffsetConverter:...
class DecimalConverter(BaseNumberConverter):
    def __init__(self) -> DecimalConverter:...
class DefaultBindingPropertyAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    @property
    def Name(self) -> str:"""Name { get; } -> str"""
    def __init__(self, name: str) -> DefaultBindingPropertyAttribute:...
    def __init__(self) -> DefaultBindingPropertyAttribute:...
class DefaultEventAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    @property
    def Name(self) -> str:"""Name { get; } -> str"""
    def __init__(self, name: str) -> DefaultEventAttribute:...
class DefaultPropertyAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    @property
    def Name(self) -> str:"""Name { get; } -> str"""
    def __init__(self, name: str) -> DefaultPropertyAttribute:...
class DefaultValueAttribute(_n_0_t_6, _n_8_t_0):
    @property
    def Value(self) -> object:"""Value { get; } -> object"""
    def __init__(self, value: object) -> DefaultValueAttribute:...
    def __init__(self, value: str) -> DefaultValueAttribute:...
    def __init__(self, value: bool) -> DefaultValueAttribute:...
    def __init__(self, value: float) -> DefaultValueAttribute:...
    def __init__(self, value: int) -> DefaultValueAttribute:...
    def __init__(self, value: _n_0_t_7) -> DefaultValueAttribute:...
    def __init__(self, value: _n_0_t_8) -> DefaultValueAttribute:...
    def __init__(self, type: _n_0_t_9, value: str) -> DefaultValueAttribute:...
class DescriptionAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    @property
    def Description(self) -> str:"""Description { get; } -> str"""
    def __init__(self, description: str) -> DescriptionAttribute:...
    def __init__(self) -> DescriptionAttribute:...
class DesignerAttribute(_n_0_t_6, _n_8_t_0):
    @property
    def DesignerBaseTypeName(self) -> str:"""DesignerBaseTypeName { get; } -> str"""
    @property
    def DesignerTypeName(self) -> str:"""DesignerTypeName { get; } -> str"""
    def __init__(self, designerType: _n_0_t_9, designerBaseType: _n_0_t_9) -> DesignerAttribute:...
    def __init__(self, designerTypeName: str, designerBaseType: _n_0_t_9) -> DesignerAttribute:...
    def __init__(self, designerTypeName: str, designerBaseTypeName: str) -> DesignerAttribute:...
    def __init__(self, designerType: _n_0_t_9) -> DesignerAttribute:...
    def __init__(self, designerTypeName: str) -> DesignerAttribute:...
class DesignerCategoryAttribute(_n_0_t_6, _n_8_t_0):
    Component: int
    Default: int
    Form: int
    Generic: int
    @property
    def Category(self) -> str:"""Category { get; } -> str"""
    def __init__(self, category: str) -> DesignerCategoryAttribute:...
    def __init__(self) -> DesignerCategoryAttribute:...
class DesignerSerializationVisibility(_n_0_t_12, _n_0_t_13, _n_0_t_14, _n_0_t_15):
    Content: int
    Hidden: int
    value__: int
    Visible: int
class DesignerSerializationVisibilityAttribute(_n_0_t_6, _n_8_t_0):
    Content: int
    Default: int
    Hidden: int
    Visible: int
    @property
    def Visibility(self) -> DesignerSerializationVisibility:"""Visibility { get; } -> DesignerSerializationVisibility"""
    def __init__(self, visibility: DesignerSerializationVisibility) -> DesignerSerializationVisibilityAttribute:...
class DesignOnlyAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    No: int
    Yes: int
    @property
    def IsDesignOnly(self) -> bool:"""IsDesignOnly { get; } -> bool"""
    def __init__(self, isDesignOnly: bool) -> DesignOnlyAttribute:...
class DesignTimeVisibleAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    No: int
    Yes: int
    @property
    def Visible(self) -> bool:"""Visible { get; } -> bool"""
    def __init__(self) -> DesignTimeVisibleAttribute:...
    def __init__(self, visible: bool) -> DesignTimeVisibleAttribute:...
class DisplayNameAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    @property
    def DisplayName(self) -> str:"""DisplayName { get; } -> str"""
    def __init__(self, displayName: str) -> DisplayNameAttribute:...
    def __init__(self) -> DisplayNameAttribute:...
class DoubleConverter(BaseNumberConverter):
    def __init__(self) -> DoubleConverter:...
class DoWorkEventArgs(CancelEventArgs):
    @property
    def Argument(self) -> object:"""Argument { get; } -> object"""
    @property
    def Result(self) -> object:"""Result { get; set; } -> object"""
    def __init__(self, argument: object) -> DoWorkEventArgs:...
class DoWorkEventHandler(_n_0_t_1, _n_0_t_2, _n_9_t_0):
    def __init__(self, object: object, method: _n_0_t_3) -> DoWorkEventHandler:...
    def BeginInvoke(self, sender: object, e: DoWorkEventArgs, callback: _n_0_t_5, object: object) -> _n_0_t_4:...
    def EndInvoke(self, result: _n_0_t_4):...
    def Invoke(self, sender: object, e: DoWorkEventArgs):...
class EditorAttribute(_n_0_t_6, _n_8_t_0):
    @property
    def EditorBaseTypeName(self) -> str:"""EditorBaseTypeName { get; } -> str"""
    @property
    def EditorTypeName(self) -> str:"""EditorTypeName { get; } -> str"""
    def __init__(self, type: _n_0_t_9, baseType: _n_0_t_9) -> EditorAttribute:...
    def __init__(self, typeName: str, baseType: _n_0_t_9) -> EditorAttribute:...
    def __init__(self, typeName: str, baseTypeName: str) -> EditorAttribute:...
    def __init__(self) -> EditorAttribute:...
class EditorBrowsableAttribute(_n_0_t_6, _n_8_t_0):
    @property
    def State(self) -> EditorBrowsableState:"""State { get; } -> EditorBrowsableState"""
    def __init__(self) -> EditorBrowsableAttribute:...
    def __init__(self, state: EditorBrowsableState) -> EditorBrowsableAttribute:...
class EditorBrowsableState(_n_0_t_12, _n_0_t_13, _n_0_t_14, _n_0_t_15):
    Advanced: int
    Always: int
    Never: int
    value__: int
class EnumConverter(TypeConverter):
    def __init__(self, type: _n_0_t_9) -> EnumConverter:...
class EventDescriptor(MemberDescriptor):
    @property
    def ComponentType(self) -> _n_0_t_9:"""ComponentType { get; } -> Type"""
    @property
    def EventType(self) -> _n_0_t_9:"""EventType { get; } -> Type"""
    @property
    def IsMulticast(self) -> bool:"""IsMulticast { get; } -> bool"""
    def AddEventHandler(self, component: object, value: _n_0_t_17):...
    def RemoveEventHandler(self, component: object, value: _n_0_t_17):...
class EventDescriptorCollection(_n_1_t_0, _n_1_t_1, typing.Iterable[EventDescriptor]):
    Empty: int
    def __init__(self, events: _n_0_t_11[EventDescriptor], readOnly: bool) -> EventDescriptorCollection:...
    def __init__(self, events: _n_0_t_11[EventDescriptor]) -> EventDescriptorCollection:...
    def Find(self, name: str, ignoreCase: bool) -> EventDescriptor:...
    def Sort(self, comparer: _n_1_t_3) -> EventDescriptorCollection:...
    def Sort(self, names: _n_0_t_11[str], comparer: _n_1_t_3) -> EventDescriptorCollection:...
    def Sort(self, names: _n_0_t_11[str]) -> EventDescriptorCollection:...
    def Sort(self) -> EventDescriptorCollection:...
class EventHandlerList(_n_0_t_18, typing.Iterable[_n_0_t_17]):
    @property
    def Item(self) -> _n_0_t_17:"""Item { get; set; } -> Delegate"""
    def __init__(self) -> EventHandlerList:...
    def AddHandler(self, key: object, value: _n_0_t_17):...
    def AddHandlers(self, listToAddFrom: EventHandlerList):...
    def RemoveHandler(self, key: object, value: _n_0_t_17):...
class ExpandableObjectConverter(TypeConverter):
    def __init__(self) -> ExpandableObjectConverter:...
class ExtenderProvidedPropertyAttribute(_n_0_t_6, _n_8_t_0):
    @property
    def ExtenderProperty(self) -> PropertyDescriptor:"""ExtenderProperty { get; } -> PropertyDescriptor"""
    @property
    def Provider(self) -> IExtenderProvider:"""Provider { get; } -> IExtenderProvider"""
    @property
    def ReceiverType(self) -> _n_0_t_9:"""ReceiverType { get; } -> Type"""
    def __init__(self) -> ExtenderProvidedPropertyAttribute:...
class GuidConverter(TypeConverter):
    def __init__(self) -> GuidConverter:...
class HandledEventArgs(_n_0_t_0):
    @property
    def Handled(self) -> bool:"""Handled { get; set; } -> bool"""
    def __init__(self, defaultHandledValue: bool) -> HandledEventArgs:...
    def __init__(self) -> HandledEventArgs:...
class HandledEventHandler(_n_0_t_1, _n_0_t_2, _n_9_t_0):
    def __init__(self, object: object, method: _n_0_t_3) -> HandledEventHandler:...
    def BeginInvoke(self, sender: object, e: HandledEventArgs, callback: _n_0_t_5, object: object) -> _n_0_t_4:...
    def EndInvoke(self, result: _n_0_t_4):...
    def Invoke(self, sender: object, e: HandledEventArgs):...
class IBindingList(_n_1_t_1):
    @property
    def AllowEdit(self) -> bool:"""AllowEdit { get; } -> bool"""
    @property
    def AllowNew(self) -> bool:"""AllowNew { get; } -> bool"""
    @property
    def AllowRemove(self) -> bool:"""AllowRemove { get; } -> bool"""
    @property
    def IsSorted(self) -> bool:"""IsSorted { get; } -> bool"""
    @property
    def SortDirection(self) -> ListSortDirection:"""SortDirection { get; } -> ListSortDirection"""
    @property
    def SortProperty(self) -> PropertyDescriptor:"""SortProperty { get; } -> PropertyDescriptor"""
    @property
    def SupportsChangeNotification(self) -> bool:"""SupportsChangeNotification { get; } -> bool"""
    @property
    def SupportsSearching(self) -> bool:"""SupportsSearching { get; } -> bool"""
    @property
    def SupportsSorting(self) -> bool:"""SupportsSorting { get; } -> bool"""
    @property
    def ListChanged(self) -> ListChangedEventHandler:
        """ListChanged Event: ListChangedEventHandler"""
    def AddIndex(self, property: PropertyDescriptor):...
    def AddNew(self) -> object:...
    def ApplySort(self, property: PropertyDescriptor, direction: ListSortDirection):...
    def Find(self, property: PropertyDescriptor, key: object) -> int:...
    def RemoveIndex(self, property: PropertyDescriptor):...
    def RemoveSort(self):...
class IBindingListView(IBindingList):
    @property
    def Filter(self) -> str:"""Filter { get; set; } -> str"""
    @property
    def SortDescriptions(self) -> ListSortDescriptionCollection:"""SortDescriptions { get; } -> ListSortDescriptionCollection"""
    @property
    def SupportsAdvancedSorting(self) -> bool:"""SupportsAdvancedSorting { get; } -> bool"""
    @property
    def SupportsFiltering(self) -> bool:"""SupportsFiltering { get; } -> bool"""
    def RemoveFilter(self):...
class ICancelAddNew():
    def CancelNew(self, itemIndex: int):...
    def EndNew(self, itemIndex: int):...
class IChangeTracking():
    @property
    def IsChanged(self) -> bool:"""IsChanged { get; } -> bool"""
    def AcceptChanges(self):...
class IComNativeDescriptorHandler():
    def GetAttributes(self, component: object) -> AttributeCollection:...
    def GetClassName(self, component: object) -> str:...
    def GetConverter(self, component: object) -> TypeConverter:...
    def GetDefaultEvent(self, component: object) -> EventDescriptor:...
    def GetDefaultProperty(self, component: object) -> PropertyDescriptor:...
    def GetEditor(self, component: object, baseEditorType: _n_0_t_9) -> object:...
    def GetEvents(self, component: object, attributes: _n_0_t_11[_n_0_t_6]) -> EventDescriptorCollection:...
    def GetEvents(self, component: object) -> EventDescriptorCollection:...
    def GetName(self, component: object) -> str:...
    def GetProperties(self, component: object, attributes: _n_0_t_11[_n_0_t_6]) -> PropertyDescriptorCollection:...
    def GetPropertyValue(self, component: object, dispid: int, success: bool) -> object:...
    def GetPropertyValue(self, component: object, propertyName: str, success: bool) -> object:...
class IComponent(_n_0_t_18):
    @property
    def Site(self) -> ISite:"""Site { get; set; } -> ISite"""
    @property
    def Disposed(self) -> _n_0_t_19:
        """Disposed Event: EventHandler"""
class IContainer(_n_0_t_18):
    @property
    def Components(self) -> ComponentCollection:"""Components { get; } -> ComponentCollection"""
    def Add(self, component: IComponent, name: str):...
    def Add(self, component: IComponent):...
    def Remove(self, component: IComponent):...
class ICustomTypeDescriptor():
    def GetAttributes(self) -> AttributeCollection:...
    def GetClassName(self) -> str:...
    def GetComponentName(self) -> str:...
    def GetConverter(self) -> TypeConverter:...
    def GetDefaultEvent(self) -> EventDescriptor:...
    def GetDefaultProperty(self) -> PropertyDescriptor:...
    def GetEditor(self, editorBaseType: _n_0_t_9) -> object:...
    def GetEvents(self, attributes: _n_0_t_11[_n_0_t_6]) -> EventDescriptorCollection:...
    def GetEvents(self) -> EventDescriptorCollection:...
    def GetProperties(self, attributes: _n_0_t_11[_n_0_t_6]) -> PropertyDescriptorCollection:...
    def GetProperties(self) -> PropertyDescriptorCollection:...
    def GetPropertyOwner(self, pd: PropertyDescriptor) -> object:...
class IDataErrorInfo(typing.Iterable[str]):
    @property
    def Error(self) -> str:"""Error { get; } -> str"""
    @property
    def Item(self) -> str:"""Item { get; } -> str"""
class IEditableObject():
    def BeginEdit(self):...
    def CancelEdit(self):...
    def EndEdit(self):...
class IExtenderProvider():
    def CanExtend(self, extendee: object) -> bool:...
class IIntellisenseBuilder():
    @property
    def Name(self) -> str:"""Name { get; } -> str"""
    def Show(self, language: str, value: str, newValue: str) -> bool:...
class IListSource():
    @property
    def ContainsListCollection(self) -> bool:"""ContainsListCollection { get; } -> bool"""
    def GetList(self) -> _n_1_t_1:...
class ImmutableObjectAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    No: int
    Yes: int
    @property
    def Immutable(self) -> bool:"""Immutable { get; } -> bool"""
    def __init__(self, immutable: bool) -> ImmutableObjectAttribute:...
class INestedContainer(IContainer):
    @property
    def Owner(self) -> IComponent:"""Owner { get; } -> IComponent"""
class INestedSite(ISite):
    @property
    def FullName(self) -> str:"""FullName { get; } -> str"""
class InheritanceAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    Inherited: int
    InheritedReadOnly: int
    NotInherited: int
    @property
    def InheritanceLevel(self) -> InheritanceLevel:"""InheritanceLevel { get; } -> InheritanceLevel"""
    def __init__(self, inheritanceLevel: InheritanceLevel) -> InheritanceAttribute:...
    def __init__(self) -> InheritanceAttribute:...
class InheritanceLevel(_n_0_t_12, _n_0_t_13, _n_0_t_14, _n_0_t_15):
    Inherited: int
    InheritedReadOnly: int
    NotInherited: int
    value__: int
class InitializationEventAttribute(_n_0_t_6, _n_8_t_0):
    @property
    def EventName(self) -> str:"""EventName { get; } -> str"""
    def __init__(self, eventName: str) -> InitializationEventAttribute:...
class INotifyDataErrorInfo():
    @property
    def HasErrors(self) -> bool:"""HasErrors { get; } -> bool"""
    @property
    def ErrorsChanged(self) -> _n_0_t_19[DataErrorsChangedEventArgs]:
        """ErrorsChanged Event: EventHandler"""
    def GetErrors(self, propertyName: str) -> _n_1_t_4:...
class INotifyPropertyChanged():
    @property
    def PropertyChanged(self) -> PropertyChangedEventHandler:
        """PropertyChanged Event: PropertyChangedEventHandler"""
class INotifyPropertyChanging():
    @property
    def PropertyChanging(self) -> PropertyChangingEventHandler:
        """PropertyChanging Event: PropertyChangingEventHandler"""
class InstallerTypeAttribute(_n_0_t_6, _n_8_t_0):
    @property
    def InstallerType(self) -> _n_0_t_9:"""InstallerType { get; } -> Type"""
    def __init__(self, typeName: str) -> InstallerTypeAttribute:...
    def __init__(self, installerType: _n_0_t_9) -> InstallerTypeAttribute:...
class InstanceCreationEditor(object):
    @property
    def Text(self) -> str:"""Text { get; } -> str"""
    def CreateInstance(self, context: ITypeDescriptorContext, instanceType: _n_0_t_9) -> object:...
class Int16Converter(BaseNumberConverter):
    def __init__(self) -> Int16Converter:...
class Int32Converter(BaseNumberConverter):
    def __init__(self) -> Int32Converter:...
class Int64Converter(BaseNumberConverter):
    def __init__(self) -> Int64Converter:...
class InvalidAsynchronousStateException(_n_0_t_20, _n_9_t_0, _n_8_t_1):
    def __init__(self, message: str, innerException: _n_0_t_10) -> InvalidAsynchronousStateException:...
    def __init__(self, message: str) -> InvalidAsynchronousStateException:...
    def __init__(self) -> InvalidAsynchronousStateException:...
class InvalidEnumArgumentException(_n_0_t_20, _n_9_t_0, _n_8_t_1):
    def __init__(self, argumentName: str, invalidValue: int, enumClass: _n_0_t_9) -> InvalidEnumArgumentException:...
    def __init__(self, message: str, innerException: _n_0_t_10) -> InvalidEnumArgumentException:...
    def __init__(self, message: str) -> InvalidEnumArgumentException:...
    def __init__(self) -> InvalidEnumArgumentException:...
class IRaiseItemChangedEvents():
    @property
    def RaisesItemChangedEvents(self) -> bool:"""RaisesItemChangedEvents { get; } -> bool"""
class IRevertibleChangeTracking(IChangeTracking):
    def RejectChanges(self):...
class ISite(_n_0_t_21):
    @property
    def Component(self) -> IComponent:"""Component { get; } -> IComponent"""
    @property
    def Container(self) -> IContainer:"""Container { get; } -> IContainer"""
    @property
    def DesignMode(self) -> bool:"""DesignMode { get; } -> bool"""
    @property
    def Name(self) -> str:"""Name { get; set; } -> str"""
class ISupportInitialize():
    def BeginInit(self):...
    def EndInit(self):...
class ISupportInitializeNotification(ISupportInitialize):
    @property
    def IsInitialized(self) -> bool:"""IsInitialized { get; } -> bool"""
    @property
    def Initialized(self) -> _n_0_t_19:
        """Initialized Event: EventHandler"""
class ISynchronizeInvoke():
    @property
    def InvokeRequired(self) -> bool:"""InvokeRequired { get; } -> bool"""
    def BeginInvoke(self, method: _n_0_t_17, args: _n_0_t_11[object]) -> _n_0_t_4:...
    def EndInvoke(self, result: _n_0_t_4) -> object:...
    def Invoke(self, method: _n_0_t_17, args: _n_0_t_11[object]) -> object:...
class ITypeDescriptorContext(_n_0_t_21):
    @property
    def Container(self) -> IContainer:"""Container { get; } -> IContainer"""
    @property
    def Instance(self) -> object:"""Instance { get; } -> object"""
    @property
    def PropertyDescriptor(self) -> PropertyDescriptor:"""PropertyDescriptor { get; } -> PropertyDescriptor"""
    def OnComponentChanged(self):...
    def OnComponentChanging(self) -> bool:...
class ITypedList():
    def GetItemProperties(self, listAccessors: _n_0_t_11[PropertyDescriptor]) -> PropertyDescriptorCollection:...
    def GetListName(self, listAccessors: _n_0_t_11[PropertyDescriptor]) -> str:...
class License(_n_0_t_18):
    @property
    def LicenseKey(self) -> str:"""LicenseKey { get; } -> str"""
class LicenseContext(_n_0_t_21):
    @property
    def UsageMode(self) -> LicenseUsageMode:"""UsageMode { get; } -> LicenseUsageMode"""
    def __init__(self) -> LicenseContext:...
    def GetSavedLicenseKey(self, type: _n_0_t_9, resourceAssembly: _n_6_t_0) -> str:...
    def SetSavedLicenseKey(self, type: _n_0_t_9, key: str):...
class LicenseException(_n_0_t_22, _n_9_t_0, _n_8_t_1):
    @property
    def LicensedType(self) -> _n_0_t_9:"""LicensedType { get; } -> Type"""
    def __init__(self, type: _n_0_t_9, instance: object, message: str, innerException: _n_0_t_10) -> LicenseException:...
    def __init__(self, type: _n_0_t_9, instance: object, message: str) -> LicenseException:...
    def __init__(self, type: _n_0_t_9, instance: object) -> LicenseException:...
    def __init__(self, type: _n_0_t_9) -> LicenseException:...
class LicenseManager(object):
    @property
    def CurrentContext(self) -> LicenseContext:"""CurrentContext { get; set; } -> LicenseContext"""
    @property
    def UsageMode(self) -> LicenseUsageMode:"""UsageMode { get; } -> LicenseUsageMode"""
    @staticmethod
    def CreateWithContext(type: _n_0_t_9, creationContext: LicenseContext, args: _n_0_t_11[object]) -> object:...
    @staticmethod
    def CreateWithContext(type: _n_0_t_9, creationContext: LicenseContext) -> object:...
    @staticmethod
    def IsLicensed(type: _n_0_t_9) -> bool:...
    @staticmethod
    def IsValid(type: _n_0_t_9, instance: object, license: License) -> bool:...
    @staticmethod
    def IsValid(type: _n_0_t_9) -> bool:...
    @staticmethod
    def LockContext(contextUser: object):...
    @staticmethod
    def UnlockContext(contextUser: object):...
    @staticmethod
    def Validate(type: _n_0_t_9, instance: object) -> License:...
    @staticmethod
    def Validate(type: _n_0_t_9):...
class LicenseProvider(object):
    def GetLicense(self, context: LicenseContext, type: _n_0_t_9, instance: object, allowExceptions: bool) -> License:...
class LicenseProviderAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    @property
    def LicenseProvider(self) -> _n_0_t_9:"""LicenseProvider { get; } -> Type"""
    def __init__(self, type: _n_0_t_9) -> LicenseProviderAttribute:...
    def __init__(self, typeName: str) -> LicenseProviderAttribute:...
    def __init__(self) -> LicenseProviderAttribute:...
class LicenseUsageMode(_n_0_t_12, _n_0_t_13, _n_0_t_14, _n_0_t_15):
    Designtime: int
    Runtime: int
    value__: int
class LicFileLicenseProvider(LicenseProvider):
    def __init__(self) -> LicFileLicenseProvider:...
class ListBindableAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    No: int
    Yes: int
    @property
    def ListBindable(self) -> bool:"""ListBindable { get; } -> bool"""
    def __init__(self, flags: BindableSupport) -> ListBindableAttribute:...
    def __init__(self, listBindable: bool) -> ListBindableAttribute:...
class ListChangedEventArgs(_n_0_t_0):
    @property
    def ListChangedType(self) -> ListChangedType:"""ListChangedType { get; } -> ListChangedType"""
    @property
    def NewIndex(self) -> int:"""NewIndex { get; } -> int"""
    @property
    def OldIndex(self) -> int:"""OldIndex { get; } -> int"""
    @property
    def PropertyDescriptor(self) -> PropertyDescriptor:"""PropertyDescriptor { get; } -> PropertyDescriptor"""
    def __init__(self, listChangedType: ListChangedType, newIndex: int, oldIndex: int) -> ListChangedEventArgs:...
    def __init__(self, listChangedType: ListChangedType, propDesc: PropertyDescriptor) -> ListChangedEventArgs:...
    def __init__(self, listChangedType: ListChangedType, newIndex: int, propDesc: PropertyDescriptor) -> ListChangedEventArgs:...
    def __init__(self, listChangedType: ListChangedType, newIndex: int) -> ListChangedEventArgs:...
class ListChangedEventHandler(_n_0_t_1, _n_0_t_2, _n_9_t_0):
    def __init__(self, object: object, method: _n_0_t_3) -> ListChangedEventHandler:...
    def BeginInvoke(self, sender: object, e: ListChangedEventArgs, callback: _n_0_t_5, object: object) -> _n_0_t_4:...
    def EndInvoke(self, result: _n_0_t_4):...
    def Invoke(self, sender: object, e: ListChangedEventArgs):...
class ListChangedType(_n_0_t_12, _n_0_t_13, _n_0_t_14, _n_0_t_15):
    ItemAdded: int
    ItemChanged: int
    ItemDeleted: int
    ItemMoved: int
    PropertyDescriptorAdded: int
    PropertyDescriptorChanged: int
    PropertyDescriptorDeleted: int
    Reset: int
    value__: int
class ListSortDescription(object):
    @property
    def PropertyDescriptor(self) -> PropertyDescriptor:"""PropertyDescriptor { get; set; } -> PropertyDescriptor"""
    @property
    def SortDirection(self) -> ListSortDirection:"""SortDirection { get; set; } -> ListSortDirection"""
    def __init__(self, property: PropertyDescriptor, direction: ListSortDirection) -> ListSortDescription:...
class ListSortDescriptionCollection(_n_1_t_1, typing.Iterable[ListSortDescription]):
    def __init__(self, sorts: _n_0_t_11[ListSortDescription]) -> ListSortDescriptionCollection:...
    def __init__(self) -> ListSortDescriptionCollection:...
class ListSortDirection(_n_0_t_12, _n_0_t_13, _n_0_t_14, _n_0_t_15):
    Ascending: int
    Descending: int
    value__: int
class LocalizableAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    No: int
    Yes: int
    @property
    def IsLocalizable(self) -> bool:"""IsLocalizable { get; } -> bool"""
    def __init__(self, isLocalizable: bool) -> LocalizableAttribute:...
class LookupBindingPropertiesAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    @property
    def DataSource(self) -> str:"""DataSource { get; } -> str"""
    @property
    def DisplayMember(self) -> str:"""DisplayMember { get; } -> str"""
    @property
    def LookupMember(self) -> str:"""LookupMember { get; } -> str"""
    @property
    def ValueMember(self) -> str:"""ValueMember { get; } -> str"""
    def __init__(self, dataSource: str, displayMember: str, valueMember: str, lookupMember: str) -> LookupBindingPropertiesAttribute:...
    def __init__(self) -> LookupBindingPropertiesAttribute:...
class MarshalByValueComponent(IComponent, _n_0_t_21):
    @property
    def Container(self) -> IContainer:"""Container { get; } -> IContainer"""
    @property
    def DesignMode(self) -> bool:"""DesignMode { get; } -> bool"""
    def __init__(self) -> MarshalByValueComponent:...
class MaskedTextProvider(_n_0_t_2, typing.Iterable[_n_0_t_8]):
    @property
    def AllowPromptAsInput(self) -> bool:"""AllowPromptAsInput { get; } -> bool"""
    @property
    def AsciiOnly(self) -> bool:"""AsciiOnly { get; } -> bool"""
    @property
    def AssignedEditPositionCount(self) -> int:"""AssignedEditPositionCount { get; } -> int"""
    @property
    def AvailableEditPositionCount(self) -> int:"""AvailableEditPositionCount { get; } -> int"""
    @property
    def Culture(self) -> _n_5_t_0:"""Culture { get; } -> CultureInfo"""
    @property
    def DefaultPasswordChar(self) -> _n_0_t_8:"""DefaultPasswordChar { get; } -> Char"""
    @property
    def EditPositionCount(self) -> int:"""EditPositionCount { get; } -> int"""
    @property
    def EditPositions(self) -> _n_1_t_5:"""EditPositions { get; } -> IEnumerator"""
    @property
    def IncludeLiterals(self) -> bool:"""IncludeLiterals { get; set; } -> bool"""
    @property
    def IncludePrompt(self) -> bool:"""IncludePrompt { get; set; } -> bool"""
    @property
    def InvalidIndex(self) -> int:"""InvalidIndex { get; } -> int"""
    @property
    def IsPassword(self) -> bool:"""IsPassword { get; set; } -> bool"""
    @property
    def Item(self) -> _n_0_t_8:"""Item { get; } -> Char"""
    @property
    def LastAssignedPosition(self) -> int:"""LastAssignedPosition { get; } -> int"""
    @property
    def Length(self) -> int:"""Length { get; } -> int"""
    @property
    def Mask(self) -> str:"""Mask { get; } -> str"""
    @property
    def MaskCompleted(self) -> bool:"""MaskCompleted { get; } -> bool"""
    @property
    def MaskFull(self) -> bool:"""MaskFull { get; } -> bool"""
    @property
    def PasswordChar(self) -> _n_0_t_8:"""PasswordChar { get; set; } -> Char"""
    @property
    def PromptChar(self) -> _n_0_t_8:"""PromptChar { get; set; } -> Char"""
    @property
    def ResetOnPrompt(self) -> bool:"""ResetOnPrompt { get; set; } -> bool"""
    @property
    def ResetOnSpace(self) -> bool:"""ResetOnSpace { get; set; } -> bool"""
    @property
    def SkipLiterals(self) -> bool:"""SkipLiterals { get; set; } -> bool"""
    def __init__(self, mask: str, culture: _n_5_t_0, allowPromptAsInput: bool, promptChar: _n_0_t_8, passwordChar: _n_0_t_8, restrictToAscii: bool) -> MaskedTextProvider:...
    def __init__(self, mask: str, culture: _n_5_t_0, passwordChar: _n_0_t_8, allowPromptAsInput: bool) -> MaskedTextProvider:...
    def __init__(self, mask: str, passwordChar: _n_0_t_8, allowPromptAsInput: bool) -> MaskedTextProvider:...
    def __init__(self, mask: str, culture: _n_5_t_0, restrictToAscii: bool) -> MaskedTextProvider:...
    def __init__(self, mask: str, culture: _n_5_t_0) -> MaskedTextProvider:...
    def __init__(self, mask: str, restrictToAscii: bool) -> MaskedTextProvider:...
    def __init__(self, mask: str) -> MaskedTextProvider:...
    def Add(self, input: str, testPosition: int, resultHint: MaskedTextResultHint) -> bool:...
    def Add(self, input: str) -> bool:...
    def Add(self, input: _n_0_t_8, testPosition: int, resultHint: MaskedTextResultHint) -> bool:...
    def Add(self, input: _n_0_t_8) -> bool:...
    def Clear(self, resultHint: MaskedTextResultHint):...
    def Clear(self):...
    def FindAssignedEditPositionFrom(self, position: int, direction: bool) -> int:...
    def FindAssignedEditPositionInRange(self, startPosition: int, endPosition: int, direction: bool) -> int:...
    def FindEditPositionFrom(self, position: int, direction: bool) -> int:...
    def FindEditPositionInRange(self, startPosition: int, endPosition: int, direction: bool) -> int:...
    def FindNonEditPositionFrom(self, position: int, direction: bool) -> int:...
    def FindNonEditPositionInRange(self, startPosition: int, endPosition: int, direction: bool) -> int:...
    def FindUnassignedEditPositionFrom(self, position: int, direction: bool) -> int:...
    def FindUnassignedEditPositionInRange(self, startPosition: int, endPosition: int, direction: bool) -> int:...
    @staticmethod
    def GetOperationResultFromHint(hint: MaskedTextResultHint) -> bool:...
    def InsertAt(self, input: str, position: int, testPosition: int, resultHint: MaskedTextResultHint) -> bool:...
    def InsertAt(self, input: str, position: int) -> bool:...
    def InsertAt(self, input: _n_0_t_8, position: int, testPosition: int, resultHint: MaskedTextResultHint) -> bool:...
    def InsertAt(self, input: _n_0_t_8, position: int) -> bool:...
    def IsAvailablePosition(self, position: int) -> bool:...
    def IsEditPosition(self, position: int) -> bool:...
    @staticmethod
    def IsValidInputChar(c: _n_0_t_8) -> bool:...
    @staticmethod
    def IsValidMaskChar(c: _n_0_t_8) -> bool:...
    @staticmethod
    def IsValidPasswordChar(c: _n_0_t_8) -> bool:...
    def Remove(self, testPosition: int, resultHint: MaskedTextResultHint) -> bool:...
    def Remove(self) -> bool:...
    def RemoveAt(self, startPosition: int, endPosition: int, testPosition: int, resultHint: MaskedTextResultHint) -> bool:...
    def RemoveAt(self, startPosition: int, endPosition: int) -> bool:...
    def RemoveAt(self, position: int) -> bool:...
    def Replace(self, input: str, startPosition: int, endPosition: int, testPosition: int, resultHint: MaskedTextResultHint) -> bool:...
    def Replace(self, input: str, position: int, testPosition: int, resultHint: MaskedTextResultHint) -> bool:...
    def Replace(self, input: str, position: int) -> bool:...
    def Replace(self, input: _n_0_t_8, startPosition: int, endPosition: int, testPosition: int, resultHint: MaskedTextResultHint) -> bool:...
    def Replace(self, input: _n_0_t_8, position: int, testPosition: int, resultHint: MaskedTextResultHint) -> bool:...
    def Replace(self, input: _n_0_t_8, position: int) -> bool:...
    def Set(self, input: str, testPosition: int, resultHint: MaskedTextResultHint) -> bool:...
    def Set(self, input: str) -> bool:...
    def ToDisplayString(self) -> str:...
    def VerifyChar(self, input: _n_0_t_8, position: int, hint: MaskedTextResultHint) -> bool:...
    def VerifyEscapeChar(self, input: _n_0_t_8, position: int) -> bool:...
    def VerifyString(self, input: str, testPosition: int, resultHint: MaskedTextResultHint) -> bool:...
    def VerifyString(self, input: str) -> bool:...
class MaskedTextResultHint(_n_0_t_12, _n_0_t_13, _n_0_t_14, _n_0_t_15):
    AlphanumericCharacterExpected: int
    AsciiCharacterExpected: int
    CharacterEscaped: int
    DigitExpected: int
    InvalidInput: int
    LetterExpected: int
    NoEffect: int
    NonEditPosition: int
    PositionOutOfRange: int
    PromptCharNotAllowed: int
    SideEffect: int
    SignedDigitExpected: int
    Success: int
    UnavailableEditPosition: int
    Unknown: int
    value__: int
class MemberDescriptor(object):
    @property
    def Attributes(self) -> AttributeCollection:"""Attributes { get; } -> AttributeCollection"""
    @property
    def Category(self) -> str:"""Category { get; } -> str"""
    @property
    def Description(self) -> str:"""Description { get; } -> str"""
    @property
    def DesignTimeOnly(self) -> bool:"""DesignTimeOnly { get; } -> bool"""
    @property
    def DisplayName(self) -> str:"""DisplayName { get; } -> str"""
    @property
    def IsBrowsable(self) -> bool:"""IsBrowsable { get; } -> bool"""
    @property
    def Name(self) -> str:"""Name { get; } -> str"""
class MergablePropertyAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    No: int
    Yes: int
    @property
    def AllowMerge(self) -> bool:"""AllowMerge { get; } -> bool"""
    def __init__(self, allowMerge: bool) -> MergablePropertyAttribute:...
class MultilineStringConverter(TypeConverter):
    def __init__(self) -> MultilineStringConverter:...
class NestedContainer(Container, IContainer, INestedContainer):
    def __init__(self, owner: IComponent) -> NestedContainer:...
class NotifyParentPropertyAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    No: int
    Yes: int
    @property
    def NotifyParent(self) -> bool:"""NotifyParent { get; } -> bool"""
    def __init__(self, notifyParent: bool) -> NotifyParentPropertyAttribute:...
class NullableConverter(TypeConverter):
    @property
    def NullableType(self) -> _n_0_t_9:"""NullableType { get; } -> Type"""
    @property
    def UnderlyingType(self) -> _n_0_t_9:"""UnderlyingType { get; } -> Type"""
    @property
    def UnderlyingTypeConverter(self) -> TypeConverter:"""UnderlyingTypeConverter { get; } -> TypeConverter"""
    def __init__(self, type: _n_0_t_9) -> NullableConverter:...
class ParenthesizePropertyNameAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    @property
    def NeedParenthesis(self) -> bool:"""NeedParenthesis { get; } -> bool"""
    def __init__(self, needParenthesis: bool) -> ParenthesizePropertyNameAttribute:...
    def __init__(self) -> ParenthesizePropertyNameAttribute:...
class PasswordPropertyTextAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    No: int
    Yes: int
    @property
    def Password(self) -> bool:"""Password { get; } -> bool"""
    def __init__(self, password: bool) -> PasswordPropertyTextAttribute:...
    def __init__(self) -> PasswordPropertyTextAttribute:...
class ProgressChangedEventArgs(_n_0_t_0):
    @property
    def ProgressPercentage(self) -> int:"""ProgressPercentage { get; } -> int"""
    @property
    def UserState(self) -> object:"""UserState { get; } -> object"""
    def __init__(self, progressPercentage: int, userState: object) -> ProgressChangedEventArgs:...
class ProgressChangedEventHandler(_n_0_t_1, _n_0_t_2, _n_9_t_0):
    def __init__(self, object: object, method: _n_0_t_3) -> ProgressChangedEventHandler:...
    def BeginInvoke(self, sender: object, e: ProgressChangedEventArgs, callback: _n_0_t_5, object: object) -> _n_0_t_4:...
    def EndInvoke(self, result: _n_0_t_4):...
    def Invoke(self, sender: object, e: ProgressChangedEventArgs):...
class PropertyChangedEventArgs(_n_0_t_0):
    @property
    def PropertyName(self) -> str:"""PropertyName { get; } -> str"""
    def __init__(self, propertyName: str) -> PropertyChangedEventArgs:...
class PropertyChangedEventHandler(_n_0_t_1, _n_0_t_2, _n_9_t_0):
    def __init__(self, object: object, method: _n_0_t_3) -> PropertyChangedEventHandler:...
    def BeginInvoke(self, sender: object, e: PropertyChangedEventArgs, callback: _n_0_t_5, object: object) -> _n_0_t_4:...
    def EndInvoke(self, result: _n_0_t_4):...
    def Invoke(self, sender: object, e: PropertyChangedEventArgs):...
class PropertyChangingEventArgs(_n_0_t_0):
    @property
    def PropertyName(self) -> str:"""PropertyName { get; } -> str"""
    def __init__(self, propertyName: str) -> PropertyChangingEventArgs:...
class PropertyChangingEventHandler(_n_0_t_1, _n_0_t_2, _n_9_t_0):
    def __init__(self, object: object, method: _n_0_t_3) -> PropertyChangingEventHandler:...
    def BeginInvoke(self, sender: object, e: PropertyChangingEventArgs, callback: _n_0_t_5, object: object) -> _n_0_t_4:...
    def EndInvoke(self, result: _n_0_t_4):...
    def Invoke(self, sender: object, e: PropertyChangingEventArgs):...
class PropertyDescriptor(MemberDescriptor):
    @property
    def ComponentType(self) -> _n_0_t_9:"""ComponentType { get; } -> Type"""
    @property
    def Converter(self) -> TypeConverter:"""Converter { get; } -> TypeConverter"""
    @property
    def IsLocalizable(self) -> bool:"""IsLocalizable { get; } -> bool"""
    @property
    def IsReadOnly(self) -> bool:"""IsReadOnly { get; } -> bool"""
    @property
    def PropertyType(self) -> _n_0_t_9:"""PropertyType { get; } -> Type"""
    @property
    def SerializationVisibility(self) -> DesignerSerializationVisibility:"""SerializationVisibility { get; } -> DesignerSerializationVisibility"""
    @property
    def SupportsChangeEvents(self) -> bool:"""SupportsChangeEvents { get; } -> bool"""
    def AddValueChanged(self, component: object, handler: _n_0_t_19):...
    def CanResetValue(self, component: object) -> bool:...
    def GetChildProperties(self, instance: object, filter: _n_0_t_11[_n_0_t_6]) -> PropertyDescriptorCollection:...
    def GetChildProperties(self, instance: object) -> PropertyDescriptorCollection:...
    def GetChildProperties(self, filter: _n_0_t_11[_n_0_t_6]) -> PropertyDescriptorCollection:...
    def GetChildProperties(self) -> PropertyDescriptorCollection:...
    def GetEditor(self, editorBaseType: _n_0_t_9) -> object:...
    def GetValue(self, component: object) -> object:...
    def RemoveValueChanged(self, component: object, handler: _n_0_t_19):...
    def ResetValue(self, component: object):...
    def SetValue(self, component: object, value: object):...
    def ShouldSerializeValue(self, component: object) -> bool:...
class PropertyDescriptorCollection(_n_1_t_0, _n_1_t_1, _n_1_t_6, typing.Iterable[PropertyDescriptor]):
    Empty: int
    def __init__(self, properties: _n_0_t_11[PropertyDescriptor], readOnly: bool) -> PropertyDescriptorCollection:...
    def __init__(self, properties: _n_0_t_11[PropertyDescriptor]) -> PropertyDescriptorCollection:...
    def Find(self, name: str, ignoreCase: bool) -> PropertyDescriptor:...
    def Sort(self, comparer: _n_1_t_3) -> PropertyDescriptorCollection:...
    def Sort(self, names: _n_0_t_11[str], comparer: _n_1_t_3) -> PropertyDescriptorCollection:...
    def Sort(self, names: _n_0_t_11[str]) -> PropertyDescriptorCollection:...
    def Sort(self) -> PropertyDescriptorCollection:...
class PropertyTabAttribute(_n_0_t_6, _n_8_t_0):
    @property
    def TabClasses(self) -> _n_0_t_11[_n_0_t_9]:"""TabClasses { get; } -> Array"""
    @property
    def TabScopes(self) -> _n_0_t_11[PropertyTabScope]:"""TabScopes { get; } -> Array"""
    def __init__(self, tabClassName: str, tabScope: PropertyTabScope) -> PropertyTabAttribute:...
    def __init__(self, tabClass: _n_0_t_9, tabScope: PropertyTabScope) -> PropertyTabAttribute:...
    def __init__(self, tabClassName: str) -> PropertyTabAttribute:...
    def __init__(self, tabClass: _n_0_t_9) -> PropertyTabAttribute:...
    def __init__(self) -> PropertyTabAttribute:...
class PropertyTabScope(_n_0_t_12, _n_0_t_13, _n_0_t_14, _n_0_t_15):
    Component: int
    Document: int
    Global: int
    Static: int
    value__: int
class ProvidePropertyAttribute(_n_0_t_6, _n_8_t_0):
    @property
    def PropertyName(self) -> str:"""PropertyName { get; } -> str"""
    @property
    def ReceiverTypeName(self) -> str:"""ReceiverTypeName { get; } -> str"""
    def __init__(self, propertyName: str, receiverTypeName: str) -> ProvidePropertyAttribute:...
    def __init__(self, propertyName: str, receiverType: _n_0_t_9) -> ProvidePropertyAttribute:...
class ReadOnlyAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    No: int
    Yes: int
    @property
    def IsReadOnly(self) -> bool:"""IsReadOnly { get; } -> bool"""
    def __init__(self, isReadOnly: bool) -> ReadOnlyAttribute:...
class RecommendedAsConfigurableAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    No: int
    Yes: int
    @property
    def RecommendedAsConfigurable(self) -> bool:"""RecommendedAsConfigurable { get; } -> bool"""
    def __init__(self, recommendedAsConfigurable: bool) -> RecommendedAsConfigurableAttribute:...
class ReferenceConverter(TypeConverter):
    def __init__(self, type: _n_0_t_9) -> ReferenceConverter:...
class RefreshEventArgs(_n_0_t_0):
    @property
    def ComponentChanged(self) -> object:"""ComponentChanged { get; } -> object"""
    @property
    def TypeChanged(self) -> _n_0_t_9:"""TypeChanged { get; } -> Type"""
    def __init__(self, typeChanged: _n_0_t_9) -> RefreshEventArgs:...
    def __init__(self, componentChanged: object) -> RefreshEventArgs:...
class RefreshEventHandler(_n_0_t_1, _n_0_t_2, _n_9_t_0):
    def __init__(self, object: object, method: _n_0_t_3) -> RefreshEventHandler:...
    def BeginInvoke(self, e: RefreshEventArgs, callback: _n_0_t_5, object: object) -> _n_0_t_4:...
    def EndInvoke(self, result: _n_0_t_4):...
    def Invoke(self, e: RefreshEventArgs):...
class RefreshProperties(_n_0_t_12, _n_0_t_13, _n_0_t_14, _n_0_t_15):
    All: int
    _None: int
    Repaint: int
    value__: int
class RefreshPropertiesAttribute(_n_0_t_6, _n_8_t_0):
    All: int
    Default: int
    Repaint: int
    @property
    def RefreshProperties(self) -> RefreshProperties:"""RefreshProperties { get; } -> RefreshProperties"""
    def __init__(self, refresh: RefreshProperties) -> RefreshPropertiesAttribute:...
class RunInstallerAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    No: int
    Yes: int
    @property
    def RunInstaller(self) -> bool:"""RunInstaller { get; } -> bool"""
    def __init__(self, runInstaller: bool) -> RunInstallerAttribute:...
class RunWorkerCompletedEventArgs(AsyncCompletedEventArgs):
    @property
    def Result(self) -> object:"""Result { get; } -> object"""
    def __init__(self, result: object, error: _n_0_t_10, cancelled: bool) -> RunWorkerCompletedEventArgs:...
class RunWorkerCompletedEventHandler(_n_0_t_1, _n_0_t_2, _n_9_t_0):
    def __init__(self, object: object, method: _n_0_t_3) -> RunWorkerCompletedEventHandler:...
    def BeginInvoke(self, sender: object, e: RunWorkerCompletedEventArgs, callback: _n_0_t_5, object: object) -> _n_0_t_4:...
    def EndInvoke(self, result: _n_0_t_4):...
    def Invoke(self, sender: object, e: RunWorkerCompletedEventArgs):...
class SByteConverter(BaseNumberConverter):
    def __init__(self) -> SByteConverter:...
class SettingsBindableAttribute(_n_0_t_6, _n_8_t_0):
    No: int
    Yes: int
    @property
    def Bindable(self) -> bool:"""Bindable { get; } -> bool"""
    def __init__(self, bindable: bool) -> SettingsBindableAttribute:...
class SingleConverter(BaseNumberConverter):
    def __init__(self) -> SingleConverter:...
class StringConverter(TypeConverter):
    def __init__(self) -> StringConverter:...
class SyntaxCheck(object):
    @staticmethod
    def CheckMachineName(value: str) -> bool:...
    @staticmethod
    def CheckPath(value: str) -> bool:...
    @staticmethod
    def CheckRootedPath(value: str) -> bool:...
class TimeSpanConverter(TypeConverter):
    def __init__(self) -> TimeSpanConverter:...
class ToolboxItemAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    _None: int
    @property
    def ToolboxItemType(self) -> _n_0_t_9:"""ToolboxItemType { get; } -> Type"""
    @property
    def ToolboxItemTypeName(self) -> str:"""ToolboxItemTypeName { get; } -> str"""
    def __init__(self, toolboxItemType: _n_0_t_9) -> ToolboxItemAttribute:...
    def __init__(self, toolboxItemTypeName: str) -> ToolboxItemAttribute:...
    def __init__(self, defaultType: bool) -> ToolboxItemAttribute:...
class ToolboxItemFilterAttribute(_n_0_t_6, _n_8_t_0):
    @property
    def FilterString(self) -> str:"""FilterString { get; } -> str"""
    @property
    def FilterType(self) -> ToolboxItemFilterType:"""FilterType { get; } -> ToolboxItemFilterType"""
    def __init__(self, filterString: str, filterType: ToolboxItemFilterType) -> ToolboxItemFilterAttribute:...
    def __init__(self, filterString: str) -> ToolboxItemFilterAttribute:...
class ToolboxItemFilterType(_n_0_t_12, _n_0_t_13, _n_0_t_14, _n_0_t_15):
    Allow: int
    Custom: int
    Prevent: int
    Require: int
    value__: int
class TypeConverter(object):
    def __init__(self) -> TypeConverter:...
    def CanConvertFrom(self, context: ITypeDescriptorContext, sourceType: _n_0_t_9) -> bool:...
    def CanConvertFrom(self, sourceType: _n_0_t_9) -> bool:...
    def CanConvertTo(self, context: ITypeDescriptorContext, destinationType: _n_0_t_9) -> bool:...
    def CanConvertTo(self, destinationType: _n_0_t_9) -> bool:...
    def ConvertFrom(self, context: ITypeDescriptorContext, culture: _n_5_t_0, value: object) -> object:...
    def ConvertFrom(self, value: object) -> object:...
    def ConvertFromInvariantString(self, context: ITypeDescriptorContext, text: str) -> object:...
    def ConvertFromInvariantString(self, text: str) -> object:...
    def ConvertFromString(self, context: ITypeDescriptorContext, culture: _n_5_t_0, text: str) -> object:...
    def ConvertFromString(self, context: ITypeDescriptorContext, text: str) -> object:...
    def ConvertFromString(self, text: str) -> object:...
    def ConvertTo(self, context: ITypeDescriptorContext, culture: _n_5_t_0, value: object, destinationType: _n_0_t_9) -> object:...
    def ConvertTo(self, value: object, destinationType: _n_0_t_9) -> object:...
    def ConvertToInvariantString(self, context: ITypeDescriptorContext, value: object) -> str:...
    def ConvertToInvariantString(self, value: object) -> str:...
    def ConvertToString(self, context: ITypeDescriptorContext, culture: _n_5_t_0, value: object) -> str:...
    def ConvertToString(self, context: ITypeDescriptorContext, value: object) -> str:...
    def ConvertToString(self, value: object) -> str:...
    def CreateInstance(self, context: ITypeDescriptorContext, propertyValues: _n_1_t_6) -> object:...
    def CreateInstance(self, propertyValues: _n_1_t_6) -> object:...
    def GetCreateInstanceSupported(self, context: ITypeDescriptorContext) -> bool:...
    def GetCreateInstanceSupported(self) -> bool:...
    def GetProperties(self, context: ITypeDescriptorContext, value: object, attributes: _n_0_t_11[_n_0_t_6]) -> PropertyDescriptorCollection:...
    def GetProperties(self, context: ITypeDescriptorContext, value: object) -> PropertyDescriptorCollection:...
    def GetProperties(self, value: object) -> PropertyDescriptorCollection:...
    def GetPropertiesSupported(self, context: ITypeDescriptorContext) -> bool:...
    def GetPropertiesSupported(self) -> bool:...
    def GetStandardValues(self, context: ITypeDescriptorContext) -> TypeConverter.StandardValuesCollection:...
    def GetStandardValues(self) -> _n_1_t_0:...
    def GetStandardValuesExclusive(self, context: ITypeDescriptorContext) -> bool:...
    def GetStandardValuesExclusive(self) -> bool:...
    def GetStandardValuesSupported(self, context: ITypeDescriptorContext) -> bool:...
    def GetStandardValuesSupported(self) -> bool:...
    def IsValid(self, context: ITypeDescriptorContext, value: object) -> bool:...
    def IsValid(self, value: object) -> bool:...
    class StandardValuesCollection(_n_1_t_0):
        @property
        def Item(self) -> object:"""Item { get; } -> object"""
        def __init__(self, values: _n_1_t_0) -> TypeConverter.StandardValuesCollection:...
class TypeConverterAttribute(_n_0_t_6, _n_8_t_0):
    Default: int
    @property
    def ConverterTypeName(self) -> str:"""ConverterTypeName { get; } -> str"""
    def __init__(self, typeName: str) -> TypeConverterAttribute:...
    def __init__(self, type: _n_0_t_9) -> TypeConverterAttribute:...
    def __init__(self) -> TypeConverterAttribute:...
class TypeDescriptionProvider(object):
    def CreateInstance(self, provider: _n_0_t_21, objectType: _n_0_t_9, argTypes: _n_0_t_11[_n_0_t_9], args: _n_0_t_11[object]) -> object:...
    def GetCache(self, instance: object) -> _n_1_t_6:...
    def GetExtendedTypeDescriptor(self, instance: object) -> ICustomTypeDescriptor:...
    def GetFullComponentName(self, component: object) -> str:...
    def GetReflectionType(self, objectType: _n_0_t_9, instance: object) -> _n_0_t_9:...
    def GetReflectionType(self, instance: object) -> _n_0_t_9:...
    def GetReflectionType(self, objectType: _n_0_t_9) -> _n_0_t_9:...
    def GetRuntimeType(self, reflectionType: _n_0_t_9) -> _n_0_t_9:...
    def GetTypeDescriptor(self, objectType: _n_0_t_9, instance: object) -> ICustomTypeDescriptor:...
    def GetTypeDescriptor(self, instance: object) -> ICustomTypeDescriptor:...
    def GetTypeDescriptor(self, objectType: _n_0_t_9) -> ICustomTypeDescriptor:...
    def IsSupportedType(self, type: _n_0_t_9) -> bool:...
class TypeDescriptionProviderAttribute(_n_0_t_6, _n_8_t_0):
    @property
    def TypeName(self) -> str:"""TypeName { get; } -> str"""
    def __init__(self, type: _n_0_t_9) -> TypeDescriptionProviderAttribute:...
    def __init__(self, typeName: str) -> TypeDescriptionProviderAttribute:...
class TypeDescriptor(object):
    @property
    def ComNativeDescriptorHandler(self) -> IComNativeDescriptorHandler:"""ComNativeDescriptorHandler { get; set; } -> IComNativeDescriptorHandler"""
    @property
    def ComObjectType(self) -> _n_0_t_9:"""ComObjectType { get; } -> Type"""
    @property
    def InterfaceType(self) -> _n_0_t_9:"""InterfaceType { get; } -> Type"""
    @property
    def Refreshed(self) -> RefreshEventHandler:
        """Refreshed Event: RefreshEventHandler"""
    @staticmethod
    def AddAttributes(instance: object, attributes: _n_0_t_11[_n_0_t_6]) -> TypeDescriptionProvider:...
    @staticmethod
    def AddAttributes(type: _n_0_t_9, attributes: _n_0_t_11[_n_0_t_6]) -> TypeDescriptionProvider:...
    @staticmethod
    def AddEditorTable(editorBaseType: _n_0_t_9, table: _n_1_t_7):...
    @staticmethod
    def AddProvider(provider: TypeDescriptionProvider, instance: object):...
    @staticmethod
    def AddProvider(provider: TypeDescriptionProvider, type: _n_0_t_9):...
    @staticmethod
    def AddProviderTransparent(provider: TypeDescriptionProvider, instance: object):...
    @staticmethod
    def AddProviderTransparent(provider: TypeDescriptionProvider, type: _n_0_t_9):...
    @staticmethod
    def CreateAssociation(primary: object, secondary: object):...
    @staticmethod
    def CreateDesigner(component: IComponent, designerBaseType: _n_0_t_9) -> _n_4_t_0:...
    @staticmethod
    def CreateEvent(componentType: _n_0_t_9, oldEventDescriptor: EventDescriptor, attributes: _n_0_t_11[_n_0_t_6]) -> EventDescriptor:...
    @staticmethod
    def CreateEvent(componentType: _n_0_t_9, name: str, type: _n_0_t_9, attributes: _n_0_t_11[_n_0_t_6]) -> EventDescriptor:...
    @staticmethod
    def CreateInstance(provider: _n_0_t_21, objectType: _n_0_t_9, argTypes: _n_0_t_11[_n_0_t_9], args: _n_0_t_11[object]) -> object:...
    @staticmethod
    def CreateProperty(componentType: _n_0_t_9, oldPropertyDescriptor: PropertyDescriptor, attributes: _n_0_t_11[_n_0_t_6]) -> PropertyDescriptor:...
    @staticmethod
    def CreateProperty(componentType: _n_0_t_9, name: str, type: _n_0_t_9, attributes: _n_0_t_11[_n_0_t_6]) -> PropertyDescriptor:...
    @staticmethod
    def GetAssociation(type: _n_0_t_9, primary: object) -> object:...
    @staticmethod
    def GetAttributes(component: object, noCustomTypeDesc: bool) -> AttributeCollection:...
    @staticmethod
    def GetAttributes(component: object) -> AttributeCollection:...
    @staticmethod
    def GetAttributes(componentType: _n_0_t_9) -> AttributeCollection:...
    @staticmethod
    def GetClassName(componentType: _n_0_t_9) -> str:...
    @staticmethod
    def GetClassName(component: object, noCustomTypeDesc: bool) -> str:...
    @staticmethod
    def GetClassName(component: object) -> str:...
    @staticmethod
    def GetComponentName(component: object, noCustomTypeDesc: bool) -> str:...
    @staticmethod
    def GetComponentName(component: object) -> str:...
    @staticmethod
    def GetConverter(type: _n_0_t_9) -> TypeConverter:...
    @staticmethod
    def GetConverter(component: object, noCustomTypeDesc: bool) -> TypeConverter:...
    @staticmethod
    def GetConverter(component: object) -> TypeConverter:...
    @staticmethod
    def GetDefaultEvent(component: object, noCustomTypeDesc: bool) -> EventDescriptor:...
    @staticmethod
    def GetDefaultEvent(component: object) -> EventDescriptor:...
    @staticmethod
    def GetDefaultEvent(componentType: _n_0_t_9) -> EventDescriptor:...
    @staticmethod
    def GetDefaultProperty(component: object, noCustomTypeDesc: bool) -> PropertyDescriptor:...
    @staticmethod
    def GetDefaultProperty(component: object) -> PropertyDescriptor:...
    @staticmethod
    def GetDefaultProperty(componentType: _n_0_t_9) -> PropertyDescriptor:...
    @staticmethod
    def GetEditor(type: _n_0_t_9, editorBaseType: _n_0_t_9) -> object:...
    @staticmethod
    def GetEditor(component: object, editorBaseType: _n_0_t_9, noCustomTypeDesc: bool) -> object:...
    @staticmethod
    def GetEditor(component: object, editorBaseType: _n_0_t_9) -> object:...
    @staticmethod
    def GetEvents(component: object, attributes: _n_0_t_11[_n_0_t_6], noCustomTypeDesc: bool) -> EventDescriptorCollection:...
    @staticmethod
    def GetEvents(component: object, attributes: _n_0_t_11[_n_0_t_6]) -> EventDescriptorCollection:...
    @staticmethod
    def GetEvents(component: object, noCustomTypeDesc: bool) -> EventDescriptorCollection:...
    @staticmethod
    def GetEvents(component: object) -> EventDescriptorCollection:...
    @staticmethod
    def GetEvents(componentType: _n_0_t_9, attributes: _n_0_t_11[_n_0_t_6]) -> EventDescriptorCollection:...
    @staticmethod
    def GetEvents(componentType: _n_0_t_9) -> EventDescriptorCollection:...
    @staticmethod
    def GetFullComponentName(component: object) -> str:...
    @staticmethod
    def GetProperties(component: object, attributes: _n_0_t_11[_n_0_t_6], noCustomTypeDesc: bool) -> PropertyDescriptorCollection:...
    @staticmethod
    def GetProperties(component: object, attributes: _n_0_t_11[_n_0_t_6]) -> PropertyDescriptorCollection:...
    @staticmethod
    def GetProperties(component: object, noCustomTypeDesc: bool) -> PropertyDescriptorCollection:...
    @staticmethod
    def GetProperties(component: object) -> PropertyDescriptorCollection:...
    @staticmethod
    def GetProperties(componentType: _n_0_t_9, attributes: _n_0_t_11[_n_0_t_6]) -> PropertyDescriptorCollection:...
    @staticmethod
    def GetProperties(componentType: _n_0_t_9) -> PropertyDescriptorCollection:...
    @staticmethod
    def GetProvider(instance: object) -> TypeDescriptionProvider:...
    @staticmethod
    def GetProvider(type: _n_0_t_9) -> TypeDescriptionProvider:...
    @staticmethod
    def GetReflectionType(instance: object) -> _n_0_t_9:...
    @staticmethod
    def GetReflectionType(type: _n_0_t_9) -> _n_0_t_9:...
    @staticmethod
    def Refresh(assembly: _n_6_t_0):...
    @staticmethod
    def Refresh(module: _n_6_t_1):...
    @staticmethod
    def Refresh(type: _n_0_t_9):...
    @staticmethod
    def Refresh(component: object):...
    @staticmethod
    def RemoveAssociation(primary: object, secondary: object):...
    @staticmethod
    def RemoveAssociations(primary: object):...
    @staticmethod
    def RemoveProvider(provider: TypeDescriptionProvider, instance: object):...
    @staticmethod
    def RemoveProvider(provider: TypeDescriptionProvider, type: _n_0_t_9):...
    @staticmethod
    def RemoveProviderTransparent(provider: TypeDescriptionProvider, instance: object):...
    @staticmethod
    def RemoveProviderTransparent(provider: TypeDescriptionProvider, type: _n_0_t_9):...
    @staticmethod
    def SortDescriptorArray(infos: _n_1_t_1):...
class TypeListConverter(TypeConverter):
    pass
class UInt16Converter(BaseNumberConverter):
    def __init__(self) -> UInt16Converter:...
class UInt32Converter(BaseNumberConverter):
    def __init__(self) -> UInt32Converter:...
class UInt64Converter(BaseNumberConverter):
    def __init__(self) -> UInt64Converter:...
class WarningException(_n_0_t_22, _n_9_t_0, _n_8_t_1):
    @property
    def HelpTopic(self) -> str:"""HelpTopic { get; } -> str"""
    @property
    def HelpUrl(self) -> str:"""HelpUrl { get; } -> str"""
    def __init__(self, message: str, helpUrl: str, helpTopic: str) -> WarningException:...
    def __init__(self, message: str, innerException: _n_0_t_10) -> WarningException:...
    def __init__(self, message: str, helpUrl: str) -> WarningException:...
    def __init__(self, message: str) -> WarningException:...
    def __init__(self) -> WarningException:...
class Win32Exception(_n_8_t_2, _n_9_t_0, _n_8_t_1):
    @property
    def NativeErrorCode(self) -> int:"""NativeErrorCode { get; } -> int"""
    def __init__(self, message: str, innerException: _n_0_t_10) -> Win32Exception:...
    def __init__(self, message: str) -> Win32Exception:...
    def __init__(self, error: int, message: str) -> Win32Exception:...
    def __init__(self, error: int) -> Win32Exception:...
    def __init__(self) -> Win32Exception:...
