from __clrclasses__.System.IO.IsolatedStorage import INormalizeForIsolatedStorage
from __clrclasses__.System.IO.IsolatedStorage import IsolatedStorage
from __clrclasses__.System.IO.IsolatedStorage import IsolatedStorageException
from __clrclasses__.System.IO.IsolatedStorage import IsolatedStorageFile
from __clrclasses__.System.IO.IsolatedStorage import IsolatedStorageFileStream
from __clrclasses__.System.IO.IsolatedStorage import IsolatedStorageScope
from __clrclasses__.System.IO.IsolatedStorage import IsolatedStorageSecurityOptions
from __clrclasses__.System.IO.IsolatedStorage import IsolatedStorageSecurityState
