from __clrclasses__.System.Collections.Generic import IEnumerable as _n_0_t_0
from __clrclasses__.System.Reflection import Assembly as _n_1_t_0
import typing
class WindowsRuntimeDesignerContext(object):
    @property
    def Name(self) -> str:"""Name { get; } -> str"""
    def __init__(self, paths: _n_0_t_0[str], name: str) -> WindowsRuntimeDesignerContext:...
    def GetAssembly(self, assemblyName: str) -> _n_1_t_0:...
    @staticmethod
    def InitializeSharedContext(paths: _n_0_t_0[str]):...
    @staticmethod
    def SetIterationContext(context: WindowsRuntimeDesignerContext):...
