from __clrclasses__.System import Attribute as _n_0_t_0
from __clrclasses__.System import MarshalByRefObject as _n_0_t_1
from __clrclasses__.System import Type as _n_0_t_2
from __clrclasses__.System import IntPtr as _n_0_t_3
from __clrclasses__.System import Guid as _n_0_t_4
from __clrclasses__.System.Runtime.InteropServices import _Attribute as _n_1_t_0
from __clrclasses__.System.Runtime.Remoting import ObjRef as _n_2_t_0
from __clrclasses__.System.Runtime.Remoting.Activation import IConstructionReturnMessage as _n_3_t_0
from __clrclasses__.System.Runtime.Remoting.Activation import IConstructionCallMessage as _n_3_t_1
from __clrclasses__.System.Runtime.Remoting.Contexts import IContextAttribute as _n_4_t_0
from __clrclasses__.System.Runtime.Remoting.Contexts import Context as _n_4_t_1
from __clrclasses__.System.Runtime.Remoting.Messaging import IMessage as _n_5_t_0
from __clrclasses__.System.Runtime.Serialization import SerializationInfo as _n_6_t_0
from __clrclasses__.System.Runtime.Serialization import StreamingContext as _n_6_t_1
import typing
class ProxyAttribute(_n_0_t_0, _n_1_t_0, _n_4_t_0):
    def __init__(self) -> ProxyAttribute:...
    def CreateInstance(self, serverType: _n_0_t_2) -> _n_0_t_1:...
    def CreateProxy(self, objRef: _n_2_t_0, serverType: _n_0_t_2, serverObject: object, serverContext: _n_4_t_1) -> RealProxy:...
class RealProxy(object):
    def CreateObjRef(self, requestedType: _n_0_t_2) -> _n_2_t_0:...
    def GetCOMIUnknown(self, fIsMarshalled: bool) -> _n_0_t_3:...
    def GetObjectData(self, info: _n_6_t_0, context: _n_6_t_1):...
    def GetProxiedType(self) -> _n_0_t_2:...
    @staticmethod
    def GetStubData(rp: RealProxy) -> object:...
    def GetTransparentProxy(self) -> object:...
    def InitializeServerObject(self, ctorMsg: _n_3_t_1) -> _n_3_t_0:...
    def Invoke(self, msg: _n_5_t_0) -> _n_5_t_0:...
    def SetCOMIUnknown(self, i: _n_0_t_3):...
    @staticmethod
    def SetStubData(rp: RealProxy, stubData: object):...
    def SupportsInterface(self, iid: _n_0_t_4) -> _n_0_t_3:...
