from __clrclasses__.System import Byte as _n_0_t_0
from __clrclasses__.System import Array as _n_0_t_1
from __clrclasses__.System import Enum as _n_0_t_2
from __clrclasses__.System import IComparable as _n_0_t_3
from __clrclasses__.System import IFormattable as _n_0_t_4
from __clrclasses__.System import IConvertible as _n_0_t_5
from __clrclasses__.System import Type as _n_0_t_6
from __clrclasses__.System import RuntimeTypeHandle as _n_0_t_7
from __clrclasses__.System import RuntimeFieldHandle as _n_0_t_8
from __clrclasses__.System import RuntimeMethodHandle as _n_0_t_9
from __clrclasses__.System import ValueType as _n_0_t_10
from __clrclasses__.System import IEquatable as _n_0_t_11
from __clrclasses__.System import SByte as _n_0_t_12
from __clrclasses__.System import IntPtr as _n_0_t_13
from __clrclasses__.System import Guid as _n_0_t_14
from __clrclasses__.System.Collections.Generic import IEnumerable as _n_1_t_0
from __clrclasses__.System.Diagnostics.SymbolStore import ISymbolDocumentWriter as _n_2_t_0
from __clrclasses__.System.Diagnostics.SymbolStore import ISymbolWriter as _n_2_t_1
from __clrclasses__.System.IO import Stream as _n_3_t_0
from __clrclasses__.System.Reflection import Assembly as _n_4_t_0
from __clrclasses__.System.Reflection import ICustomAttributeProvider as _n_4_t_1
from __clrclasses__.System.Reflection import ResourceAttributes as _n_4_t_2
from __clrclasses__.System.Reflection import AssemblyName as _n_4_t_3
from __clrclasses__.System.Reflection import PortableExecutableKinds as _n_4_t_4
from __clrclasses__.System.Reflection import ImageFileMachine as _n_4_t_5
from __clrclasses__.System.Reflection import ConstructorInfo as _n_4_t_6
from __clrclasses__.System.Reflection import MethodInfo as _n_4_t_7
from __clrclasses__.System.Reflection import ParameterAttributes as _n_4_t_8
from __clrclasses__.System.Reflection import Module as _n_4_t_9
from __clrclasses__.System.Reflection import MethodImplAttributes as _n_4_t_10
from __clrclasses__.System.Reflection import PropertyInfo as _n_4_t_11
from __clrclasses__.System.Reflection import FieldInfo as _n_4_t_12
from __clrclasses__.System.Reflection import MethodAttributes as _n_4_t_13
from __clrclasses__.System.Reflection import CallingConventions as _n_4_t_14
from __clrclasses__.System.Reflection import TypeInfo as _n_4_t_15
from __clrclasses__.System.Reflection import IReflect as _n_4_t_16
from __clrclasses__.System.Reflection import IReflectableType as _n_4_t_17
from __clrclasses__.System.Reflection import ExceptionHandlingClauseOptions as _n_4_t_18
from __clrclasses__.System.Reflection import GenericParameterAttributes as _n_4_t_19
from __clrclasses__.System.Reflection import LocalVariableInfo as _n_4_t_20
from __clrclasses__.System.Reflection import TypeAttributes as _n_4_t_21
from __clrclasses__.System.Reflection import FieldAttributes as _n_4_t_22
from __clrclasses__.System.Reflection import EventAttributes as _n_4_t_23
from __clrclasses__.System.Reflection import PropertyAttributes as _n_4_t_24
from __clrclasses__.System.Resources import IResourceWriter as _n_5_t_0
from __clrclasses__.System.Runtime.InteropServices import _Assembly as _n_6_t_0
from __clrclasses__.System.Runtime.InteropServices import _AssemblyBuilder as _n_6_t_1
from __clrclasses__.System.Runtime.InteropServices import _MemberInfo as _n_6_t_2
from __clrclasses__.System.Runtime.InteropServices import _MethodBase as _n_6_t_3
from __clrclasses__.System.Runtime.InteropServices import _ConstructorInfo as _n_6_t_4
from __clrclasses__.System.Runtime.InteropServices import _ConstructorBuilder as _n_6_t_5
from __clrclasses__.System.Runtime.InteropServices import _CustomAttributeBuilder as _n_6_t_6
from __clrclasses__.System.Runtime.InteropServices import _MethodInfo as _n_6_t_7
from __clrclasses__.System.Runtime.InteropServices import _Type as _n_6_t_8
from __clrclasses__.System.Runtime.InteropServices import _EnumBuilder as _n_6_t_9
from __clrclasses__.System.Runtime.InteropServices import _EventBuilder as _n_6_t_10
from __clrclasses__.System.Runtime.InteropServices import _FieldInfo as _n_6_t_11
from __clrclasses__.System.Runtime.InteropServices import _FieldBuilder as _n_6_t_12
from __clrclasses__.System.Runtime.InteropServices import _ILGenerator as _n_6_t_13
from __clrclasses__.System.Runtime.InteropServices import CallingConvention as _n_6_t_14
from __clrclasses__.System.Runtime.InteropServices import _LocalBuilder as _n_6_t_15
from __clrclasses__.System.Runtime.InteropServices import _MethodBuilder as _n_6_t_16
from __clrclasses__.System.Runtime.InteropServices import _MethodRental as _n_6_t_17
from __clrclasses__.System.Runtime.InteropServices import _Module as _n_6_t_18
from __clrclasses__.System.Runtime.InteropServices import _ModuleBuilder as _n_6_t_19
from __clrclasses__.System.Runtime.InteropServices import CharSet as _n_6_t_20
from __clrclasses__.System.Runtime.InteropServices import _ParameterBuilder as _n_6_t_21
from __clrclasses__.System.Runtime.InteropServices import _PropertyInfo as _n_6_t_22
from __clrclasses__.System.Runtime.InteropServices import _PropertyBuilder as _n_6_t_23
from __clrclasses__.System.Runtime.InteropServices import _SignatureHelper as _n_6_t_24
from __clrclasses__.System.Runtime.InteropServices import _TypeBuilder as _n_6_t_25
from __clrclasses__.System.Runtime.InteropServices import UnmanagedType as _n_6_t_26
from __clrclasses__.System.Runtime.Serialization import ISerializable as _n_7_t_0
from __clrclasses__.System.Security import IEvidenceFactory as _n_8_t_0
from __clrclasses__.System.Security import PermissionSet as _n_8_t_1
from __clrclasses__.System.Security.Permissions import SecurityAction as _n_9_t_0
import typing
class AssemblyBuilder(_n_4_t_0, _n_6_t_0, _n_8_t_0, _n_4_t_1, _n_7_t_0, _n_6_t_1):
    def AddResourceFile(self, name: str, fileName: str, attribute: _n_4_t_2):...
    def AddResourceFile(self, name: str, fileName: str):...
    @staticmethod
    def DefineDynamicAssembly(name: _n_4_t_3, access: AssemblyBuilderAccess, assemblyAttributes: _n_1_t_0[CustomAttributeBuilder]) -> AssemblyBuilder:...
    @staticmethod
    def DefineDynamicAssembly(name: _n_4_t_3, access: AssemblyBuilderAccess) -> AssemblyBuilder:...
    def DefineDynamicModule(self, name: str, fileName: str, emitSymbolInfo: bool) -> ModuleBuilder:...
    def DefineDynamicModule(self, name: str, fileName: str) -> ModuleBuilder:...
    def DefineDynamicModule(self, name: str, emitSymbolInfo: bool) -> ModuleBuilder:...
    def DefineDynamicModule(self, name: str) -> ModuleBuilder:...
    def DefineResource(self, name: str, description: str, fileName: str, attribute: _n_4_t_2) -> _n_5_t_0:...
    def DefineResource(self, name: str, description: str, fileName: str) -> _n_5_t_0:...
    def DefineUnmanagedResource(self, resourceFileName: str):...
    def DefineUnmanagedResource(self, resource: _n_0_t_1[_n_0_t_0]):...
    def DefineVersionInfoResource(self):...
    def DefineVersionInfoResource(self, product: str, productVersion: str, company: str, copyright: str, trademark: str):...
    def GetDynamicModule(self, name: str) -> ModuleBuilder:...
    def Save(self, assemblyFileName: str, portableExecutableKind: _n_4_t_4, imageFileMachine: _n_4_t_5):...
    def Save(self, assemblyFileName: str):...
    def SetCustomAttribute(self, con: _n_4_t_6, binaryAttribute: _n_0_t_1[_n_0_t_0]):...
    def SetCustomAttribute(self, customBuilder: CustomAttributeBuilder):...
    def SetEntryPoint(self, entryMethod: _n_4_t_7, fileKind: PEFileKinds):...
    def SetEntryPoint(self, entryMethod: _n_4_t_7):...
class AssemblyBuilderAccess(_n_0_t_2, _n_0_t_3, _n_0_t_4, _n_0_t_5):
    ReflectionOnly: int
    Run: int
    RunAndCollect: int
    RunAndSave: int
    Save: int
    value__: int
class ConstructorBuilder(_n_4_t_6, _n_4_t_1, _n_6_t_2, _n_6_t_3, _n_6_t_4, _n_6_t_5):
    @property
    def InitLocals(self) -> bool:"""InitLocals { get; set; } -> bool"""
    @property
    def ReturnType(self) -> _n_0_t_6:"""ReturnType { get; } -> Type"""
    @property
    def Signature(self) -> str:"""Signature { get; } -> str"""
    def AddDeclarativeSecurity(self, action: _n_9_t_0, pset: _n_8_t_1):...
    def DefineParameter(self, iSequence: int, attributes: _n_4_t_8, strParamName: str) -> ParameterBuilder:...
    def GetILGenerator(self, streamSize: int) -> ILGenerator:...
    def GetILGenerator(self) -> ILGenerator:...
    def GetModule(self) -> _n_4_t_9:...
    def GetToken(self) -> MethodToken:...
    def SetCustomAttribute(self, customBuilder: CustomAttributeBuilder):...
    def SetCustomAttribute(self, con: _n_4_t_6, binaryAttribute: _n_0_t_1[_n_0_t_0]):...
    def SetImplementationFlags(self, attributes: _n_4_t_10):...
    def SetMethodBody(self, il: _n_0_t_1[_n_0_t_0], maxStack: int, localSignature: _n_0_t_1[_n_0_t_0], exceptionHandlers: _n_1_t_0[ExceptionHandler], tokenFixups: _n_1_t_0[int]):...
    def SetSymCustomAttribute(self, name: str, data: _n_0_t_1[_n_0_t_0]):...
class CustomAttributeBuilder(_n_6_t_6):
    def __init__(self, con: _n_4_t_6, constructorArgs: _n_0_t_1[object], namedProperties: _n_0_t_1[_n_4_t_11], propertyValues: _n_0_t_1[object], namedFields: _n_0_t_1[_n_4_t_12], fieldValues: _n_0_t_1[object]) -> CustomAttributeBuilder:...
    def __init__(self, con: _n_4_t_6, constructorArgs: _n_0_t_1[object], namedProperties: _n_0_t_1[_n_4_t_11], propertyValues: _n_0_t_1[object]) -> CustomAttributeBuilder:...
    def __init__(self, con: _n_4_t_6, constructorArgs: _n_0_t_1[object]) -> CustomAttributeBuilder:...
class DynamicILInfo(object):
    @property
    def DynamicMethod(self) -> DynamicMethod:"""DynamicMethod { get; } -> DynamicMethod"""
    def GetTokenFor(self, signature: _n_0_t_1[_n_0_t_0]) -> int:...
    def GetTokenFor(self, literal: str) -> int:...
    def GetTokenFor(self, type: _n_0_t_7) -> int:...
    def GetTokenFor(self, field: _n_0_t_8, contextType: _n_0_t_7) -> int:...
    def GetTokenFor(self, field: _n_0_t_8) -> int:...
    def GetTokenFor(self, method: _n_0_t_9, contextType: _n_0_t_7) -> int:...
    def GetTokenFor(self, method: DynamicMethod) -> int:...
    def GetTokenFor(self, method: _n_0_t_9) -> int:...
    def SetCode(self, code: _n_0_t_0, codeSize: int, maxStackSize: int):...
    def SetCode(self, code: _n_0_t_1[_n_0_t_0], maxStackSize: int):...
    def SetExceptions(self, exceptions: _n_0_t_0, exceptionsSize: int):...
    def SetExceptions(self, exceptions: _n_0_t_1[_n_0_t_0]):...
    def SetLocalSignature(self, localSignature: _n_0_t_0, signatureSize: int):...
    def SetLocalSignature(self, localSignature: _n_0_t_1[_n_0_t_0]):...
class DynamicMethod(_n_4_t_7, _n_4_t_1, _n_6_t_2, _n_6_t_3, _n_6_t_7):
    @property
    def InitLocals(self) -> bool:"""InitLocals { get; set; } -> bool"""
    def __init__(self, name: str, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6], owner: _n_0_t_6) -> DynamicMethod:...
    def __init__(self, name: str, attributes: _n_4_t_13, callingConvention: _n_4_t_14, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6], m: _n_4_t_9, skipVisibility: bool) -> DynamicMethod:...
    def __init__(self, name: str, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6], m: _n_4_t_9) -> DynamicMethod:...
    def __init__(self, name: str, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6], restrictedSkipVisibility: bool) -> DynamicMethod:...
    def __init__(self, name: str, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6]) -> DynamicMethod:...
    def __init__(self, name: str, attributes: _n_4_t_13, callingConvention: _n_4_t_14, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6], owner: _n_0_t_6, skipVisibility: bool) -> DynamicMethod:...
    def __init__(self, name: str, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6], owner: _n_0_t_6, skipVisibility: bool) -> DynamicMethod:...
    def __init__(self, name: str, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6], m: _n_4_t_9, skipVisibility: bool) -> DynamicMethod:...
    def DefineParameter(self, position: int, attributes: _n_4_t_8, parameterName: str) -> ParameterBuilder:...
    def GetDynamicILInfo(self) -> DynamicILInfo:...
    def GetILGenerator(self, streamSize: int) -> ILGenerator:...
    def GetILGenerator(self) -> ILGenerator:...
class EnumBuilder(_n_4_t_15, _n_4_t_1, _n_6_t_2, _n_6_t_8, _n_4_t_16, _n_4_t_17, _n_6_t_9):
    @property
    def TypeToken(self) -> TypeToken:"""TypeToken { get; } -> TypeToken"""
    @property
    def UnderlyingField(self) -> FieldBuilder:"""UnderlyingField { get; } -> FieldBuilder"""
    def CreateType(self) -> _n_0_t_6:...
    def CreateTypeInfo(self) -> _n_4_t_15:...
    def DefineLiteral(self, literalName: str, literalValue: object) -> FieldBuilder:...
    def SetCustomAttribute(self, customBuilder: CustomAttributeBuilder):...
    def SetCustomAttribute(self, con: _n_4_t_6, binaryAttribute: _n_0_t_1[_n_0_t_0]):...
class EventBuilder(_n_6_t_10):
    def AddOtherMethod(self, mdBuilder: MethodBuilder):...
    def GetEventToken(self) -> EventToken:...
    def SetAddOnMethod(self, mdBuilder: MethodBuilder):...
    def SetCustomAttribute(self, customBuilder: CustomAttributeBuilder):...
    def SetCustomAttribute(self, con: _n_4_t_6, binaryAttribute: _n_0_t_1[_n_0_t_0]):...
    def SetRaiseMethod(self, mdBuilder: MethodBuilder):...
    def SetRemoveOnMethod(self, mdBuilder: MethodBuilder):...
class EventToken(_n_0_t_10):
    Empty: int
    @property
    def Token(self) -> int:"""Token { get; } -> int"""
class ExceptionHandler(_n_0_t_10, _n_0_t_11[ExceptionHandler]):
    @property
    def ExceptionTypeToken(self) -> int:"""ExceptionTypeToken { get; } -> int"""
    @property
    def FilterOffset(self) -> int:"""FilterOffset { get; } -> int"""
    @property
    def HandlerLength(self) -> int:"""HandlerLength { get; } -> int"""
    @property
    def HandlerOffset(self) -> int:"""HandlerOffset { get; } -> int"""
    @property
    def Kind(self) -> _n_4_t_18:"""Kind { get; } -> ExceptionHandlingClauseOptions"""
    @property
    def TryLength(self) -> int:"""TryLength { get; } -> int"""
    @property
    def TryOffset(self) -> int:"""TryOffset { get; } -> int"""
    def __init__(self, tryOffset: int, tryLength: int, filterOffset: int, handlerOffset: int, handlerLength: int, kind: _n_4_t_18, exceptionTypeToken: int) -> ExceptionHandler:...
class FieldBuilder(_n_4_t_12, _n_4_t_1, _n_6_t_2, _n_6_t_11, _n_6_t_12):
    def GetToken(self) -> FieldToken:...
    def SetConstant(self, defaultValue: object):...
    def SetCustomAttribute(self, customBuilder: CustomAttributeBuilder):...
    def SetCustomAttribute(self, con: _n_4_t_6, binaryAttribute: _n_0_t_1[_n_0_t_0]):...
    def SetMarshal(self, unmanagedMarshal: UnmanagedMarshal):...
    def SetOffset(self, iOffset: int):...
class FieldToken(_n_0_t_10):
    Empty: int
    @property
    def Token(self) -> int:"""Token { get; } -> int"""
class FlowControl(_n_0_t_2, _n_0_t_3, _n_0_t_4, _n_0_t_5):
    Branch: int
    Break: int
    Call: int
    Cond_Branch: int
    Meta: int
    Next: int
    Phi: int
    Return: int
    Throw: int
    value__: int
class GenericTypeParameterBuilder(_n_4_t_15, _n_4_t_1, _n_6_t_2, _n_6_t_8, _n_4_t_16, _n_4_t_17):
    def SetBaseTypeConstraint(self, baseTypeConstraint: _n_0_t_6):...
    def SetCustomAttribute(self, customBuilder: CustomAttributeBuilder):...
    def SetCustomAttribute(self, con: _n_4_t_6, binaryAttribute: _n_0_t_1[_n_0_t_0]):...
    def SetGenericParameterAttributes(self, genericParameterAttributes: _n_4_t_19):...
    def SetInterfaceConstraints(self, interfaceConstraints: _n_0_t_1[_n_0_t_6]):...
class ILGenerator(_n_6_t_13):
    @property
    def ILOffset(self) -> int:"""ILOffset { get; } -> int"""
    def BeginCatchBlock(self, exceptionType: _n_0_t_6):...
    def BeginExceptFilterBlock(self):...
    def BeginExceptionBlock(self) -> Label:...
    def BeginFaultBlock(self):...
    def BeginFinallyBlock(self):...
    def BeginScope(self):...
    def DeclareLocal(self, localType: _n_0_t_6, pinned: bool) -> LocalBuilder:...
    def DeclareLocal(self, localType: _n_0_t_6) -> LocalBuilder:...
    def DefineLabel(self) -> Label:...
    def Emit(self, opcode: OpCode, local: LocalBuilder):...
    def Emit(self, opcode: OpCode, str: str):...
    def Emit(self, opcode: OpCode, field: _n_4_t_12):...
    def Emit(self, opcode: OpCode, labels: _n_0_t_1[Label]):...
    def Emit(self, opcode: OpCode, label: Label):...
    def Emit(self, opcode: OpCode, arg: float):...
    def Emit(self, opcode: OpCode, cls: _n_0_t_6):...
    def Emit(self, opcode: OpCode, con: _n_4_t_6):...
    def Emit(self, opcode: OpCode, signature: SignatureHelper):...
    def Emit(self, opcode: OpCode, meth: _n_4_t_7):...
    def Emit(self, opcode: OpCode, arg: int):...
    def Emit(self, opcode: OpCode, arg: _n_0_t_12):...
    def Emit(self, opcode: OpCode, arg: _n_0_t_0):...
    def Emit(self, opcode: OpCode):...
    def EmitCall(self, opcode: OpCode, methodInfo: _n_4_t_7, optionalParameterTypes: _n_0_t_1[_n_0_t_6]):...
    def EmitCalli(self, opcode: OpCode, unmanagedCallConv: _n_6_t_14, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6]):...
    def EmitCalli(self, opcode: OpCode, callingConvention: _n_4_t_14, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6], optionalParameterTypes: _n_0_t_1[_n_0_t_6]):...
    def EmitWriteLine(self, fld: _n_4_t_12):...
    def EmitWriteLine(self, localBuilder: LocalBuilder):...
    def EmitWriteLine(self, value: str):...
    def EndExceptionBlock(self):...
    def EndScope(self):...
    def MarkLabel(self, loc: Label):...
    def MarkSequencePoint(self, document: _n_2_t_0, startLine: int, startColumn: int, endLine: int, endColumn: int):...
    def ThrowException(self, excType: _n_0_t_6):...
    def UsingNamespace(self, usingNamespace: str):...
class Label(_n_0_t_10):
    pass
class LocalBuilder(_n_4_t_20, _n_6_t_15):
    def SetLocalSymInfo(self, name: str, startOffset: int, endOffset: int):...
    def SetLocalSymInfo(self, name: str):...
class MethodBuilder(_n_4_t_7, _n_4_t_1, _n_6_t_2, _n_6_t_3, _n_6_t_7, _n_6_t_16):
    @property
    def InitLocals(self) -> bool:"""InitLocals { get; set; } -> bool"""
    @property
    def Signature(self) -> str:"""Signature { get; } -> str"""
    def AddDeclarativeSecurity(self, action: _n_9_t_0, pset: _n_8_t_1):...
    def CreateMethodBody(self, il: _n_0_t_1[_n_0_t_0], count: int):...
    def DefineGenericParameters(self, names: _n_0_t_1[str]) -> _n_0_t_1[GenericTypeParameterBuilder]:...
    def DefineParameter(self, position: int, attributes: _n_4_t_8, strParamName: str) -> ParameterBuilder:...
    def GetILGenerator(self, size: int) -> ILGenerator:...
    def GetILGenerator(self) -> ILGenerator:...
    def GetModule(self) -> _n_4_t_9:...
    def GetToken(self) -> MethodToken:...
    def SetCustomAttribute(self, customBuilder: CustomAttributeBuilder):...
    def SetCustomAttribute(self, con: _n_4_t_6, binaryAttribute: _n_0_t_1[_n_0_t_0]):...
    def SetImplementationFlags(self, attributes: _n_4_t_10):...
    def SetMarshal(self, unmanagedMarshal: UnmanagedMarshal):...
    def SetMethodBody(self, il: _n_0_t_1[_n_0_t_0], maxStack: int, localSignature: _n_0_t_1[_n_0_t_0], exceptionHandlers: _n_1_t_0[ExceptionHandler], tokenFixups: _n_1_t_0[int]):...
    def SetParameters(self, parameterTypes: _n_0_t_1[_n_0_t_6]):...
    def SetReturnType(self, returnType: _n_0_t_6):...
    def SetSignature(self, returnType: _n_0_t_6, returnTypeRequiredCustomModifiers: _n_0_t_1[_n_0_t_6], returnTypeOptionalCustomModifiers: _n_0_t_1[_n_0_t_6], parameterTypes: _n_0_t_1[_n_0_t_6], parameterTypeRequiredCustomModifiers: _n_0_t_1[_n_0_t_1[_n_0_t_6]], parameterTypeOptionalCustomModifiers: _n_0_t_1[_n_0_t_1[_n_0_t_6]]):...
    def SetSymCustomAttribute(self, name: str, data: _n_0_t_1[_n_0_t_0]):...
class MethodRental(_n_6_t_17):
    JitImmediate: int
    JitOnDemand: int
    @staticmethod
    def SwapMethodBody(cls: _n_0_t_6, methodtoken: int, rgIL: _n_0_t_13, methodSize: int, flags: int):...
class MethodToken(_n_0_t_10):
    Empty: int
    @property
    def Token(self) -> int:"""Token { get; } -> int"""
class ModuleBuilder(_n_4_t_9, _n_6_t_18, _n_7_t_0, _n_4_t_1, _n_6_t_19):
    def CreateGlobalFunctions(self):...
    def DefineDocument(self, url: str, language: _n_0_t_14, languageVendor: _n_0_t_14, documentType: _n_0_t_14) -> _n_2_t_0:...
    def DefineEnum(self, name: str, visibility: _n_4_t_21, underlyingType: _n_0_t_6) -> EnumBuilder:...
    def DefineGlobalMethod(self, name: str, attributes: _n_4_t_13, callingConvention: _n_4_t_14, returnType: _n_0_t_6, requiredReturnTypeCustomModifiers: _n_0_t_1[_n_0_t_6], optionalReturnTypeCustomModifiers: _n_0_t_1[_n_0_t_6], parameterTypes: _n_0_t_1[_n_0_t_6], requiredParameterTypeCustomModifiers: _n_0_t_1[_n_0_t_1[_n_0_t_6]], optionalParameterTypeCustomModifiers: _n_0_t_1[_n_0_t_1[_n_0_t_6]]) -> MethodBuilder:...
    def DefineGlobalMethod(self, name: str, attributes: _n_4_t_13, callingConvention: _n_4_t_14, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6]) -> MethodBuilder:...
    def DefineGlobalMethod(self, name: str, attributes: _n_4_t_13, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6]) -> MethodBuilder:...
    def DefineInitializedData(self, name: str, data: _n_0_t_1[_n_0_t_0], attributes: _n_4_t_22) -> FieldBuilder:...
    def DefineManifestResource(self, name: str, stream: _n_3_t_0, attribute: _n_4_t_2):...
    def DefinePInvokeMethod(self, name: str, dllName: str, entryName: str, attributes: _n_4_t_13, callingConvention: _n_4_t_14, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6], nativeCallConv: _n_6_t_14, nativeCharSet: _n_6_t_20) -> MethodBuilder:...
    def DefinePInvokeMethod(self, name: str, dllName: str, attributes: _n_4_t_13, callingConvention: _n_4_t_14, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6], nativeCallConv: _n_6_t_14, nativeCharSet: _n_6_t_20) -> MethodBuilder:...
    def DefineResource(self, name: str, description: str, attribute: _n_4_t_2) -> _n_5_t_0:...
    def DefineResource(self, name: str, description: str) -> _n_5_t_0:...
    def DefineType(self, name: str, attr: _n_4_t_21, parent: _n_0_t_6, packsize: PackingSize) -> TypeBuilder:...
    def DefineType(self, name: str, attr: _n_4_t_21, parent: _n_0_t_6, packingSize: PackingSize, typesize: int) -> TypeBuilder:...
    def DefineType(self, name: str, attr: _n_4_t_21, parent: _n_0_t_6, typesize: int) -> TypeBuilder:...
    def DefineType(self, name: str, attr: _n_4_t_21, parent: _n_0_t_6) -> TypeBuilder:...
    def DefineType(self, name: str, attr: _n_4_t_21) -> TypeBuilder:...
    def DefineType(self, name: str) -> TypeBuilder:...
    def DefineType(self, name: str, attr: _n_4_t_21, parent: _n_0_t_6, interfaces: _n_0_t_1[_n_0_t_6]) -> TypeBuilder:...
    def DefineUninitializedData(self, name: str, size: int, attributes: _n_4_t_22) -> FieldBuilder:...
    def DefineUnmanagedResource(self, resourceFileName: str):...
    def DefineUnmanagedResource(self, resource: _n_0_t_1[_n_0_t_0]):...
    def GetArrayMethod(self, arrayClass: _n_0_t_6, methodName: str, callingConvention: _n_4_t_14, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6]) -> _n_4_t_7:...
    def GetArrayMethodToken(self, arrayClass: _n_0_t_6, methodName: str, callingConvention: _n_4_t_14, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6]) -> MethodToken:...
    def GetConstructorToken(self, con: _n_4_t_6) -> MethodToken:...
    def GetConstructorToken(self, constructor: _n_4_t_6, optionalParameterTypes: _n_1_t_0[_n_0_t_6]) -> MethodToken:...
    def GetFieldToken(self, field: _n_4_t_12) -> FieldToken:...
    def GetMethodToken(self, method: _n_4_t_7, optionalParameterTypes: _n_1_t_0[_n_0_t_6]) -> MethodToken:...
    def GetMethodToken(self, method: _n_4_t_7) -> MethodToken:...
    def GetSignatureToken(self, sigBytes: _n_0_t_1[_n_0_t_0], sigLength: int) -> SignatureToken:...
    def GetSignatureToken(self, sigHelper: SignatureHelper) -> SignatureToken:...
    def GetStringConstant(self, str: str) -> StringToken:...
    def GetSymWriter(self) -> _n_2_t_1:...
    def GetTypeToken(self, name: str) -> TypeToken:...
    def GetTypeToken(self, type: _n_0_t_6) -> TypeToken:...
    def IsTransient(self) -> bool:...
    def SetCustomAttribute(self, customBuilder: CustomAttributeBuilder):...
    def SetCustomAttribute(self, con: _n_4_t_6, binaryAttribute: _n_0_t_1[_n_0_t_0]):...
    def SetSymCustomAttribute(self, name: str, data: _n_0_t_1[_n_0_t_0]):...
    def SetUserEntryPoint(self, entryPoint: _n_4_t_7):...
class OpCode(_n_0_t_10):
    @property
    def FlowControl(self) -> FlowControl:"""FlowControl { get; } -> FlowControl"""
    @property
    def Name(self) -> str:"""Name { get; } -> str"""
    @property
    def OpCodeType(self) -> OpCodeType:"""OpCodeType { get; } -> OpCodeType"""
    @property
    def OperandType(self) -> OperandType:"""OperandType { get; } -> OperandType"""
    @property
    def Size(self) -> int:"""Size { get; } -> int"""
    @property
    def StackBehaviourPop(self) -> StackBehaviour:"""StackBehaviourPop { get; } -> StackBehaviour"""
    @property
    def StackBehaviourPush(self) -> StackBehaviour:"""StackBehaviourPush { get; } -> StackBehaviour"""
    @property
    def Value(self) -> int:"""Value { get; } -> int"""
class OpCodes(object):
    Add: int
    Add_Ovf: int
    Add_Ovf_Un: int
    And: int
    Arglist: int
    Beq: int
    Beq_S: int
    Bge: int
    Bge_S: int
    Bge_Un: int
    Bge_Un_S: int
    Bgt: int
    Bgt_S: int
    Bgt_Un: int
    Bgt_Un_S: int
    Ble: int
    Ble_S: int
    Ble_Un: int
    Ble_Un_S: int
    Blt: int
    Blt_S: int
    Blt_Un: int
    Blt_Un_S: int
    Bne_Un: int
    Bne_Un_S: int
    Box: int
    Br: int
    Br_S: int
    Break: int
    Brfalse: int
    Brfalse_S: int
    Brtrue: int
    Brtrue_S: int
    Call: int
    Calli: int
    Callvirt: int
    Castclass: int
    Ceq: int
    Cgt: int
    Cgt_Un: int
    Ckfinite: int
    Clt: int
    Clt_Un: int
    Constrained: int
    Conv_I: int
    Conv_I1: int
    Conv_I2: int
    Conv_I4: int
    Conv_I8: int
    Conv_Ovf_I: int
    Conv_Ovf_I_Un: int
    Conv_Ovf_I1: int
    Conv_Ovf_I1_Un: int
    Conv_Ovf_I2: int
    Conv_Ovf_I2_Un: int
    Conv_Ovf_I4: int
    Conv_Ovf_I4_Un: int
    Conv_Ovf_I8: int
    Conv_Ovf_I8_Un: int
    Conv_Ovf_U: int
    Conv_Ovf_U_Un: int
    Conv_Ovf_U1: int
    Conv_Ovf_U1_Un: int
    Conv_Ovf_U2: int
    Conv_Ovf_U2_Un: int
    Conv_Ovf_U4: int
    Conv_Ovf_U4_Un: int
    Conv_Ovf_U8: int
    Conv_Ovf_U8_Un: int
    Conv_R_Un: int
    Conv_R4: int
    Conv_R8: int
    Conv_U: int
    Conv_U1: int
    Conv_U2: int
    Conv_U4: int
    Conv_U8: int
    Cpblk: int
    Cpobj: int
    Div: int
    Div_Un: int
    Dup: int
    Endfilter: int
    Endfinally: int
    Initblk: int
    Initobj: int
    Isinst: int
    Jmp: int
    Ldarg: int
    Ldarg_0: int
    Ldarg_1: int
    Ldarg_2: int
    Ldarg_3: int
    Ldarg_S: int
    Ldarga: int
    Ldarga_S: int
    Ldc_I4: int
    Ldc_I4_0: int
    Ldc_I4_1: int
    Ldc_I4_2: int
    Ldc_I4_3: int
    Ldc_I4_4: int
    Ldc_I4_5: int
    Ldc_I4_6: int
    Ldc_I4_7: int
    Ldc_I4_8: int
    Ldc_I4_M1: int
    Ldc_I4_S: int
    Ldc_I8: int
    Ldc_R4: int
    Ldc_R8: int
    Ldelem: int
    Ldelem_I: int
    Ldelem_I1: int
    Ldelem_I2: int
    Ldelem_I4: int
    Ldelem_I8: int
    Ldelem_R4: int
    Ldelem_R8: int
    Ldelem_Ref: int
    Ldelem_U1: int
    Ldelem_U2: int
    Ldelem_U4: int
    Ldelema: int
    Ldfld: int
    Ldflda: int
    Ldftn: int
    Ldind_I: int
    Ldind_I1: int
    Ldind_I2: int
    Ldind_I4: int
    Ldind_I8: int
    Ldind_R4: int
    Ldind_R8: int
    Ldind_Ref: int
    Ldind_U1: int
    Ldind_U2: int
    Ldind_U4: int
    Ldlen: int
    Ldloc: int
    Ldloc_0: int
    Ldloc_1: int
    Ldloc_2: int
    Ldloc_3: int
    Ldloc_S: int
    Ldloca: int
    Ldloca_S: int
    Ldnull: int
    Ldobj: int
    Ldsfld: int
    Ldsflda: int
    Ldstr: int
    Ldtoken: int
    Ldvirtftn: int
    Leave: int
    Leave_S: int
    Localloc: int
    Mkrefany: int
    Mul: int
    Mul_Ovf: int
    Mul_Ovf_Un: int
    Neg: int
    Newarr: int
    Newobj: int
    Nop: int
    Not: int
    Or: int
    Pop: int
    Prefix1: int
    Prefix2: int
    Prefix3: int
    Prefix4: int
    Prefix5: int
    Prefix6: int
    Prefix7: int
    Prefixref: int
    Readonly: int
    Refanytype: int
    Refanyval: int
    Rem: int
    Rem_Un: int
    Ret: int
    Rethrow: int
    Shl: int
    Shr: int
    Shr_Un: int
    Sizeof: int
    Starg: int
    Starg_S: int
    Stelem: int
    Stelem_I: int
    Stelem_I1: int
    Stelem_I2: int
    Stelem_I4: int
    Stelem_I8: int
    Stelem_R4: int
    Stelem_R8: int
    Stelem_Ref: int
    Stfld: int
    Stind_I: int
    Stind_I1: int
    Stind_I2: int
    Stind_I4: int
    Stind_I8: int
    Stind_R4: int
    Stind_R8: int
    Stind_Ref: int
    Stloc: int
    Stloc_0: int
    Stloc_1: int
    Stloc_2: int
    Stloc_3: int
    Stloc_S: int
    Stobj: int
    Stsfld: int
    Sub: int
    Sub_Ovf: int
    Sub_Ovf_Un: int
    Switch: int
    Tailcall: int
    Throw: int
    Unaligned: int
    Unbox: int
    Unbox_Any: int
    Volatile: int
    Xor: int
    @staticmethod
    def TakesSingleByteArgument(inst: OpCode) -> bool:...
class OpCodeType(_n_0_t_2, _n_0_t_3, _n_0_t_4, _n_0_t_5):
    Annotation: int
    Macro: int
    Nternal: int
    Objmodel: int
    Prefix: int
    Primitive: int
    value__: int
class OperandType(_n_0_t_2, _n_0_t_3, _n_0_t_4, _n_0_t_5):
    InlineBrTarget: int
    InlineField: int
    InlineI: int
    InlineI8: int
    InlineMethod: int
    InlineNone: int
    InlinePhi: int
    InlineR: int
    InlineSig: int
    InlineString: int
    InlineSwitch: int
    InlineTok: int
    InlineType: int
    InlineVar: int
    ShortInlineBrTarget: int
    ShortInlineI: int
    ShortInlineR: int
    ShortInlineVar: int
    value__: int
class PackingSize(_n_0_t_2, _n_0_t_3, _n_0_t_4, _n_0_t_5):
    Size1: int
    Size128: int
    Size16: int
    Size2: int
    Size32: int
    Size4: int
    Size64: int
    Size8: int
    Unspecified: int
    value__: int
class ParameterBuilder(_n_6_t_21):
    @property
    def Attributes(self) -> int:"""Attributes { get; } -> int"""
    @property
    def IsIn(self) -> bool:"""IsIn { get; } -> bool"""
    @property
    def IsOptional(self) -> bool:"""IsOptional { get; } -> bool"""
    @property
    def IsOut(self) -> bool:"""IsOut { get; } -> bool"""
    @property
    def Name(self) -> str:"""Name { get; } -> str"""
    @property
    def Position(self) -> int:"""Position { get; } -> int"""
    def GetToken(self) -> ParameterToken:...
    def SetConstant(self, defaultValue: object):...
    def SetCustomAttribute(self, customBuilder: CustomAttributeBuilder):...
    def SetCustomAttribute(self, con: _n_4_t_6, binaryAttribute: _n_0_t_1[_n_0_t_0]):...
    def SetMarshal(self, unmanagedMarshal: UnmanagedMarshal):...
class ParameterToken(_n_0_t_10):
    Empty: int
    @property
    def Token(self) -> int:"""Token { get; } -> int"""
class PEFileKinds(_n_0_t_2, _n_0_t_3, _n_0_t_4, _n_0_t_5):
    ConsoleApplication: int
    Dll: int
    value__: int
    WindowApplication: int
class PropertyBuilder(_n_4_t_11, _n_4_t_1, _n_6_t_2, _n_6_t_22, _n_6_t_23):
    @property
    def PropertyToken(self) -> PropertyToken:"""PropertyToken { get; } -> PropertyToken"""
    def AddOtherMethod(self, mdBuilder: MethodBuilder):...
    def SetConstant(self, defaultValue: object):...
    def SetCustomAttribute(self, customBuilder: CustomAttributeBuilder):...
    def SetCustomAttribute(self, con: _n_4_t_6, binaryAttribute: _n_0_t_1[_n_0_t_0]):...
    def SetGetMethod(self, mdBuilder: MethodBuilder):...
    def SetSetMethod(self, mdBuilder: MethodBuilder):...
class PropertyToken(_n_0_t_10):
    Empty: int
    @property
    def Token(self) -> int:"""Token { get; } -> int"""
class SignatureHelper(_n_6_t_24):
    def AddArgument(self, argument: _n_0_t_6, requiredCustomModifiers: _n_0_t_1[_n_0_t_6], optionalCustomModifiers: _n_0_t_1[_n_0_t_6]):...
    def AddArgument(self, argument: _n_0_t_6, pinned: bool):...
    def AddArgument(self, clsArgument: _n_0_t_6):...
    def AddArguments(self, arguments: _n_0_t_1[_n_0_t_6], requiredCustomModifiers: _n_0_t_1[_n_0_t_1[_n_0_t_6]], optionalCustomModifiers: _n_0_t_1[_n_0_t_1[_n_0_t_6]]):...
    def AddSentinel(self):...
    @staticmethod
    def GetFieldSigHelper(mod: _n_4_t_9) -> SignatureHelper:...
    @staticmethod
    def GetLocalVarSigHelper(mod: _n_4_t_9) -> SignatureHelper:...
    @staticmethod
    def GetLocalVarSigHelper() -> SignatureHelper:...
    @staticmethod
    def GetMethodSigHelper(unmanagedCallingConvention: _n_6_t_14, returnType: _n_0_t_6) -> SignatureHelper:...
    @staticmethod
    def GetMethodSigHelper(callingConvention: _n_4_t_14, returnType: _n_0_t_6) -> SignatureHelper:...
    @staticmethod
    def GetMethodSigHelper(mod: _n_4_t_9, unmanagedCallConv: _n_6_t_14, returnType: _n_0_t_6) -> SignatureHelper:...
    @staticmethod
    def GetMethodSigHelper(mod: _n_4_t_9, callingConvention: _n_4_t_14, returnType: _n_0_t_6) -> SignatureHelper:...
    @staticmethod
    def GetMethodSigHelper(mod: _n_4_t_9, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6]) -> SignatureHelper:...
    @staticmethod
    def GetPropertySigHelper(mod: _n_4_t_9, callingConvention: _n_4_t_14, returnType: _n_0_t_6, requiredReturnTypeCustomModifiers: _n_0_t_1[_n_0_t_6], optionalReturnTypeCustomModifiers: _n_0_t_1[_n_0_t_6], parameterTypes: _n_0_t_1[_n_0_t_6], requiredParameterTypeCustomModifiers: _n_0_t_1[_n_0_t_1[_n_0_t_6]], optionalParameterTypeCustomModifiers: _n_0_t_1[_n_0_t_1[_n_0_t_6]]) -> SignatureHelper:...
    @staticmethod
    def GetPropertySigHelper(mod: _n_4_t_9, returnType: _n_0_t_6, requiredReturnTypeCustomModifiers: _n_0_t_1[_n_0_t_6], optionalReturnTypeCustomModifiers: _n_0_t_1[_n_0_t_6], parameterTypes: _n_0_t_1[_n_0_t_6], requiredParameterTypeCustomModifiers: _n_0_t_1[_n_0_t_1[_n_0_t_6]], optionalParameterTypeCustomModifiers: _n_0_t_1[_n_0_t_1[_n_0_t_6]]) -> SignatureHelper:...
    @staticmethod
    def GetPropertySigHelper(mod: _n_4_t_9, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6]) -> SignatureHelper:...
    def GetSignature(self) -> _n_0_t_1[_n_0_t_0]:...
class SignatureToken(_n_0_t_10):
    Empty: int
    @property
    def Token(self) -> int:"""Token { get; } -> int"""
class StackBehaviour(_n_0_t_2, _n_0_t_3, _n_0_t_4, _n_0_t_5):
    Pop0: int
    Pop1: int
    Pop1_pop1: int
    Popi: int
    Popi_pop1: int
    Popi_popi: int
    Popi_popi_popi: int
    Popi_popi8: int
    Popi_popr4: int
    Popi_popr8: int
    Popref: int
    Popref_pop1: int
    Popref_popi: int
    Popref_popi_pop1: int
    Popref_popi_popi: int
    Popref_popi_popi8: int
    Popref_popi_popr4: int
    Popref_popi_popr8: int
    Popref_popi_popref: int
    Push0: int
    Push1: int
    Push1_push1: int
    Pushi: int
    Pushi8: int
    Pushr4: int
    Pushr8: int
    Pushref: int
    value__: int
    Varpop: int
    Varpush: int
class StringToken(_n_0_t_10):
    @property
    def Token(self) -> int:"""Token { get; } -> int"""
class TypeBuilder(_n_4_t_15, _n_4_t_1, _n_6_t_2, _n_6_t_8, _n_4_t_16, _n_4_t_17, _n_6_t_25):
    UnspecifiedTypeSize: int
    @property
    def PackingSize(self) -> PackingSize:"""PackingSize { get; } -> PackingSize"""
    @property
    def Size(self) -> int:"""Size { get; } -> int"""
    @property
    def TypeToken(self) -> TypeToken:"""TypeToken { get; } -> TypeToken"""
    def AddDeclarativeSecurity(self, action: _n_9_t_0, pset: _n_8_t_1):...
    def AddInterfaceImplementation(self, interfaceType: _n_0_t_6):...
    def CreateType(self) -> _n_0_t_6:...
    def CreateTypeInfo(self) -> _n_4_t_15:...
    def DefineConstructor(self, attributes: _n_4_t_13, callingConvention: _n_4_t_14, parameterTypes: _n_0_t_1[_n_0_t_6], requiredCustomModifiers: _n_0_t_1[_n_0_t_1[_n_0_t_6]], optionalCustomModifiers: _n_0_t_1[_n_0_t_1[_n_0_t_6]]) -> ConstructorBuilder:...
    def DefineConstructor(self, attributes: _n_4_t_13, callingConvention: _n_4_t_14, parameterTypes: _n_0_t_1[_n_0_t_6]) -> ConstructorBuilder:...
    def DefineDefaultConstructor(self, attributes: _n_4_t_13) -> ConstructorBuilder:...
    def DefineEvent(self, name: str, attributes: _n_4_t_23, eventtype: _n_0_t_6) -> EventBuilder:...
    def DefineField(self, fieldName: str, type: _n_0_t_6, attributes: _n_4_t_22) -> FieldBuilder:...
    def DefineField(self, fieldName: str, type: _n_0_t_6, requiredCustomModifiers: _n_0_t_1[_n_0_t_6], optionalCustomModifiers: _n_0_t_1[_n_0_t_6], attributes: _n_4_t_22) -> FieldBuilder:...
    def DefineGenericParameters(self, names: _n_0_t_1[str]) -> _n_0_t_1[GenericTypeParameterBuilder]:...
    def DefineInitializedData(self, name: str, data: _n_0_t_1[_n_0_t_0], attributes: _n_4_t_22) -> FieldBuilder:...
    def DefineMethod(self, name: str, attributes: _n_4_t_13, callingConvention: _n_4_t_14, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6]) -> MethodBuilder:...
    def DefineMethod(self, name: str, attributes: _n_4_t_13, callingConvention: _n_4_t_14) -> MethodBuilder:...
    def DefineMethod(self, name: str, attributes: _n_4_t_13) -> MethodBuilder:...
    def DefineMethod(self, name: str, attributes: _n_4_t_13, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6]) -> MethodBuilder:...
    def DefineMethod(self, name: str, attributes: _n_4_t_13, callingConvention: _n_4_t_14, returnType: _n_0_t_6, returnTypeRequiredCustomModifiers: _n_0_t_1[_n_0_t_6], returnTypeOptionalCustomModifiers: _n_0_t_1[_n_0_t_6], parameterTypes: _n_0_t_1[_n_0_t_6], parameterTypeRequiredCustomModifiers: _n_0_t_1[_n_0_t_1[_n_0_t_6]], parameterTypeOptionalCustomModifiers: _n_0_t_1[_n_0_t_1[_n_0_t_6]]) -> MethodBuilder:...
    def DefineMethodOverride(self, methodInfoBody: _n_4_t_7, methodInfoDeclaration: _n_4_t_7):...
    def DefineNestedType(self, name: str, attr: _n_4_t_21, parent: _n_0_t_6, packSize: PackingSize, typeSize: int) -> TypeBuilder:...
    def DefineNestedType(self, name: str, attr: _n_4_t_21, parent: _n_0_t_6, packSize: PackingSize) -> TypeBuilder:...
    def DefineNestedType(self, name: str, attr: _n_4_t_21, parent: _n_0_t_6, typeSize: int) -> TypeBuilder:...
    def DefineNestedType(self, name: str, attr: _n_4_t_21) -> TypeBuilder:...
    def DefineNestedType(self, name: str, attr: _n_4_t_21, parent: _n_0_t_6) -> TypeBuilder:...
    def DefineNestedType(self, name: str, attr: _n_4_t_21, parent: _n_0_t_6, interfaces: _n_0_t_1[_n_0_t_6]) -> TypeBuilder:...
    def DefineNestedType(self, name: str) -> TypeBuilder:...
    def DefinePInvokeMethod(self, name: str, dllName: str, entryName: str, attributes: _n_4_t_13, callingConvention: _n_4_t_14, returnType: _n_0_t_6, returnTypeRequiredCustomModifiers: _n_0_t_1[_n_0_t_6], returnTypeOptionalCustomModifiers: _n_0_t_1[_n_0_t_6], parameterTypes: _n_0_t_1[_n_0_t_6], parameterTypeRequiredCustomModifiers: _n_0_t_1[_n_0_t_1[_n_0_t_6]], parameterTypeOptionalCustomModifiers: _n_0_t_1[_n_0_t_1[_n_0_t_6]], nativeCallConv: _n_6_t_14, nativeCharSet: _n_6_t_20) -> MethodBuilder:...
    def DefinePInvokeMethod(self, name: str, dllName: str, entryName: str, attributes: _n_4_t_13, callingConvention: _n_4_t_14, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6], nativeCallConv: _n_6_t_14, nativeCharSet: _n_6_t_20) -> MethodBuilder:...
    def DefinePInvokeMethod(self, name: str, dllName: str, attributes: _n_4_t_13, callingConvention: _n_4_t_14, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6], nativeCallConv: _n_6_t_14, nativeCharSet: _n_6_t_20) -> MethodBuilder:...
    def DefineProperty(self, name: str, attributes: _n_4_t_24, returnType: _n_0_t_6, returnTypeRequiredCustomModifiers: _n_0_t_1[_n_0_t_6], returnTypeOptionalCustomModifiers: _n_0_t_1[_n_0_t_6], parameterTypes: _n_0_t_1[_n_0_t_6], parameterTypeRequiredCustomModifiers: _n_0_t_1[_n_0_t_1[_n_0_t_6]], parameterTypeOptionalCustomModifiers: _n_0_t_1[_n_0_t_1[_n_0_t_6]]) -> PropertyBuilder:...
    def DefineProperty(self, name: str, attributes: _n_4_t_24, callingConvention: _n_4_t_14, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6]) -> PropertyBuilder:...
    def DefineProperty(self, name: str, attributes: _n_4_t_24, returnType: _n_0_t_6, parameterTypes: _n_0_t_1[_n_0_t_6]) -> PropertyBuilder:...
    def DefineProperty(self, name: str, attributes: _n_4_t_24, callingConvention: _n_4_t_14, returnType: _n_0_t_6, returnTypeRequiredCustomModifiers: _n_0_t_1[_n_0_t_6], returnTypeOptionalCustomModifiers: _n_0_t_1[_n_0_t_6], parameterTypes: _n_0_t_1[_n_0_t_6], parameterTypeRequiredCustomModifiers: _n_0_t_1[_n_0_t_1[_n_0_t_6]], parameterTypeOptionalCustomModifiers: _n_0_t_1[_n_0_t_1[_n_0_t_6]]) -> PropertyBuilder:...
    def DefineTypeInitializer(self) -> ConstructorBuilder:...
    def DefineUninitializedData(self, name: str, size: int, attributes: _n_4_t_22) -> FieldBuilder:...
    def IsCreated(self) -> bool:...
    def SetCustomAttribute(self, customBuilder: CustomAttributeBuilder):...
    def SetCustomAttribute(self, con: _n_4_t_6, binaryAttribute: _n_0_t_1[_n_0_t_0]):...
    def SetParent(self, parent: _n_0_t_6):...
class TypeToken(_n_0_t_10):
    Empty: int
    @property
    def Token(self) -> int:"""Token { get; } -> int"""
class UnmanagedMarshal(object):
    @property
    def BaseType(self) -> _n_6_t_26:"""BaseType { get; } -> UnmanagedType"""
    @property
    def ElementCount(self) -> int:"""ElementCount { get; } -> int"""
    @property
    def GetUnmanagedType(self) -> _n_6_t_26:"""GetUnmanagedType { get; } -> UnmanagedType"""
    @property
    def IIDGuid(self) -> _n_0_t_14:"""IIDGuid { get; } -> Guid"""
    @staticmethod
    def DefineByValArray(elemCount: int) -> UnmanagedMarshal:...
    @staticmethod
    def DefineByValTStr(elemCount: int) -> UnmanagedMarshal:...
    @staticmethod
    def DefineLPArray(elemType: _n_6_t_26) -> UnmanagedMarshal:...
    @staticmethod
    def DefineSafeArray(elemType: _n_6_t_26) -> UnmanagedMarshal:...
    @staticmethod
    def DefineUnmanagedMarshal(unmanagedType: _n_6_t_26) -> UnmanagedMarshal:...
