from __clrclasses__.System.Runtime.InteropServices.ComTypes import ADVF
from __clrclasses__.System.Runtime.InteropServices.ComTypes import BIND_OPTS
from __clrclasses__.System.Runtime.InteropServices.ComTypes import BINDPTR
from __clrclasses__.System.Runtime.InteropServices.ComTypes import CALLCONV
from __clrclasses__.System.Runtime.InteropServices.ComTypes import CONNECTDATA
from __clrclasses__.System.Runtime.InteropServices.ComTypes import DATADIR
from __clrclasses__.System.Runtime.InteropServices.ComTypes import DESCKIND
from __clrclasses__.System.Runtime.InteropServices.ComTypes import DISPPARAMS
from __clrclasses__.System.Runtime.InteropServices.ComTypes import DVASPECT
from __clrclasses__.System.Runtime.InteropServices.ComTypes import ELEMDESC
from __clrclasses__.System.Runtime.InteropServices.ComTypes import EXCEPINFO
from __clrclasses__.System.Runtime.InteropServices.ComTypes import FILETIME
from __clrclasses__.System.Runtime.InteropServices.ComTypes import FORMATETC
from __clrclasses__.System.Runtime.InteropServices.ComTypes import FUNCDESC
from __clrclasses__.System.Runtime.InteropServices.ComTypes import FUNCFLAGS
from __clrclasses__.System.Runtime.InteropServices.ComTypes import FUNCKIND
from __clrclasses__.System.Runtime.InteropServices.ComTypes import IAdviseSink
from __clrclasses__.System.Runtime.InteropServices.ComTypes import IBindCtx
from __clrclasses__.System.Runtime.InteropServices.ComTypes import IConnectionPoint
from __clrclasses__.System.Runtime.InteropServices.ComTypes import IConnectionPointContainer
from __clrclasses__.System.Runtime.InteropServices.ComTypes import IDataObject
from __clrclasses__.System.Runtime.InteropServices.ComTypes import IDLDESC
from __clrclasses__.System.Runtime.InteropServices.ComTypes import IDLFLAG
from __clrclasses__.System.Runtime.InteropServices.ComTypes import IEnumConnectionPoints
from __clrclasses__.System.Runtime.InteropServices.ComTypes import IEnumConnections
from __clrclasses__.System.Runtime.InteropServices.ComTypes import IEnumFORMATETC
from __clrclasses__.System.Runtime.InteropServices.ComTypes import IEnumMoniker
from __clrclasses__.System.Runtime.InteropServices.ComTypes import IEnumSTATDATA
from __clrclasses__.System.Runtime.InteropServices.ComTypes import IEnumString
from __clrclasses__.System.Runtime.InteropServices.ComTypes import IEnumVARIANT
from __clrclasses__.System.Runtime.InteropServices.ComTypes import IMoniker
from __clrclasses__.System.Runtime.InteropServices.ComTypes import IMPLTYPEFLAGS
from __clrclasses__.System.Runtime.InteropServices.ComTypes import INVOKEKIND
from __clrclasses__.System.Runtime.InteropServices.ComTypes import IPersistFile
from __clrclasses__.System.Runtime.InteropServices.ComTypes import IRunningObjectTable
from __clrclasses__.System.Runtime.InteropServices.ComTypes import IStream
from __clrclasses__.System.Runtime.InteropServices.ComTypes import ITypeComp
from __clrclasses__.System.Runtime.InteropServices.ComTypes import ITypeInfo
from __clrclasses__.System.Runtime.InteropServices.ComTypes import ITypeInfo2
from __clrclasses__.System.Runtime.InteropServices.ComTypes import ITypeLib
from __clrclasses__.System.Runtime.InteropServices.ComTypes import ITypeLib2
from __clrclasses__.System.Runtime.InteropServices.ComTypes import LIBFLAGS
from __clrclasses__.System.Runtime.InteropServices.ComTypes import PARAMDESC
from __clrclasses__.System.Runtime.InteropServices.ComTypes import PARAMFLAG
from __clrclasses__.System.Runtime.InteropServices.ComTypes import STATDATA
from __clrclasses__.System.Runtime.InteropServices.ComTypes import STATSTG
from __clrclasses__.System.Runtime.InteropServices.ComTypes import STGMEDIUM
from __clrclasses__.System.Runtime.InteropServices.ComTypes import SYSKIND
from __clrclasses__.System.Runtime.InteropServices.ComTypes import TYMED
from __clrclasses__.System.Runtime.InteropServices.ComTypes import TYPEATTR
from __clrclasses__.System.Runtime.InteropServices.ComTypes import TYPEDESC
from __clrclasses__.System.Runtime.InteropServices.ComTypes import TYPEFLAGS
from __clrclasses__.System.Runtime.InteropServices.ComTypes import TYPEKIND
from __clrclasses__.System.Runtime.InteropServices.ComTypes import TYPELIBATTR
from __clrclasses__.System.Runtime.InteropServices.ComTypes import VARDESC
from __clrclasses__.System.Runtime.InteropServices.ComTypes import VARFLAGS
from __clrclasses__.System.Runtime.InteropServices.ComTypes import VARKIND
