from __clrclasses__.System import Attribute as _n_0_t_0
from __clrclasses__.System import Type as _n_0_t_1
from __clrclasses__.System import ValueType as _n_0_t_2
from __clrclasses__.System import Exception as _n_0_t_3
from __clrclasses__.System import Array as _n_0_t_4
from __clrclasses__.System import Enum as _n_0_t_5
from __clrclasses__.System import IComparable as _n_0_t_6
from __clrclasses__.System import IFormattable as _n_0_t_7
from __clrclasses__.System import IConvertible as _n_0_t_8
from __clrclasses__.System import MulticastDelegate as _n_0_t_9
from __clrclasses__.System import ICloneable as _n_0_t_10
from __clrclasses__.System import IntPtr as _n_0_t_11
from __clrclasses__.System import IAsyncResult as _n_0_t_12
from __clrclasses__.System import AsyncCallback as _n_0_t_13
from __clrclasses__.System import Decimal as _n_0_t_14
from __clrclasses__.System import Byte as _n_0_t_15
from __clrclasses__.System import UInt32 as _n_0_t_16
from __clrclasses__.System import Delegate as _n_0_t_17
from __clrclasses__.System import FormattableString as _n_0_t_18
from __clrclasses__.System import Action as _n_0_t_19
from __clrclasses__.System import RuntimeFieldHandle as _n_0_t_20
from __clrclasses__.System import RuntimeMethodHandle as _n_0_t_21
from __clrclasses__.System import RuntimeTypeHandle as _n_0_t_22
from __clrclasses__.System import ModuleHandle as _n_0_t_23
from __clrclasses__.System.Collections import IList as _n_1_t_0
from __clrclasses__.System.Collections.Generic import IList as _n_2_t_0
from __clrclasses__.System.Collections.Generic import IEnumerable as _n_2_t_1
from __clrclasses__.System.Collections.ObjectModel import ReadOnlyCollection as _n_3_t_0
from __clrclasses__.System.Diagnostics.Contracts import ContractFailureKind as _n_4_t_0
from __clrclasses__.System.Dynamic import ExpandoObject as _n_5_t_0
from __clrclasses__.System.Linq.Expressions import LabelTarget as _n_6_t_0
from __clrclasses__.System.Linq.Expressions import Expression as _n_6_t_1
from __clrclasses__.System.Linq.Expressions import ParameterExpression as _n_6_t_2
from __clrclasses__.System.Linq.Expressions import LambdaExpression as _n_6_t_3
from __clrclasses__.System.Linq.Expressions import DebugInfoExpression as _n_6_t_4
from __clrclasses__.System.Reflection import MethodBase as _n_7_t_0
from __clrclasses__.System.Runtime.InteropServices import _Attribute as _n_8_t_0
from __clrclasses__.System.Runtime.InteropServices import _Exception as _n_8_t_1
from __clrclasses__.System.Runtime.Serialization import ISerializable as _n_9_t_0
from __clrclasses__.System.Threading.Tasks import Task as _n_10_t_0
import typing
TResult = typing.TypeVar('TResult')
T = typing.TypeVar('T')
TKey = typing.TypeVar('TKey')
TValue = typing.TypeVar('TValue')
class AccessedThroughPropertyAttribute(_n_0_t_0, _n_8_t_0):
    @property
    def PropertyName(self) -> str:"""PropertyName { get; } -> str"""
    def __init__(self, propertyName: str) -> AccessedThroughPropertyAttribute:...
class AsyncStateMachineAttribute(StateMachineAttribute, _n_8_t_0):
    def __init__(self, stateMachineType: _n_0_t_1) -> AsyncStateMachineAttribute:...
class AsyncTaskMethodBuilder(_n_0_t_2, typing.Generic[TResult]):
    @property
    def Task(self) -> _n_10_t_0[TResult]:"""Task { get; } -> Task"""
    def AwaitOnCompleted(self, awaiter: object, stateMachine: object):...
    def AwaitUnsafeOnCompleted(self, awaiter: object, stateMachine: object):...
    @staticmethod
    def Create() -> AsyncTaskMethodBuilder[TResult]:...
    def SetException(self, exception: _n_0_t_3):...
    def SetResult(self, result: TResult):...
    def SetStateMachine(self, stateMachine: IAsyncStateMachine):...
    def Start(self, stateMachine: object):...
class AsyncVoidMethodBuilder(_n_0_t_2):
    def AwaitOnCompleted(self, awaiter: object, stateMachine: object):...
    def AwaitUnsafeOnCompleted(self, awaiter: object, stateMachine: object):...
    @staticmethod
    def Create() -> AsyncVoidMethodBuilder:...
    def SetException(self, exception: _n_0_t_3):...
    def SetResult(self):...
    def SetStateMachine(self, stateMachine: IAsyncStateMachine):...
    def Start(self, stateMachine: object):...
class CallConvCdecl(object):
    def __init__(self) -> CallConvCdecl:...
class CallConvFastcall(object):
    def __init__(self) -> CallConvFastcall:...
class CallConvStdcall(object):
    def __init__(self) -> CallConvStdcall:...
class CallConvThiscall(object):
    def __init__(self) -> CallConvThiscall:...
class CallerFilePathAttribute(_n_0_t_0, _n_8_t_0):
    def __init__(self) -> CallerFilePathAttribute:...
class CallerLineNumberAttribute(_n_0_t_0, _n_8_t_0):
    def __init__(self) -> CallerLineNumberAttribute:...
class CallerMemberNameAttribute(_n_0_t_0, _n_8_t_0):
    def __init__(self) -> CallerMemberNameAttribute:...
class CallSite(CallSite, typing.Generic[T]):
    Target: int
    @property
    def Update(self) -> T:"""Update { get; } -> T"""
class CallSiteBinder(object):
    @property
    def UpdateLabel(self) -> _n_6_t_0:"""UpdateLabel { get; } -> LabelTarget"""
    def Bind(self, args: _n_0_t_4[object], parameters: _n_3_t_0[_n_6_t_2], returnLabel: _n_6_t_0) -> _n_6_t_1:...
    def BindDelegate(self, site: CallSite[typing.Any], args: _n_0_t_4[object]) -> typing.Any:...
class CallSiteHelpers(object):
    @staticmethod
    def IsInternalFrame(mb: _n_7_t_0) -> bool:...
class CallSiteOps(object):
    @staticmethod
    def AddRule(site: CallSite[typing.Any], rule: typing.Any):...
    @staticmethod
    def Bind(binder: CallSiteBinder, site: CallSite[typing.Any], args: _n_0_t_4[object]) -> typing.Any:...
    @staticmethod
    def ClearMatch(site: CallSite):...
    @staticmethod
    def CreateMatchmaker(site: CallSite[typing.Any]) -> CallSite[typing.Any]:...
    @staticmethod
    def GetCachedRules(cache: RuleCache[typing.Any]) -> _n_0_t_4[typing.Any]:...
    @staticmethod
    def GetMatch(site: CallSite) -> bool:...
    @staticmethod
    def GetRuleCache(site: CallSite[typing.Any]) -> RuleCache[typing.Any]:...
    @staticmethod
    def GetRules(site: CallSite[typing.Any]) -> _n_0_t_4[typing.Any]:...
    @staticmethod
    def MoveRule(cache: RuleCache[typing.Any], rule: typing.Any, i: int):...
    @staticmethod
    def SetNotMatched(site: CallSite) -> bool:...
    @staticmethod
    def UpdateRules(this: CallSite[typing.Any], matched: int):...
class Closure(object):
    Constants: int
    Locals: int
    def __init__(self, constants: _n_0_t_4[object], locals: _n_0_t_4[object]) -> Closure:...
class CompilationRelaxations(_n_0_t_5, _n_0_t_6, _n_0_t_7, _n_0_t_8):
    NoStringInterning: int
    value__: int
class CompilationRelaxationsAttribute(_n_0_t_0, _n_8_t_0):
    @property
    def CompilationRelaxations(self) -> int:"""CompilationRelaxations { get; } -> int"""
    def __init__(self, relaxations: int) -> CompilationRelaxationsAttribute:...
    def __init__(self, relaxations: CompilationRelaxations) -> CompilationRelaxationsAttribute:...
class CompilerGeneratedAttribute(_n_0_t_0, _n_8_t_0):
    def __init__(self) -> CompilerGeneratedAttribute:...
class CompilerGlobalScopeAttribute(_n_0_t_0, _n_8_t_0):
    def __init__(self) -> CompilerGlobalScopeAttribute:...
class CompilerMarshalOverride(object):
    pass
class ConditionalWeakTable(typing.Generic[TKey, TValue]):
    def __init__(self) -> ConditionalWeakTable:...
    def Add(self, key: TKey, value: TValue):...
    def GetOrCreateValue(self, key: TKey) -> TValue:...
    def GetValue(self, key: TKey, createValueCallback: ConditionalWeakTable.CreateValueCallback[TKey, TValue]) -> TValue:...
    def Remove(self, key: TKey) -> bool:...
    def TryGetValue(self, key: TKey, value: object) -> bool:...
    class CreateValueCallback(_n_0_t_9, _n_0_t_10, _n_9_t_0, typing.Generic[TKey, TValue]):
        def __init__(self, object: object, method: _n_0_t_11) -> ConditionalWeakTable.CreateValueCallback:...
        def BeginInvoke(self, key: TKey, callback: _n_0_t_13, object: object) -> _n_0_t_12:...
        def EndInvoke(self, result: _n_0_t_12) -> TValue:...
        def Invoke(self, key: TKey) -> TValue:...
class ConfiguredTaskAwaitable(_n_0_t_2, typing.Generic[TResult]):
    def GetAwaiter(self) -> ConfiguredTaskAwaitable.ConfiguredTaskAwaiter[TResult]:...
    class ConfiguredTaskAwaiter(_n_0_t_2, ICriticalNotifyCompletion, typing.Generic[TResult]):
        @property
        def IsCompleted(self) -> bool:"""IsCompleted { get; } -> bool"""
        def GetResult(self) -> TResult:...
class ContractHelper(object):
    @staticmethod
    def RaiseContractFailedEvent(failureKind: _n_4_t_0, userMessage: str, conditionText: str, innerException: _n_0_t_3) -> str:...
    @staticmethod
    def TriggerFailure(kind: _n_4_t_0, displayMessage: str, userMessage: str, conditionText: str, innerException: _n_0_t_3):...
class CustomConstantAttribute(_n_0_t_0, _n_8_t_0):
    @property
    def Value(self) -> object:"""Value { get; } -> object"""
class DateTimeConstantAttribute(CustomConstantAttribute, _n_8_t_0):
    def __init__(self, ticks: int) -> DateTimeConstantAttribute:...
class DebugInfoGenerator(object):
    @staticmethod
    def CreatePdbGenerator() -> DebugInfoGenerator:...
    def MarkSequencePoint(self, method: _n_6_t_3, ilOffset: int, sequencePoint: _n_6_t_4):...
class DecimalConstantAttribute(_n_0_t_0, _n_8_t_0):
    @property
    def Value(self) -> _n_0_t_14:"""Value { get; } -> Decimal"""
    def __init__(self, scale: _n_0_t_15, sign: _n_0_t_15, hi: _n_0_t_16, mid: _n_0_t_16, low: _n_0_t_16) -> DecimalConstantAttribute:...
    def __init__(self, scale: _n_0_t_15, sign: _n_0_t_15, hi: int, mid: int, low: int) -> DecimalConstantAttribute:...
class DefaultDependencyAttribute(_n_0_t_0, _n_8_t_0):
    @property
    def LoadHint(self) -> LoadHint:"""LoadHint { get; } -> LoadHint"""
    def __init__(self, loadHintArgument: LoadHint) -> DefaultDependencyAttribute:...
class DependencyAttribute(_n_0_t_0, _n_8_t_0):
    @property
    def DependentAssembly(self) -> str:"""DependentAssembly { get; } -> str"""
    @property
    def LoadHint(self) -> LoadHint:"""LoadHint { get; } -> LoadHint"""
    def __init__(self, dependentAssemblyArgument: str, loadHintArgument: LoadHint) -> DependencyAttribute:...
class DisablePrivateReflectionAttribute(_n_0_t_0, _n_8_t_0):
    def __init__(self) -> DisablePrivateReflectionAttribute:...
class DiscardableAttribute(_n_0_t_0, _n_8_t_0):
    def __init__(self) -> DiscardableAttribute:...
class DynamicAttribute(_n_0_t_0, _n_8_t_0):
    @property
    def TransformFlags(self) -> _n_2_t_0[bool]:"""TransformFlags { get; } -> IList"""
    def __init__(self, transformFlags: _n_0_t_4[bool]) -> DynamicAttribute:...
    def __init__(self) -> DynamicAttribute:...
class ExecutionScope(object):
    Globals: int
    Locals: int
    Parent: int
    def CreateDelegate(self, indexLambda: int, locals: _n_0_t_4[object]) -> _n_0_t_17:...
    def CreateHoistedLocals(self) -> _n_0_t_4[object]:...
    def IsolateExpression(self, expression: _n_6_t_1, locals: _n_0_t_4[object]) -> _n_6_t_1:...
class ExtensionAttribute(_n_0_t_0, _n_8_t_0):
    def __init__(self) -> ExtensionAttribute:...
class FixedAddressValueTypeAttribute(_n_0_t_0, _n_8_t_0):
    def __init__(self) -> FixedAddressValueTypeAttribute:...
class FixedBufferAttribute(_n_0_t_0, _n_8_t_0):
    @property
    def ElementType(self) -> _n_0_t_1:"""ElementType { get; } -> Type"""
    @property
    def Length(self) -> int:"""Length { get; } -> int"""
    def __init__(self, elementType: _n_0_t_1, length: int) -> FixedBufferAttribute:...
class FormattableStringFactory(object):
    @staticmethod
    def Create(format: str, arguments: _n_0_t_4[object]) -> _n_0_t_18:...
class HasCopySemanticsAttribute(_n_0_t_0, _n_8_t_0):
    def __init__(self) -> HasCopySemanticsAttribute:...
class IAsyncStateMachine():
    def MoveNext(self):...
    def SetStateMachine(self, stateMachine: IAsyncStateMachine):...
class ICriticalNotifyCompletion(INotifyCompletion):
    def UnsafeOnCompleted(self, continuation: _n_0_t_19):...
class IDispatchConstantAttribute(CustomConstantAttribute, _n_8_t_0):
    def __init__(self) -> IDispatchConstantAttribute:...
class IndexerNameAttribute(_n_0_t_0, _n_8_t_0):
    def __init__(self, indexerName: str) -> IndexerNameAttribute:...
class INotifyCompletion():
    def OnCompleted(self, continuation: _n_0_t_19):...
class InternalsVisibleToAttribute(_n_0_t_0, _n_8_t_0):
    @property
    def AllInternalsVisible(self) -> bool:"""AllInternalsVisible { get; set; } -> bool"""
    @property
    def AssemblyName(self) -> str:"""AssemblyName { get; } -> str"""
    def __init__(self, assemblyName: str) -> InternalsVisibleToAttribute:...
class IRuntimeVariables():
    @property
    def Count(self) -> int:"""Count { get; } -> int"""
    @property
    def Item(self) -> object:"""Item { get; set; } -> object"""
class IsBoxed(object):
    pass
class IsByRefLikeAttribute(_n_0_t_0, _n_8_t_0):
    def __init__(self) -> IsByRefLikeAttribute:...
class IsByValue(object):
    pass
class IsConst(object):
    pass
class IsCopyConstructed(object):
    pass
class IsExplicitlyDereferenced(object):
    pass
class IsImplicitlyDereferenced(object):
    pass
class IsJitIntrinsic(object):
    pass
class IsLong(object):
    pass
class IsPinned(object):
    pass
class IsReadOnlyAttribute(_n_0_t_0, _n_8_t_0):
    def __init__(self) -> IsReadOnlyAttribute:...
class IsSignUnspecifiedByte(object):
    pass
class IStrongBox():
    @property
    def Value(self) -> object:"""Value { get; set; } -> object"""
class IsUdtReturn(object):
    pass
class IsVolatile(object):
    pass
class IteratorStateMachineAttribute(StateMachineAttribute, _n_8_t_0):
    def __init__(self, stateMachineType: _n_0_t_1) -> IteratorStateMachineAttribute:...
class ITuple():
    @property
    def Item(self) -> object:"""Item { get; } -> object"""
    @property
    def Length(self) -> int:"""Length { get; } -> int"""
class IUnknownConstantAttribute(CustomConstantAttribute, _n_8_t_0):
    def __init__(self) -> IUnknownConstantAttribute:...
class LoadHint(_n_0_t_5, _n_0_t_6, _n_0_t_7, _n_0_t_8):
    Always: int
    Default: int
    Sometimes: int
    value__: int
class MethodCodeType(_n_0_t_5, _n_0_t_6, _n_0_t_7, _n_0_t_8):
    IL: int
    Native: int
    OPTIL: int
    Runtime: int
    value__: int
class MethodImplAttribute(_n_0_t_0, _n_8_t_0):
    MethodCodeType: int
    @property
    def Value(self) -> MethodImplOptions:"""Value { get; } -> MethodImplOptions"""
    def __init__(self, methodImplOptions: MethodImplOptions) -> MethodImplAttribute:...
    def __init__(self, value: int) -> MethodImplAttribute:...
    def __init__(self) -> MethodImplAttribute:...
class MethodImplOptions(_n_0_t_5, _n_0_t_6, _n_0_t_7, _n_0_t_8):
    AggressiveInlining: int
    ForwardRef: int
    InternalCall: int
    NoInlining: int
    NoOptimization: int
    PreserveSig: int
    Synchronized: int
    Unmanaged: int
    value__: int
class NativeCppClassAttribute(_n_0_t_0, _n_8_t_0):
    def __init__(self) -> NativeCppClassAttribute:...
class ReadOnlyCollectionBuilder(_n_2_t_0[T], _n_1_t_0, typing.Generic[T], typing.Iterable[T]):
    @property
    def Capacity(self) -> int:"""Capacity { get; set; } -> int"""
    def __init__(self, collection: _n_2_t_1[T]) -> ReadOnlyCollectionBuilder:...
    def __init__(self, capacity: int) -> ReadOnlyCollectionBuilder:...
    def __init__(self) -> ReadOnlyCollectionBuilder:...
    def Reverse(self, index: int, count: int):...
    def Reverse(self):...
    def ToArray(self) -> _n_0_t_4[T]:...
    def ToReadOnlyCollection(self) -> _n_3_t_0[T]:...
class ReferenceAssemblyAttribute(_n_0_t_0, _n_8_t_0):
    @property
    def Description(self) -> str:"""Description { get; } -> str"""
    def __init__(self) -> ReferenceAssemblyAttribute:...
    def __init__(self, description: str) -> ReferenceAssemblyAttribute:...
class RequiredAttributeAttribute(_n_0_t_0, _n_8_t_0):
    @property
    def RequiredContract(self) -> _n_0_t_1:"""RequiredContract { get; } -> Type"""
    def __init__(self, requiredContract: _n_0_t_1) -> RequiredAttributeAttribute:...
class RuleCache(typing.Generic[T]):
    pass
class RuntimeCompatibilityAttribute(_n_0_t_0, _n_8_t_0):
    @property
    def WrapNonExceptionThrows(self) -> bool:"""WrapNonExceptionThrows { get; set; } -> bool"""
    def __init__(self) -> RuntimeCompatibilityAttribute:...
class RuntimeFeature(object):
    PortablePdb: int
    @staticmethod
    def IsSupported(feature: str) -> bool:...
class RuntimeHelpers(object):
    @property
    def OffsetToStringData(self) -> int:"""OffsetToStringData { get; } -> int"""
    @staticmethod
    def EnsureSufficientExecutionStack():...
    @staticmethod
    def ExecuteCodeWithGuaranteedCleanup(code: RuntimeHelpers.TryCode, backoutCode: RuntimeHelpers.CleanupCode, userData: object):...
    @staticmethod
    def GetObjectValue(obj: object) -> object:...
    @staticmethod
    def InitializeArray(array: _n_0_t_4, fldHandle: _n_0_t_20):...
    @staticmethod
    def PrepareConstrainedRegions():...
    @staticmethod
    def PrepareConstrainedRegionsNoOP():...
    @staticmethod
    def PrepareContractedDelegate(d: _n_0_t_17):...
    @staticmethod
    def PrepareDelegate(d: _n_0_t_17):...
    @staticmethod
    def PrepareMethod(method: _n_0_t_21):...
    @staticmethod
    def PrepareMethod(method: _n_0_t_21, instantiation: _n_0_t_4[_n_0_t_22]):...
    @staticmethod
    def ProbeForSufficientStack():...
    @staticmethod
    def RunClassConstructor(type: _n_0_t_22):...
    @staticmethod
    def RunModuleConstructor(module: _n_0_t_23):...
    class CleanupCode(_n_0_t_9, _n_0_t_10, _n_9_t_0):
        def __init__(self, object: object, method: _n_0_t_11) -> RuntimeHelpers.CleanupCode:...
        def BeginInvoke(self, userData: object, exceptionThrown: bool, callback: _n_0_t_13, object: object) -> _n_0_t_12:...
        def EndInvoke(self, result: _n_0_t_12):...
        def Invoke(self, userData: object, exceptionThrown: bool):...
    class TryCode(_n_0_t_9, _n_0_t_10, _n_9_t_0):
        def __init__(self, object: object, method: _n_0_t_11) -> RuntimeHelpers.TryCode:...
        def BeginInvoke(self, userData: object, callback: _n_0_t_13, object: object) -> _n_0_t_12:...
        def EndInvoke(self, result: _n_0_t_12):...
        def Invoke(self, userData: object):...
class RuntimeOps(object):
    @staticmethod
    def CreateRuntimeVariables() -> IRuntimeVariables:...
    @staticmethod
    def CreateRuntimeVariables(data: _n_0_t_4[object], indexes: _n_0_t_4[int]) -> IRuntimeVariables:...
    @staticmethod
    def ExpandoCheckVersion(expando: _n_5_t_0, version: object) -> bool:...
    @staticmethod
    def ExpandoPromoteClass(expando: _n_5_t_0, oldClass: object, newClass: object):...
    @staticmethod
    def ExpandoTryDeleteValue(expando: _n_5_t_0, indexClass: object, index: int, name: str, ignoreCase: bool) -> bool:...
    @staticmethod
    def ExpandoTryGetValue(expando: _n_5_t_0, indexClass: object, index: int, name: str, ignoreCase: bool, value: object) -> bool:...
    @staticmethod
    def ExpandoTrySetValue(expando: _n_5_t_0, indexClass: object, index: int, value: object, name: str, ignoreCase: bool) -> object:...
    @staticmethod
    def MergeRuntimeVariables(first: IRuntimeVariables, second: IRuntimeVariables, indexes: _n_0_t_4[int]) -> IRuntimeVariables:...
    @staticmethod
    def Quote(expression: _n_6_t_1, hoistedLocals: object, locals: _n_0_t_4[object]) -> _n_6_t_1:...
class RuntimeWrappedException(_n_0_t_3, _n_9_t_0, _n_8_t_1):
    @property
    def WrappedException(self) -> object:"""WrappedException { get; } -> object"""
class ScopelessEnumAttribute(_n_0_t_0, _n_8_t_0):
    def __init__(self) -> ScopelessEnumAttribute:...
class SpecialNameAttribute(_n_0_t_0, _n_8_t_0):
    def __init__(self) -> SpecialNameAttribute:...
class StateMachineAttribute(_n_0_t_0, _n_8_t_0):
    @property
    def StateMachineType(self) -> _n_0_t_1:"""StateMachineType { get; set; } -> Type"""
    def __init__(self, stateMachineType: _n_0_t_1) -> StateMachineAttribute:...
class StringFreezingAttribute(_n_0_t_0, _n_8_t_0):
    def __init__(self) -> StringFreezingAttribute:...
class StrongBox(IStrongBox, typing.Generic[T]):
    Value: int
    def __init__(self, value: T) -> StrongBox:...
    def __init__(self) -> StrongBox:...
class SuppressIldasmAttribute(_n_0_t_0, _n_8_t_0):
    def __init__(self) -> SuppressIldasmAttribute:...
class TaskAwaiter(_n_0_t_2, ICriticalNotifyCompletion, typing.Generic[TResult]):
    @property
    def IsCompleted(self) -> bool:"""IsCompleted { get; } -> bool"""
    def GetResult(self) -> TResult:...
class TupleElementNamesAttribute(_n_0_t_0, _n_8_t_0):
    @property
    def TransformNames(self) -> _n_2_t_0[str]:"""TransformNames { get; } -> IList"""
    def __init__(self, transformNames: _n_0_t_4[str]) -> TupleElementNamesAttribute:...
class TypeForwardedFromAttribute(_n_0_t_0, _n_8_t_0):
    @property
    def AssemblyFullName(self) -> str:"""AssemblyFullName { get; } -> str"""
    def __init__(self, assemblyFullName: str) -> TypeForwardedFromAttribute:...
class TypeForwardedToAttribute(_n_0_t_0, _n_8_t_0):
    @property
    def Destination(self) -> _n_0_t_1:"""Destination { get; } -> Type"""
    def __init__(self, destination: _n_0_t_1) -> TypeForwardedToAttribute:...
class UnsafeValueTypeAttribute(_n_0_t_0, _n_8_t_0):
    def __init__(self) -> UnsafeValueTypeAttribute:...
class YieldAwaitable(_n_0_t_2):
    def GetAwaiter(self) -> YieldAwaitable.YieldAwaiter:...
    class YieldAwaiter(_n_0_t_2, ICriticalNotifyCompletion):
        @property
        def IsCompleted(self) -> bool:"""IsCompleted { get; } -> bool"""
        def GetResult(self):...
