from __clrclasses__.System.Runtime.Remoting.Activation import ActivatorLevel
from __clrclasses__.System.Runtime.Remoting.Activation import IActivator
from __clrclasses__.System.Runtime.Remoting.Activation import IConstructionCallMessage
from __clrclasses__.System.Runtime.Remoting.Activation import IConstructionReturnMessage
from __clrclasses__.System.Runtime.Remoting.Activation import UrlAttribute
